// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package interconnect

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/interconnect/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithytesting "github.com/aws/smithy-go/testing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"testing"
)

const serdeRespSSPrefix = "serde_response_snapshot"

func serdeRespSSPath(op string) string {
	return fmt.Sprintf("%s/%s.response.snap", serdeRespSSPrefix, op)
}

// serdeRespReadSnapshot parses a frozen wire response fixture: a status-code
// line, HTTP headers, a blank line, then the raw body.
func serdeRespReadSnapshot(op string) (int, http.Header, []byte, error) {
	raw, err := os.ReadFile(serdeRespSSPath(op))
	if err != nil {
		return 0, nil, nil, err
	}

	r := bufio.NewReader(bytes.NewReader(raw))
	statusLine, err := r.ReadString('\n')
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read status line: %w", err)
	}
	status, err := strconv.Atoi(strings.TrimSpace(statusLine))
	if err != nil {
		return 0, nil, nil, fmt.Errorf("parse status: %w", err)
	}

	header := http.Header{}
	for {
		line, err := r.ReadString('\n')
		if err != nil && err != io.EOF {
			return 0, nil, nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		k, v, ok := strings.Cut(trimmed, ": ")
		if !ok {
			return 0, nil, nil, fmt.Errorf("malformed header %q", trimmed)
		}
		header.Add(k, v)
		if err == io.EOF {
			break
		}
	}

	body, err := io.ReadAll(r)
	if err != nil {
		return 0, nil, nil, err
	}
	return status, header, body, nil
}

type serdeRespEndpointResolver struct{}

func (*serdeRespEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeRespClient(status int, header http.Header, body []byte) *Client {
	return New(Options{
		Region: "us-east-1",
		HTTPClient: smithyhttp.ClientDoFunc(func(req *http.Request) (*http.Response, error) {
			resp := &http.Response{StatusCode: status, Header: header, Request: req}
			if len(body) > 0 {
				resp.ContentLength = int64(len(body))
				resp.Body = io.NopCloser(bytes.NewReader(body))
			} else {
				resp.Body = http.NoBody
			}
			return resp, nil
		}),
		EndpointResolverV2: &serdeRespEndpointResolver{},
		APIOptions: []func(*middleware.Stack) error{
			func(s *middleware.Stack) error {
				s.Finalize.Clear()
				s.Initialize.Remove("OperationInputValidation")
				return nil
			},
		},
	})
}
func TestSerdeCheckResponseSnapshot_AcceptConnectionProposal(t *testing.T) {
	want := &AcceptConnectionProposalOutput{
		Connection: &types.Connection{
			Id:          ptr.String("__Id__"),
			Arn:         ptr.String("__Arn__"),
			Description: ptr.String("__Description__"),
			Bandwidth:   ptr.String("__Bandwidth__"),
			AttachPoint: &types.AttachPointMemberDirectConnectGateway{
				Value: "__AttachPointMemberDirectConnectGateway__",
			},
			EnvironmentId: ptr.String("__EnvironmentId__"),
			Provider: &types.ProviderMemberCloudServiceProvider{
				Value: "__ProviderMemberCloudServiceProvider__",
			},
			Location:      ptr.String("__Location__"),
			Type:          ptr.String("__Type__"),
			State:         types.ConnectionState("available"),
			SharedId:      ptr.String("__SharedId__"),
			BillingTier:   ptr.Int32(1),
			OwnerAccount:  ptr.String("__OwnerAccount__"),
			ActivationKey: ptr.String("__ActivationKey__"),
			Tags: map[string]string{
				"key0": "__Value__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("AcceptConnectionProposal")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.AcceptConnectionProposal(context.Background(), &AcceptConnectionProposalInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "AcceptConnectionProposal", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateConnection(t *testing.T) {
	want := &CreateConnectionOutput{
		Connection: &types.Connection{
			Id:          ptr.String("__Id__"),
			Arn:         ptr.String("__Arn__"),
			Description: ptr.String("__Description__"),
			Bandwidth:   ptr.String("__Bandwidth__"),
			AttachPoint: &types.AttachPointMemberDirectConnectGateway{
				Value: "__AttachPointMemberDirectConnectGateway__",
			},
			EnvironmentId: ptr.String("__EnvironmentId__"),
			Provider: &types.ProviderMemberCloudServiceProvider{
				Value: "__ProviderMemberCloudServiceProvider__",
			},
			Location:      ptr.String("__Location__"),
			Type:          ptr.String("__Type__"),
			State:         types.ConnectionState("available"),
			SharedId:      ptr.String("__SharedId__"),
			BillingTier:   ptr.Int32(1),
			OwnerAccount:  ptr.String("__OwnerAccount__"),
			ActivationKey: ptr.String("__ActivationKey__"),
			Tags: map[string]string{
				"key0": "__Value__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("CreateConnection")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateConnection(context.Background(), &CreateConnectionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateConnection", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteConnection(t *testing.T) {
	want := &DeleteConnectionOutput{
		Connection: &types.Connection{
			Id:          ptr.String("__Id__"),
			Arn:         ptr.String("__Arn__"),
			Description: ptr.String("__Description__"),
			Bandwidth:   ptr.String("__Bandwidth__"),
			AttachPoint: &types.AttachPointMemberDirectConnectGateway{
				Value: "__AttachPointMemberDirectConnectGateway__",
			},
			EnvironmentId: ptr.String("__EnvironmentId__"),
			Provider: &types.ProviderMemberCloudServiceProvider{
				Value: "__ProviderMemberCloudServiceProvider__",
			},
			Location:      ptr.String("__Location__"),
			Type:          ptr.String("__Type__"),
			State:         types.ConnectionState("available"),
			SharedId:      ptr.String("__SharedId__"),
			BillingTier:   ptr.Int32(1),
			OwnerAccount:  ptr.String("__OwnerAccount__"),
			ActivationKey: ptr.String("__ActivationKey__"),
			Tags: map[string]string{
				"key0": "__Value__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DeleteConnection")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteConnection(context.Background(), &DeleteConnectionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteConnection", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeConnectionProposal(t *testing.T) {
	want := &DescribeConnectionProposalOutput{
		Bandwidth:     ptr.String("__Bandwidth__"),
		EnvironmentId: ptr.String("__EnvironmentId__"),
		Provider: &types.ProviderMemberCloudServiceProvider{
			Value: "__ProviderMemberCloudServiceProvider__",
		},
		Location: ptr.String("__Location__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeConnectionProposal")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeConnectionProposal(context.Background(), &DescribeConnectionProposalInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeConnectionProposal", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetConnection(t *testing.T) {
	want := &GetConnectionOutput{
		Connection: &types.Connection{
			Id:          ptr.String("__Id__"),
			Arn:         ptr.String("__Arn__"),
			Description: ptr.String("__Description__"),
			Bandwidth:   ptr.String("__Bandwidth__"),
			AttachPoint: &types.AttachPointMemberDirectConnectGateway{
				Value: "__AttachPointMemberDirectConnectGateway__",
			},
			EnvironmentId: ptr.String("__EnvironmentId__"),
			Provider: &types.ProviderMemberCloudServiceProvider{
				Value: "__ProviderMemberCloudServiceProvider__",
			},
			Location:      ptr.String("__Location__"),
			Type:          ptr.String("__Type__"),
			State:         types.ConnectionState("available"),
			SharedId:      ptr.String("__SharedId__"),
			BillingTier:   ptr.Int32(1),
			OwnerAccount:  ptr.String("__OwnerAccount__"),
			ActivationKey: ptr.String("__ActivationKey__"),
			Tags: map[string]string{
				"key0": "__Value__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetConnection")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetConnection(context.Background(), &GetConnectionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetConnection", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetEnvironment(t *testing.T) {
	want := &GetEnvironmentOutput{
		Environment: &types.Environment{
			Provider: &types.ProviderMemberCloudServiceProvider{
				Value: "__ProviderMemberCloudServiceProvider__",
			},
			Location:      ptr.String("__Location__"),
			EnvironmentId: ptr.String("__EnvironmentId__"),
			State:         types.EnvironmentState("available"),
			Bandwidths: &types.Bandwidths{
				Available: []string{
					"__Member__",
					"__Member__",
				},
				Supported: []string{
					"__Member__",
					"__Member__",
				},
			},
			Type:                 ptr.String("__Type__"),
			ActivationPageUrl:    ptr.String("__ActivationPageUrl__"),
			RemoteIdentifierType: types.RemoteAccountIdentifierType("account"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetEnvironment")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetEnvironment(context.Background(), &GetEnvironmentInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetEnvironment", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListAttachPoints(t *testing.T) {
	want := &ListAttachPointsOutput{
		AttachPoints: []types.AttachPointDescriptor{
			{
				Type:       types.AttachPointType("DirectConnectGateway"),
				Identifier: ptr.String("__Identifier__"),
				Name:       ptr.String("__Name__"),
			},
			{
				Type:       types.AttachPointType("DirectConnectGateway"),
				Identifier: ptr.String("__Identifier__"),
				Name:       ptr.String("__Name__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListAttachPoints")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListAttachPoints(context.Background(), &ListAttachPointsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListAttachPoints", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListConnections(t *testing.T) {
	want := &ListConnectionsOutput{
		Connections: []types.ConnectionSummary{
			{
				Id:          ptr.String("__Id__"),
				Arn:         ptr.String("__Arn__"),
				Description: ptr.String("__Description__"),
				Bandwidth:   ptr.String("__Bandwidth__"),
				AttachPoint: &types.AttachPointMemberDirectConnectGateway{
					Value: "__AttachPointMemberDirectConnectGateway__",
				},
				EnvironmentId: ptr.String("__EnvironmentId__"),
				Provider: &types.ProviderMemberCloudServiceProvider{
					Value: "__ProviderMemberCloudServiceProvider__",
				},
				Location:    ptr.String("__Location__"),
				Type:        ptr.String("__Type__"),
				State:       types.ConnectionState("available"),
				SharedId:    ptr.String("__SharedId__"),
				BillingTier: ptr.Int32(1),
			},
			{
				Id:          ptr.String("__Id__"),
				Arn:         ptr.String("__Arn__"),
				Description: ptr.String("__Description__"),
				Bandwidth:   ptr.String("__Bandwidth__"),
				AttachPoint: &types.AttachPointMemberDirectConnectGateway{
					Value: "__AttachPointMemberDirectConnectGateway__",
				},
				EnvironmentId: ptr.String("__EnvironmentId__"),
				Provider: &types.ProviderMemberCloudServiceProvider{
					Value: "__ProviderMemberCloudServiceProvider__",
				},
				Location:    ptr.String("__Location__"),
				Type:        ptr.String("__Type__"),
				State:       types.ConnectionState("available"),
				SharedId:    ptr.String("__SharedId__"),
				BillingTier: ptr.Int32(1),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListConnections")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListConnections(context.Background(), &ListConnectionsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListConnections", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListEnvironments(t *testing.T) {
	want := &ListEnvironmentsOutput{
		Environments: []types.Environment{
			{
				Provider: &types.ProviderMemberCloudServiceProvider{
					Value: "__ProviderMemberCloudServiceProvider__",
				},
				Location:      ptr.String("__Location__"),
				EnvironmentId: ptr.String("__EnvironmentId__"),
				State:         types.EnvironmentState("available"),
				Bandwidths: &types.Bandwidths{
					Available: []string{
						"__Member__",
						"__Member__",
					},
					Supported: []string{
						"__Member__",
						"__Member__",
					},
				},
				Type:                 ptr.String("__Type__"),
				ActivationPageUrl:    ptr.String("__ActivationPageUrl__"),
				RemoteIdentifierType: types.RemoteAccountIdentifierType("account"),
			},
			{
				Provider: &types.ProviderMemberCloudServiceProvider{
					Value: "__ProviderMemberCloudServiceProvider__",
				},
				Location:      ptr.String("__Location__"),
				EnvironmentId: ptr.String("__EnvironmentId__"),
				State:         types.EnvironmentState("available"),
				Bandwidths: &types.Bandwidths{
					Available: []string{
						"__Member__",
						"__Member__",
					},
					Supported: []string{
						"__Member__",
						"__Member__",
					},
				},
				Type:                 ptr.String("__Type__"),
				ActivationPageUrl:    ptr.String("__ActivationPageUrl__"),
				RemoteIdentifierType: types.RemoteAccountIdentifierType("account"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListEnvironments")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListEnvironments(context.Background(), &ListEnvironmentsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListEnvironments", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListTagsForResource(t *testing.T) {
	want := &ListTagsForResourceOutput{
		Tags: map[string]string{
			"key0": "__Value__",
		},
	}
	status, header, body, err := serdeRespReadSnapshot("ListTagsForResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListTagsForResource(context.Background(), &ListTagsForResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListTagsForResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_TagResource(t *testing.T) {
	want := &TagResourceOutput{}
	status, header, body, err := serdeRespReadSnapshot("TagResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.TagResource(context.Background(), &TagResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "TagResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_UntagResource(t *testing.T) {
	want := &UntagResourceOutput{}
	status, header, body, err := serdeRespReadSnapshot("UntagResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UntagResource(context.Background(), &UntagResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UntagResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateConnection(t *testing.T) {
	want := &UpdateConnectionOutput{
		Connection: &types.Connection{
			Id:          ptr.String("__Id__"),
			Arn:         ptr.String("__Arn__"),
			Description: ptr.String("__Description__"),
			Bandwidth:   ptr.String("__Bandwidth__"),
			AttachPoint: &types.AttachPointMemberDirectConnectGateway{
				Value: "__AttachPointMemberDirectConnectGateway__",
			},
			EnvironmentId: ptr.String("__EnvironmentId__"),
			Provider: &types.ProviderMemberCloudServiceProvider{
				Value: "__ProviderMemberCloudServiceProvider__",
			},
			Location:      ptr.String("__Location__"),
			Type:          ptr.String("__Type__"),
			State:         types.ConnectionState("available"),
			SharedId:      ptr.String("__SharedId__"),
			BillingTier:   ptr.Int32(1),
			OwnerAccount:  ptr.String("__OwnerAccount__"),
			ActivationKey: ptr.String("__ActivationKey__"),
			Tags: map[string]string{
				"key0": "__Value__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("UpdateConnection")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateConnection(context.Background(), &UpdateConnectionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateConnection", err)
	}
}
