// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_snapshot

package ioteventsdata

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/ioteventsdata/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/url"
	"os"
	"slices"
	"strings"
	"testing"
)

const serdeSSPrefix = "serde_snapshot"

type serdeSnapshotOK struct{}

func (serdeSnapshotOK) Error() string { return "error: success" }

func serdeCreatePath(path string) (*os.File, error) {
	if err := os.MkdirAll(serdeSSPrefix, 0700); err != nil && !errors.Is(err, fs.ErrExist) {
		return nil, err
	}
	return os.Create(path)
}

func serdeSSPath(op string) string {
	return fmt.Sprintf("%s/%s.request.snap", serdeSSPrefix, op)
}

type captureSerdeRequestMiddleware struct {
	body     *bytes.Buffer
	method   *string
	rawPath  *string
	rawQuery *string
	header   *map[string][]string
}

func (*captureSerdeRequestMiddleware) ID() string { return "captureSerdeRequest" }

func (m *captureSerdeRequestMiddleware) HandleFinalize(
	ctx context.Context, input middleware.FinalizeInput, next middleware.FinalizeHandler,
) (
	middleware.FinalizeOutput, middleware.Metadata, error,
) {
	req, ok := input.Request.(*smithyhttp.Request)
	if !ok {
		return middleware.FinalizeOutput{}, middleware.Metadata{}, fmt.Errorf("unexpected transport type %T", input.Request)
	}

	built := req.Build(ctx)
	*m.method = built.Method
	*m.rawPath = built.URL.RawPath
	if *m.rawPath == "" {
		*m.rawPath = built.URL.Path
	}
	*m.rawQuery = built.URL.RawQuery
	*m.header = built.Header

	if built.Body != nil {
		if _, err := io.Copy(m.body, built.Body); err != nil {
			return middleware.FinalizeOutput{}, middleware.Metadata{}, err
		}
	}

	return middleware.FinalizeOutput{}, middleware.Metadata{}, serdeSnapshotOK{}
}

func serdeFormatRequest(method, rawPath, rawQuery string, header map[string][]string, body []byte) string {
	skipHeaders := map[string]bool{
		"Authorization":         true,
		"User-Agent":            true,
		"X-Amz-Date":            true,
		"X-Amz-Security-Token":  true,
		"Amz-Sdk-Invocation-Id": true,
		"Amz-Sdk-Request":       true,
	}

	var sb strings.Builder
	sb.WriteString(method)
	sb.WriteString(" ")
	sb.WriteString(rawPath)
	if rawQuery != "" {
		sb.WriteString("?")
		sb.WriteString(rawQuery)
	}
	sb.WriteString("\n\n")

	keys := make([]string, 0, len(header))
	for k := range header {
		if skipHeaders[k] {
			continue
		}
		keys = append(keys, k)
	}
	slices.Sort(keys)
	for _, k := range keys {
		for _, v := range header[k] {
			sb.WriteString(k)
			sb.WriteString(": ")
			sb.WriteString(v)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\n")
	if len(body) > 0 {
		var v interface{}
		if err := json.Unmarshal(body, &v); err == nil {
			if sorted, err := json.Marshal(v); err == nil {
				sb.Write(sorted)
			}
		}
	}
	return sb.String()
}

func serdeUpdateSnapshot(method, rawPath, rawQuery string, header map[string][]string, body []byte, operation string) error {
	content := serdeFormatRequest(method, rawPath, rawQuery, header, body)
	f, err := serdeCreatePath(serdeSSPath(operation))
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := f.Write([]byte(content)); err != nil {
		return err
	}
	return serdeSnapshotOK{}
}

func serdeTestSnapshot(method, rawPath, rawQuery string, header map[string][]string, body []byte, operation string) error {
	content := serdeFormatRequest(method, rawPath, rawQuery, header, body)
	f, err := os.Open(serdeSSPath(operation))
	if errors.Is(err, fs.ErrNotExist) {
		return serdeSnapshotOK{}
	}
	if err != nil {
		return err
	}
	defer f.Close()
	expected, err := io.ReadAll(f)
	if err != nil {
		return err
	}
	if content != string(expected) {
		return fmt.Errorf("serde snapshot mismatch for %s:\nGOT:\n%s:\nEXPECTED:\n%s", operation, content, string(expected))
	}
	return serdeSnapshotOK{}
}

type serdeEndpointResolver struct{}

func (*serdeEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeNewClient() *Client {
	return New(Options{
		Region:             "us-east-1",
		EndpointResolverV2: &serdeEndpointResolver{},
	})
}
func TestSerdeCheckSnapshot_BatchAcknowledgeAlarm(t *testing.T) {
	input := &BatchAcknowledgeAlarmInput{
		AcknowledgeActionRequests: []types.AcknowledgeAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchAcknowledgeAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchAcknowledgeAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchDeleteDetector(t *testing.T) {
	input := &BatchDeleteDetectorInput{
		Detectors: []types.DeleteDetectorRequest{
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
			},
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchDeleteDetector(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchDeleteDetector"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchDisableAlarm(t *testing.T) {
	input := &BatchDisableAlarmInput{
		DisableActionRequests: []types.DisableAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchDisableAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchDisableAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchEnableAlarm(t *testing.T) {
	input := &BatchEnableAlarmInput{
		EnableActionRequests: []types.EnableAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchEnableAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchEnableAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchPutMessage(t *testing.T) {
	input := &BatchPutMessageInput{
		Messages: []types.Message{
			{
				MessageId: ptr.String("__MessageId__"),
				InputName: ptr.String("__InputName__"),
				Payload:   []byte("blob"),
				Timestamp: &types.TimestampValue{
					TimeInMillis: ptr.Int64(1),
				},
			},
			{
				MessageId: ptr.String("__MessageId__"),
				InputName: ptr.String("__InputName__"),
				Payload:   []byte("blob"),
				Timestamp: &types.TimestampValue{
					TimeInMillis: ptr.Int64(1),
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchPutMessage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchPutMessage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchResetAlarm(t *testing.T) {
	input := &BatchResetAlarmInput{
		ResetActionRequests: []types.ResetAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchResetAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchResetAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchSnoozeAlarm(t *testing.T) {
	input := &BatchSnoozeAlarmInput{
		SnoozeActionRequests: []types.SnoozeAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
				SnoozeDuration: ptr.Int32(1),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
				SnoozeDuration: ptr.Int32(1),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchSnoozeAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchSnoozeAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_BatchUpdateDetector(t *testing.T) {
	input := &BatchUpdateDetectorInput{
		Detectors: []types.UpdateDetectorRequest{
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
				State: &types.DetectorStateDefinition{
					StateName: ptr.String("__StateName__"),
					Variables: []types.VariableDefinition{
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
					},
					Timers: []types.TimerDefinition{
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
					},
				},
			},
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
				State: &types.DetectorStateDefinition{
					StateName: ptr.String("__StateName__"),
					Variables: []types.VariableDefinition{
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
					},
					Timers: []types.TimerDefinition{
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
					},
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchUpdateDetector(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchUpdateDetector"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeAlarm(t *testing.T) {
	input := &DescribeAlarmInput{
		AlarmModelName: ptr.String("__AlarmModelName__"),
		KeyValue:       ptr.String("__KeyValue__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeDetector(t *testing.T) {
	input := &DescribeDetectorInput{
		DetectorModelName: ptr.String("__DetectorModelName__"),
		KeyValue:          ptr.String("__KeyValue__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeDetector(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeDetector"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListAlarms(t *testing.T) {
	input := &ListAlarmsInput{
		AlarmModelName: ptr.String("__AlarmModelName__"),
		NextToken:      ptr.String("__NextToken__"),
		MaxResults:     ptr.Int32(1),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListAlarms(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListAlarms"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListDetectors(t *testing.T) {
	input := &ListDetectorsInput{
		DetectorModelName: ptr.String("__DetectorModelName__"),
		StateName:         ptr.String("__StateName__"),
		NextToken:         ptr.String("__NextToken__"),
		MaxResults:        ptr.Int32(1),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListDetectors(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListDetectors"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}
func TestSerdeUpdateSnapshot_BatchAcknowledgeAlarm(t *testing.T) {
	input := &BatchAcknowledgeAlarmInput{
		AcknowledgeActionRequests: []types.AcknowledgeAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchAcknowledgeAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchAcknowledgeAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchDeleteDetector(t *testing.T) {
	input := &BatchDeleteDetectorInput{
		Detectors: []types.DeleteDetectorRequest{
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
			},
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchDeleteDetector(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchDeleteDetector"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchDisableAlarm(t *testing.T) {
	input := &BatchDisableAlarmInput{
		DisableActionRequests: []types.DisableAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchDisableAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchDisableAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchEnableAlarm(t *testing.T) {
	input := &BatchEnableAlarmInput{
		EnableActionRequests: []types.EnableAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchEnableAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchEnableAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchPutMessage(t *testing.T) {
	input := &BatchPutMessageInput{
		Messages: []types.Message{
			{
				MessageId: ptr.String("__MessageId__"),
				InputName: ptr.String("__InputName__"),
				Payload:   []byte("blob"),
				Timestamp: &types.TimestampValue{
					TimeInMillis: ptr.Int64(1),
				},
			},
			{
				MessageId: ptr.String("__MessageId__"),
				InputName: ptr.String("__InputName__"),
				Payload:   []byte("blob"),
				Timestamp: &types.TimestampValue{
					TimeInMillis: ptr.Int64(1),
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchPutMessage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchPutMessage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchResetAlarm(t *testing.T) {
	input := &BatchResetAlarmInput{
		ResetActionRequests: []types.ResetAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchResetAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchResetAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchSnoozeAlarm(t *testing.T) {
	input := &BatchSnoozeAlarmInput{
		SnoozeActionRequests: []types.SnoozeAlarmActionRequest{
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
				SnoozeDuration: ptr.Int32(1),
			},
			{
				RequestId:      ptr.String("__RequestId__"),
				AlarmModelName: ptr.String("__AlarmModelName__"),
				KeyValue:       ptr.String("__KeyValue__"),
				Note:           ptr.String("__Note__"),
				SnoozeDuration: ptr.Int32(1),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchSnoozeAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchSnoozeAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_BatchUpdateDetector(t *testing.T) {
	input := &BatchUpdateDetectorInput{
		Detectors: []types.UpdateDetectorRequest{
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
				State: &types.DetectorStateDefinition{
					StateName: ptr.String("__StateName__"),
					Variables: []types.VariableDefinition{
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
					},
					Timers: []types.TimerDefinition{
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
					},
				},
			},
			{
				MessageId:         ptr.String("__MessageId__"),
				DetectorModelName: ptr.String("__DetectorModelName__"),
				KeyValue:          ptr.String("__KeyValue__"),
				State: &types.DetectorStateDefinition{
					StateName: ptr.String("__StateName__"),
					Variables: []types.VariableDefinition{
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
					},
					Timers: []types.TimerDefinition{
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
						{
							Name:    ptr.String("__Name__"),
							Seconds: ptr.Int32(1),
						},
					},
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.BatchUpdateDetector(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "BatchUpdateDetector"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeAlarm(t *testing.T) {
	input := &DescribeAlarmInput{
		AlarmModelName: ptr.String("__AlarmModelName__"),
		KeyValue:       ptr.String("__KeyValue__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeAlarm(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeAlarm"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeDetector(t *testing.T) {
	input := &DescribeDetectorInput{
		DetectorModelName: ptr.String("__DetectorModelName__"),
		KeyValue:          ptr.String("__KeyValue__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeDetector(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeDetector"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListAlarms(t *testing.T) {
	input := &ListAlarmsInput{
		AlarmModelName: ptr.String("__AlarmModelName__"),
		NextToken:      ptr.String("__NextToken__"),
		MaxResults:     ptr.Int32(1),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListAlarms(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListAlarms"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListDetectors(t *testing.T) {
	input := &ListDetectorsInput{
		DetectorModelName: ptr.String("__DetectorModelName__"),
		StateName:         ptr.String("__StateName__"),
		NextToken:         ptr.String("__NextToken__"),
		MaxResults:        ptr.Int32(1),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListDetectors(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListDetectors"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}
