// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package cloudwatch

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/cloudwatch/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithytesting "github.com/aws/smithy-go/testing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

const serdeRespSSPrefix = "serde_response_snapshot"

func serdeRespSSPath(op string) string {
	return fmt.Sprintf("%s/%s.response.snap", serdeRespSSPrefix, op)
}

// serdeRespReadSnapshot parses a frozen wire response fixture: a status-code
// line, HTTP headers, a blank line, then the raw body.
func serdeRespReadSnapshot(op string) (int, http.Header, []byte, error) {
	raw, err := os.ReadFile(serdeRespSSPath(op))
	if err != nil {
		return 0, nil, nil, err
	}

	r := bufio.NewReader(bytes.NewReader(raw))
	statusLine, err := r.ReadString('\n')
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read status line: %w", err)
	}
	status, err := strconv.Atoi(strings.TrimSpace(statusLine))
	if err != nil {
		return 0, nil, nil, fmt.Errorf("parse status: %w", err)
	}

	header := http.Header{}
	for {
		line, err := r.ReadString('\n')
		if err != nil && err != io.EOF {
			return 0, nil, nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		k, v, ok := strings.Cut(trimmed, ": ")
		if !ok {
			return 0, nil, nil, fmt.Errorf("malformed header %q", trimmed)
		}
		header.Add(k, v)
		if err == io.EOF {
			break
		}
	}

	body, err := io.ReadAll(r)
	if err != nil {
		return 0, nil, nil, err
	}
	return status, header, body, nil
}

type serdeRespEndpointResolver struct{}

func (*serdeRespEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeRespClient(status int, header http.Header, body []byte) *Client {
	return New(Options{
		Region: "us-east-1",
		HTTPClient: smithyhttp.ClientDoFunc(func(req *http.Request) (*http.Response, error) {
			resp := &http.Response{StatusCode: status, Header: header, Request: req}
			if len(body) > 0 {
				resp.ContentLength = int64(len(body))
				resp.Body = io.NopCloser(bytes.NewReader(body))
			} else {
				resp.Body = http.NoBody
			}
			return resp, nil
		}),
		EndpointResolverV2: &serdeRespEndpointResolver{},
		APIOptions: []func(*middleware.Stack) error{
			func(s *middleware.Stack) error {
				s.Finalize.Clear()
				s.Initialize.Remove("OperationInputValidation")
				return nil
			},
		},
	})
}
func TestSerdeCheckResponseSnapshot_AssociateDatasetKmsKey(t *testing.T) {
	want := &AssociateDatasetKmsKeyOutput{}
	status, header, body, err := serdeRespReadSnapshot("AssociateDatasetKmsKey")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.AssociateDatasetKmsKey(context.Background(), &AssociateDatasetKmsKeyInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "AssociateDatasetKmsKey", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteAlarmMuteRule(t *testing.T) {
	want := &DeleteAlarmMuteRuleOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteAlarmMuteRule")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteAlarmMuteRule(context.Background(), &DeleteAlarmMuteRuleInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteAlarmMuteRule", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteAlarms(t *testing.T) {
	want := &DeleteAlarmsOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteAlarms")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteAlarms(context.Background(), &DeleteAlarmsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteAlarms", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteAnomalyDetector(t *testing.T) {
	want := &DeleteAnomalyDetectorOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteAnomalyDetector")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteAnomalyDetector(context.Background(), &DeleteAnomalyDetectorInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteAnomalyDetector", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteDashboards(t *testing.T) {
	want := &DeleteDashboardsOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteDashboards")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteDashboards(context.Background(), &DeleteDashboardsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteDashboards", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteInsightRules(t *testing.T) {
	want := &DeleteInsightRulesOutput{
		Failures: []types.PartialFailure{
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DeleteInsightRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteInsightRules(context.Background(), &DeleteInsightRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteInsightRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteMetricStream(t *testing.T) {
	want := &DeleteMetricStreamOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteMetricStream")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteMetricStream(context.Background(), &DeleteMetricStreamInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteMetricStream", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAlarmContributors(t *testing.T) {
	want := &DescribeAlarmContributorsOutput{
		AlarmContributors: []types.AlarmContributor{
			{
				ContributorId: ptr.String("__ContributorId__"),
				ContributorAttributes: map[string]string{
					"key0": "__Value__",
				},
				StateReason:                ptr.String("__StateReason__"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				ContributorId: ptr.String("__ContributorId__"),
				ContributorAttributes: map[string]string{
					"key0": "__Value__",
				},
				StateReason:                ptr.String("__StateReason__"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAlarmContributors")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAlarmContributors(context.Background(), &DescribeAlarmContributorsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAlarmContributors", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAlarmHistory(t *testing.T) {
	want := &DescribeAlarmHistoryOutput{
		AlarmHistoryItems: []types.AlarmHistoryItem{
			{
				AlarmName:          ptr.String("__AlarmName__"),
				AlarmContributorId: ptr.String("__AlarmContributorId__"),
				AlarmType:          types.AlarmType("CompositeAlarm"),
				Timestamp:          ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				HistoryItemType:    types.HistoryItemType("ConfigurationUpdate"),
				HistorySummary:     ptr.String("__HistorySummary__"),
				HistoryData:        ptr.String("__HistoryData__"),
				AlarmContributorAttributes: map[string]string{
					"key0": "__Value__",
				},
			},
			{
				AlarmName:          ptr.String("__AlarmName__"),
				AlarmContributorId: ptr.String("__AlarmContributorId__"),
				AlarmType:          types.AlarmType("CompositeAlarm"),
				Timestamp:          ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				HistoryItemType:    types.HistoryItemType("ConfigurationUpdate"),
				HistorySummary:     ptr.String("__HistorySummary__"),
				HistoryData:        ptr.String("__HistoryData__"),
				AlarmContributorAttributes: map[string]string{
					"key0": "__Value__",
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAlarmHistory")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAlarmHistory(context.Background(), &DescribeAlarmHistoryInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAlarmHistory", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAlarms(t *testing.T) {
	want := &DescribeAlarmsOutput{
		CompositeAlarms: []types.CompositeAlarm{
			{
				ActionsEnabled: ptr.Bool(true),
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmRule:                          ptr.String("__AlarmRule__"),
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				StateReason:                      ptr.String("__StateReason__"),
				StateReasonData:                  ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp:            ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				StateValue:                       types.StateValue("OK"),
				StateTransitionedTimestamp:       ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsSuppressedBy:              types.ActionsSuppressedBy("WaitPeriod"),
				ActionsSuppressedReason:          ptr.String("__ActionsSuppressedReason__"),
				ActionsSuppressor:                ptr.String("__ActionsSuppressor__"),
				ActionsSuppressorWaitPeriod:      ptr.Int32(1),
				ActionsSuppressorExtensionPeriod: ptr.Int32(1),
			},
			{
				ActionsEnabled: ptr.Bool(true),
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmRule:                          ptr.String("__AlarmRule__"),
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				StateReason:                      ptr.String("__StateReason__"),
				StateReasonData:                  ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp:            ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				StateValue:                       types.StateValue("OK"),
				StateTransitionedTimestamp:       ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsSuppressedBy:              types.ActionsSuppressedBy("WaitPeriod"),
				ActionsSuppressedReason:          ptr.String("__ActionsSuppressedReason__"),
				ActionsSuppressor:                ptr.String("__ActionsSuppressor__"),
				ActionsSuppressorWaitPeriod:      ptr.Int32(1),
				ActionsSuppressorExtensionPeriod: ptr.Int32(1),
			},
		},
		MetricAlarms: []types.MetricAlarm{
			{
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsEnabled:                     ptr.Bool(true),
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				StateValue:            types.StateValue("OK"),
				StateReason:           ptr.String("__StateReason__"),
				StateReasonData:       ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				MetricName:            ptr.String("__MetricName__"),
				Namespace:             ptr.String("__Namespace__"),
				Statistic:             types.Statistic("SampleCount"),
				ExtendedStatistic:     ptr.String("__ExtendedStatistic__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
				Period:                           ptr.Int32(1),
				Unit:                             types.StandardUnit("Seconds"),
				EvaluationPeriods:                ptr.Int32(1),
				DatapointsToAlarm:                ptr.Int32(1),
				Threshold:                        ptr.Float64(1.0),
				ComparisonOperator:               types.ComparisonOperator("GreaterThanOrEqualToThreshold"),
				TreatMissingData:                 ptr.String("__TreatMissingData__"),
				EvaluateLowSampleCountPercentile: ptr.String("__EvaluateLowSampleCountPercentile__"),
				Metrics: []types.MetricDataQuery{
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
				},
				ThresholdMetricId:          ptr.String("__ThresholdMetricId__"),
				EvaluationState:            types.EvaluationState("PARTIAL_DATA"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EvaluationWindow: &types.EvaluationWindowMemberWallClockWindow{
					Value: types.WallClockWindow{
						Timezone: ptr.String("__Timezone__"),
					},
				},
				EvaluationCriteria: &types.EvaluationCriteriaMemberPromQLCriteria{
					Value: types.AlarmPromQLCriteria{
						Query:          ptr.String("__Query__"),
						PendingPeriod:  ptr.Int32(1),
						RecoveryPeriod: ptr.Int32(1),
					},
				},
				EvaluationInterval: ptr.Int32(1),
			},
			{
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsEnabled:                     ptr.Bool(true),
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				StateValue:            types.StateValue("OK"),
				StateReason:           ptr.String("__StateReason__"),
				StateReasonData:       ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				MetricName:            ptr.String("__MetricName__"),
				Namespace:             ptr.String("__Namespace__"),
				Statistic:             types.Statistic("SampleCount"),
				ExtendedStatistic:     ptr.String("__ExtendedStatistic__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
				Period:                           ptr.Int32(1),
				Unit:                             types.StandardUnit("Seconds"),
				EvaluationPeriods:                ptr.Int32(1),
				DatapointsToAlarm:                ptr.Int32(1),
				Threshold:                        ptr.Float64(1.0),
				ComparisonOperator:               types.ComparisonOperator("GreaterThanOrEqualToThreshold"),
				TreatMissingData:                 ptr.String("__TreatMissingData__"),
				EvaluateLowSampleCountPercentile: ptr.String("__EvaluateLowSampleCountPercentile__"),
				Metrics: []types.MetricDataQuery{
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
				},
				ThresholdMetricId:          ptr.String("__ThresholdMetricId__"),
				EvaluationState:            types.EvaluationState("PARTIAL_DATA"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EvaluationWindow: &types.EvaluationWindowMemberWallClockWindow{
					Value: types.WallClockWindow{
						Timezone: ptr.String("__Timezone__"),
					},
				},
				EvaluationCriteria: &types.EvaluationCriteriaMemberPromQLCriteria{
					Value: types.AlarmPromQLCriteria{
						Query:          ptr.String("__Query__"),
						PendingPeriod:  ptr.Int32(1),
						RecoveryPeriod: ptr.Int32(1),
					},
				},
				EvaluationInterval: ptr.Int32(1),
			},
		},
		LogAlarms: []types.LogAlarm{
			{
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsEnabled:                     ptr.Bool(true),
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				StateValue:            types.StateValue("OK"),
				StateReason:           ptr.String("__StateReason__"),
				StateReasonData:       ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ScheduledQueryConfiguration: &types.ScheduledQueryConfiguration{
					QueryString: ptr.String("__QueryString__"),
					LogGroupIdentifiers: []string{
						"__Member__",
						"__Member__",
					},
					QueryARN:              ptr.String("__QueryARN__"),
					ScheduledQueryRoleARN: ptr.String("__ScheduledQueryRoleARN__"),
					ScheduleConfiguration: &types.ScheduleConfiguration{
						ScheduleExpression: ptr.String("__ScheduleExpression__"),
						StartTimeOffset:    ptr.Int64(1),
						EndTimeOffset:      ptr.Int64(1),
					},
					AggregationExpression: ptr.String("__AggregationExpression__"),
					Tags: []types.Tag{
						{
							Key:   ptr.String("__Key__"),
							Value: ptr.String("__Value__"),
						},
						{
							Key:   ptr.String("__Key__"),
							Value: ptr.String("__Value__"),
						},
					},
				},
				QueryResultsToEvaluate:     ptr.Int32(1),
				QueryResultsToAlarm:        ptr.Int32(1),
				Threshold:                  ptr.Float64(1.0),
				ComparisonOperator:         types.ComparisonOperator("GreaterThanOrEqualToThreshold"),
				TreatMissingData:           ptr.String("__TreatMissingData__"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EvaluationState:            types.EvaluationState("PARTIAL_DATA"),
				ActionLogLineCount:         ptr.Int32(1),
				ActionLogLineRoleArn:       ptr.String("__ActionLogLineRoleArn__"),
			},
			{
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsEnabled:                     ptr.Bool(true),
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				StateValue:            types.StateValue("OK"),
				StateReason:           ptr.String("__StateReason__"),
				StateReasonData:       ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ScheduledQueryConfiguration: &types.ScheduledQueryConfiguration{
					QueryString: ptr.String("__QueryString__"),
					LogGroupIdentifiers: []string{
						"__Member__",
						"__Member__",
					},
					QueryARN:              ptr.String("__QueryARN__"),
					ScheduledQueryRoleARN: ptr.String("__ScheduledQueryRoleARN__"),
					ScheduleConfiguration: &types.ScheduleConfiguration{
						ScheduleExpression: ptr.String("__ScheduleExpression__"),
						StartTimeOffset:    ptr.Int64(1),
						EndTimeOffset:      ptr.Int64(1),
					},
					AggregationExpression: ptr.String("__AggregationExpression__"),
					Tags: []types.Tag{
						{
							Key:   ptr.String("__Key__"),
							Value: ptr.String("__Value__"),
						},
						{
							Key:   ptr.String("__Key__"),
							Value: ptr.String("__Value__"),
						},
					},
				},
				QueryResultsToEvaluate:     ptr.Int32(1),
				QueryResultsToAlarm:        ptr.Int32(1),
				Threshold:                  ptr.Float64(1.0),
				ComparisonOperator:         types.ComparisonOperator("GreaterThanOrEqualToThreshold"),
				TreatMissingData:           ptr.String("__TreatMissingData__"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EvaluationState:            types.EvaluationState("PARTIAL_DATA"),
				ActionLogLineCount:         ptr.Int32(1),
				ActionLogLineRoleArn:       ptr.String("__ActionLogLineRoleArn__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAlarms")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAlarms(context.Background(), &DescribeAlarmsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAlarms", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAlarmsForMetric(t *testing.T) {
	want := &DescribeAlarmsForMetricOutput{
		MetricAlarms: []types.MetricAlarm{
			{
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsEnabled:                     ptr.Bool(true),
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				StateValue:            types.StateValue("OK"),
				StateReason:           ptr.String("__StateReason__"),
				StateReasonData:       ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				MetricName:            ptr.String("__MetricName__"),
				Namespace:             ptr.String("__Namespace__"),
				Statistic:             types.Statistic("SampleCount"),
				ExtendedStatistic:     ptr.String("__ExtendedStatistic__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
				Period:                           ptr.Int32(1),
				Unit:                             types.StandardUnit("Seconds"),
				EvaluationPeriods:                ptr.Int32(1),
				DatapointsToAlarm:                ptr.Int32(1),
				Threshold:                        ptr.Float64(1.0),
				ComparisonOperator:               types.ComparisonOperator("GreaterThanOrEqualToThreshold"),
				TreatMissingData:                 ptr.String("__TreatMissingData__"),
				EvaluateLowSampleCountPercentile: ptr.String("__EvaluateLowSampleCountPercentile__"),
				Metrics: []types.MetricDataQuery{
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
				},
				ThresholdMetricId:          ptr.String("__ThresholdMetricId__"),
				EvaluationState:            types.EvaluationState("PARTIAL_DATA"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EvaluationWindow: &types.EvaluationWindowMemberWallClockWindow{
					Value: types.WallClockWindow{
						Timezone: ptr.String("__Timezone__"),
					},
				},
				EvaluationCriteria: &types.EvaluationCriteriaMemberPromQLCriteria{
					Value: types.AlarmPromQLCriteria{
						Query:          ptr.String("__Query__"),
						PendingPeriod:  ptr.Int32(1),
						RecoveryPeriod: ptr.Int32(1),
					},
				},
				EvaluationInterval: ptr.Int32(1),
			},
			{
				AlarmName:                          ptr.String("__AlarmName__"),
				AlarmArn:                           ptr.String("__AlarmArn__"),
				AlarmDescription:                   ptr.String("__AlarmDescription__"),
				AlarmConfigurationUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ActionsEnabled:                     ptr.Bool(true),
				OKActions: []string{
					"__Member__",
					"__Member__",
				},
				AlarmActions: []string{
					"__Member__",
					"__Member__",
				},
				InsufficientDataActions: []string{
					"__Member__",
					"__Member__",
				},
				StateValue:            types.StateValue("OK"),
				StateReason:           ptr.String("__StateReason__"),
				StateReasonData:       ptr.String("__StateReasonData__"),
				StateUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				MetricName:            ptr.String("__MetricName__"),
				Namespace:             ptr.String("__Namespace__"),
				Statistic:             types.Statistic("SampleCount"),
				ExtendedStatistic:     ptr.String("__ExtendedStatistic__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
				Period:                           ptr.Int32(1),
				Unit:                             types.StandardUnit("Seconds"),
				EvaluationPeriods:                ptr.Int32(1),
				DatapointsToAlarm:                ptr.Int32(1),
				Threshold:                        ptr.Float64(1.0),
				ComparisonOperator:               types.ComparisonOperator("GreaterThanOrEqualToThreshold"),
				TreatMissingData:                 ptr.String("__TreatMissingData__"),
				EvaluateLowSampleCountPercentile: ptr.String("__EvaluateLowSampleCountPercentile__"),
				Metrics: []types.MetricDataQuery{
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
					{
						Id: ptr.String("__Id__"),
						MetricStat: &types.MetricStat{
							Metric: &types.Metric{
								Namespace:  ptr.String("__Namespace__"),
								MetricName: ptr.String("__MetricName__"),
								Dimensions: []types.Dimension{
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
									{
										Name:  ptr.String("__Name__"),
										Value: ptr.String("__Value__"),
									},
								},
							},
							Period: ptr.Int32(1),
							Stat:   ptr.String("__Stat__"),
							Unit:   types.StandardUnit("Seconds"),
						},
						Expression: ptr.String("__Expression__"),
						Label:      ptr.String("__Label__"),
						ReturnData: ptr.Bool(true),
						Period:     ptr.Int32(1),
						AccountId:  ptr.String("__AccountId__"),
					},
				},
				ThresholdMetricId:          ptr.String("__ThresholdMetricId__"),
				EvaluationState:            types.EvaluationState("PARTIAL_DATA"),
				StateTransitionedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EvaluationWindow: &types.EvaluationWindowMemberWallClockWindow{
					Value: types.WallClockWindow{
						Timezone: ptr.String("__Timezone__"),
					},
				},
				EvaluationCriteria: &types.EvaluationCriteriaMemberPromQLCriteria{
					Value: types.AlarmPromQLCriteria{
						Query:          ptr.String("__Query__"),
						PendingPeriod:  ptr.Int32(1),
						RecoveryPeriod: ptr.Int32(1),
					},
				},
				EvaluationInterval: ptr.Int32(1),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAlarmsForMetric")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAlarmsForMetric(context.Background(), &DescribeAlarmsForMetricInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAlarmsForMetric", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAnomalyDetectors(t *testing.T) {
	want := &DescribeAnomalyDetectorsOutput{
		AnomalyDetectors: []types.AnomalyDetector{
			{
				Namespace:  ptr.String("__Namespace__"),
				MetricName: ptr.String("__MetricName__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
				Stat: ptr.String("__Stat__"),
				Configuration: &types.AnomalyDetectorConfiguration{
					ExcludedTimeRanges: []types.Range{
						{
							StartTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
							EndTime:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						},
						{
							StartTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
							EndTime:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						},
					},
					MetricTimezone: ptr.String("__MetricTimezone__"),
				},
				StateValue: types.AnomalyDetectorStateValue("PENDING_TRAINING"),
				MetricCharacteristics: &types.MetricCharacteristics{
					PeriodicSpikes: ptr.Bool(true),
				},
				SingleMetricAnomalyDetector: &types.SingleMetricAnomalyDetector{
					AccountId:  ptr.String("__AccountId__"),
					Namespace:  ptr.String("__Namespace__"),
					MetricName: ptr.String("__MetricName__"),
					Dimensions: []types.Dimension{
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
					},
					Stat: ptr.String("__Stat__"),
				},
				MetricMathAnomalyDetector: &types.MetricMathAnomalyDetector{
					MetricDataQueries: []types.MetricDataQuery{
						{
							Id: ptr.String("__Id__"),
							MetricStat: &types.MetricStat{
								Metric: &types.Metric{
									Namespace:  ptr.String("__Namespace__"),
									MetricName: ptr.String("__MetricName__"),
									Dimensions: []types.Dimension{
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
									},
								},
								Period: ptr.Int32(1),
								Stat:   ptr.String("__Stat__"),
								Unit:   types.StandardUnit("Seconds"),
							},
							Expression: ptr.String("__Expression__"),
							Label:      ptr.String("__Label__"),
							ReturnData: ptr.Bool(true),
							Period:     ptr.Int32(1),
							AccountId:  ptr.String("__AccountId__"),
						},
						{
							Id: ptr.String("__Id__"),
							MetricStat: &types.MetricStat{
								Metric: &types.Metric{
									Namespace:  ptr.String("__Namespace__"),
									MetricName: ptr.String("__MetricName__"),
									Dimensions: []types.Dimension{
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
									},
								},
								Period: ptr.Int32(1),
								Stat:   ptr.String("__Stat__"),
								Unit:   types.StandardUnit("Seconds"),
							},
							Expression: ptr.String("__Expression__"),
							Label:      ptr.String("__Label__"),
							ReturnData: ptr.Bool(true),
							Period:     ptr.Int32(1),
							AccountId:  ptr.String("__AccountId__"),
						},
					},
				},
			},
			{
				Namespace:  ptr.String("__Namespace__"),
				MetricName: ptr.String("__MetricName__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
				Stat: ptr.String("__Stat__"),
				Configuration: &types.AnomalyDetectorConfiguration{
					ExcludedTimeRanges: []types.Range{
						{
							StartTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
							EndTime:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						},
						{
							StartTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
							EndTime:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						},
					},
					MetricTimezone: ptr.String("__MetricTimezone__"),
				},
				StateValue: types.AnomalyDetectorStateValue("PENDING_TRAINING"),
				MetricCharacteristics: &types.MetricCharacteristics{
					PeriodicSpikes: ptr.Bool(true),
				},
				SingleMetricAnomalyDetector: &types.SingleMetricAnomalyDetector{
					AccountId:  ptr.String("__AccountId__"),
					Namespace:  ptr.String("__Namespace__"),
					MetricName: ptr.String("__MetricName__"),
					Dimensions: []types.Dimension{
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
						{
							Name:  ptr.String("__Name__"),
							Value: ptr.String("__Value__"),
						},
					},
					Stat: ptr.String("__Stat__"),
				},
				MetricMathAnomalyDetector: &types.MetricMathAnomalyDetector{
					MetricDataQueries: []types.MetricDataQuery{
						{
							Id: ptr.String("__Id__"),
							MetricStat: &types.MetricStat{
								Metric: &types.Metric{
									Namespace:  ptr.String("__Namespace__"),
									MetricName: ptr.String("__MetricName__"),
									Dimensions: []types.Dimension{
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
									},
								},
								Period: ptr.Int32(1),
								Stat:   ptr.String("__Stat__"),
								Unit:   types.StandardUnit("Seconds"),
							},
							Expression: ptr.String("__Expression__"),
							Label:      ptr.String("__Label__"),
							ReturnData: ptr.Bool(true),
							Period:     ptr.Int32(1),
							AccountId:  ptr.String("__AccountId__"),
						},
						{
							Id: ptr.String("__Id__"),
							MetricStat: &types.MetricStat{
								Metric: &types.Metric{
									Namespace:  ptr.String("__Namespace__"),
									MetricName: ptr.String("__MetricName__"),
									Dimensions: []types.Dimension{
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
										{
											Name:  ptr.String("__Name__"),
											Value: ptr.String("__Value__"),
										},
									},
								},
								Period: ptr.Int32(1),
								Stat:   ptr.String("__Stat__"),
								Unit:   types.StandardUnit("Seconds"),
							},
							Expression: ptr.String("__Expression__"),
							Label:      ptr.String("__Label__"),
							ReturnData: ptr.Bool(true),
							Period:     ptr.Int32(1),
							AccountId:  ptr.String("__AccountId__"),
						},
					},
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAnomalyDetectors")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAnomalyDetectors(context.Background(), &DescribeAnomalyDetectorsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAnomalyDetectors", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeInsightRules(t *testing.T) {
	want := &DescribeInsightRulesOutput{
		NextToken: ptr.String("__NextToken__"),
		InsightRules: []types.InsightRule{
			{
				Name:                   ptr.String("__Name__"),
				State:                  ptr.String("__State__"),
				Schema:                 ptr.String("__Schema__"),
				Definition:             ptr.String("__Definition__"),
				ManagedRule:            ptr.Bool(true),
				ApplyOnTransformedLogs: ptr.Bool(true),
			},
			{
				Name:                   ptr.String("__Name__"),
				State:                  ptr.String("__State__"),
				Schema:                 ptr.String("__Schema__"),
				Definition:             ptr.String("__Definition__"),
				ManagedRule:            ptr.Bool(true),
				ApplyOnTransformedLogs: ptr.Bool(true),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeInsightRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeInsightRules(context.Background(), &DescribeInsightRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeInsightRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_DisableAlarmActions(t *testing.T) {
	want := &DisableAlarmActionsOutput{}
	status, header, body, err := serdeRespReadSnapshot("DisableAlarmActions")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DisableAlarmActions(context.Background(), &DisableAlarmActionsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DisableAlarmActions", err)
	}
}

func TestSerdeCheckResponseSnapshot_DisableInsightRules(t *testing.T) {
	want := &DisableInsightRulesOutput{
		Failures: []types.PartialFailure{
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DisableInsightRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DisableInsightRules(context.Background(), &DisableInsightRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DisableInsightRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_DisassociateDatasetKmsKey(t *testing.T) {
	want := &DisassociateDatasetKmsKeyOutput{}
	status, header, body, err := serdeRespReadSnapshot("DisassociateDatasetKmsKey")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DisassociateDatasetKmsKey(context.Background(), &DisassociateDatasetKmsKeyInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DisassociateDatasetKmsKey", err)
	}
}

func TestSerdeCheckResponseSnapshot_EnableAlarmActions(t *testing.T) {
	want := &EnableAlarmActionsOutput{}
	status, header, body, err := serdeRespReadSnapshot("EnableAlarmActions")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.EnableAlarmActions(context.Background(), &EnableAlarmActionsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "EnableAlarmActions", err)
	}
}

func TestSerdeCheckResponseSnapshot_EnableInsightRules(t *testing.T) {
	want := &EnableInsightRulesOutput{
		Failures: []types.PartialFailure{
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("EnableInsightRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.EnableInsightRules(context.Background(), &EnableInsightRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "EnableInsightRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetAlarmMuteRule(t *testing.T) {
	want := &GetAlarmMuteRuleOutput{
		Name:             ptr.String("__Name__"),
		AlarmMuteRuleArn: ptr.String("__AlarmMuteRuleArn__"),
		Description:      ptr.String("__Description__"),
		Rule: &types.Rule{
			Schedule: &types.Schedule{
				Expression: ptr.String("__Expression__"),
				Duration:   ptr.String("__Duration__"),
				Timezone:   ptr.String("__Timezone__"),
			},
		},
		MuteTargets: &types.MuteTargets{
			AlarmNames: []string{
				"__Member__",
				"__Member__",
			},
		},
		StartDate:            ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		ExpireDate:           ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		Status:               types.AlarmMuteRuleStatus("SCHEDULED"),
		LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		MuteType:             ptr.String("__MuteType__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetAlarmMuteRule")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetAlarmMuteRule(context.Background(), &GetAlarmMuteRuleInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetAlarmMuteRule", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetDashboard(t *testing.T) {
	want := &GetDashboardOutput{
		DashboardArn:  ptr.String("__DashboardArn__"),
		DashboardBody: ptr.String("__DashboardBody__"),
		DashboardName: ptr.String("__DashboardName__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetDashboard")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetDashboard(context.Background(), &GetDashboardInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetDashboard", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetDataset(t *testing.T) {
	want := &GetDatasetOutput{
		DatasetId: ptr.String("__DatasetId__"),
		Arn:       ptr.String("__Arn__"),
		KmsKeyArn: ptr.String("__KmsKeyArn__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetDataset")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetDataset(context.Background(), &GetDatasetInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetDataset", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetInsightRuleReport(t *testing.T) {
	want := &GetInsightRuleReportOutput{
		KeyLabels: []string{
			"__Member__",
			"__Member__",
		},
		AggregationStatistic:   ptr.String("__AggregationStatistic__"),
		AggregateValue:         ptr.Float64(1.0),
		ApproximateUniqueCount: ptr.Int64(1),
		Contributors: []types.InsightRuleContributor{
			{
				Keys: []string{
					"__Member__",
					"__Member__",
				},
				ApproximateAggregateValue: ptr.Float64(1.0),
				Datapoints: []types.InsightRuleContributorDatapoint{
					{
						Timestamp:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						ApproximateValue: ptr.Float64(1.0),
					},
					{
						Timestamp:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						ApproximateValue: ptr.Float64(1.0),
					},
				},
			},
			{
				Keys: []string{
					"__Member__",
					"__Member__",
				},
				ApproximateAggregateValue: ptr.Float64(1.0),
				Datapoints: []types.InsightRuleContributorDatapoint{
					{
						Timestamp:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						ApproximateValue: ptr.Float64(1.0),
					},
					{
						Timestamp:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
						ApproximateValue: ptr.Float64(1.0),
					},
				},
			},
		},
		MetricDatapoints: []types.InsightRuleMetricDatapoint{
			{
				Timestamp:           ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				UniqueContributors:  ptr.Float64(1.0),
				MaxContributorValue: ptr.Float64(1.0),
				SampleCount:         ptr.Float64(1.0),
				Average:             ptr.Float64(1.0),
				Sum:                 ptr.Float64(1.0),
				Minimum:             ptr.Float64(1.0),
				Maximum:             ptr.Float64(1.0),
			},
			{
				Timestamp:           ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				UniqueContributors:  ptr.Float64(1.0),
				MaxContributorValue: ptr.Float64(1.0),
				SampleCount:         ptr.Float64(1.0),
				Average:             ptr.Float64(1.0),
				Sum:                 ptr.Float64(1.0),
				Minimum:             ptr.Float64(1.0),
				Maximum:             ptr.Float64(1.0),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetInsightRuleReport")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetInsightRuleReport(context.Background(), &GetInsightRuleReportInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetInsightRuleReport", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetMetricData(t *testing.T) {
	want := &GetMetricDataOutput{
		MetricDataResults: []types.MetricDataResult{
			{
				Id:    ptr.String("__Id__"),
				Label: ptr.String("__Label__"),
				Timestamps: []time.Time{
					time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
					time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
				},
				Values: []float64{
					1.0,
					1.0,
				},
				StatusCode: types.StatusCode("Complete"),
				Messages: []types.MessageData{
					{
						Code:  ptr.String("__Code__"),
						Value: ptr.String("__Value__"),
					},
					{
						Code:  ptr.String("__Code__"),
						Value: ptr.String("__Value__"),
					},
				},
			},
			{
				Id:    ptr.String("__Id__"),
				Label: ptr.String("__Label__"),
				Timestamps: []time.Time{
					time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
					time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
				},
				Values: []float64{
					1.0,
					1.0,
				},
				StatusCode: types.StatusCode("Complete"),
				Messages: []types.MessageData{
					{
						Code:  ptr.String("__Code__"),
						Value: ptr.String("__Value__"),
					},
					{
						Code:  ptr.String("__Code__"),
						Value: ptr.String("__Value__"),
					},
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
		Messages: []types.MessageData{
			{
				Code:  ptr.String("__Code__"),
				Value: ptr.String("__Value__"),
			},
			{
				Code:  ptr.String("__Code__"),
				Value: ptr.String("__Value__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetMetricData")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetMetricData(context.Background(), &GetMetricDataInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetMetricData", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetMetricStatistics(t *testing.T) {
	want := &GetMetricStatisticsOutput{
		Label: ptr.String("__Label__"),
		Datapoints: []types.Datapoint{
			{
				Timestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				SampleCount: ptr.Float64(1.0),
				Average:     ptr.Float64(1.0),
				Sum:         ptr.Float64(1.0),
				Minimum:     ptr.Float64(1.0),
				Maximum:     ptr.Float64(1.0),
				Unit:        types.StandardUnit("Seconds"),
				ExtendedStatistics: map[string]float64{
					"key0": 1.0,
				},
			},
			{
				Timestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				SampleCount: ptr.Float64(1.0),
				Average:     ptr.Float64(1.0),
				Sum:         ptr.Float64(1.0),
				Minimum:     ptr.Float64(1.0),
				Maximum:     ptr.Float64(1.0),
				Unit:        types.StandardUnit("Seconds"),
				ExtendedStatistics: map[string]float64{
					"key0": 1.0,
				},
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetMetricStatistics")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetMetricStatistics(context.Background(), &GetMetricStatisticsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetMetricStatistics", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetMetricStream(t *testing.T) {
	want := &GetMetricStreamOutput{
		Arn:  ptr.String("__Arn__"),
		Name: ptr.String("__Name__"),
		IncludeFilters: []types.MetricStreamFilter{
			{
				Namespace: ptr.String("__Namespace__"),
				MetricNames: []string{
					"__Member__",
					"__Member__",
				},
			},
			{
				Namespace: ptr.String("__Namespace__"),
				MetricNames: []string{
					"__Member__",
					"__Member__",
				},
			},
		},
		ExcludeFilters: []types.MetricStreamFilter{
			{
				Namespace: ptr.String("__Namespace__"),
				MetricNames: []string{
					"__Member__",
					"__Member__",
				},
			},
			{
				Namespace: ptr.String("__Namespace__"),
				MetricNames: []string{
					"__Member__",
					"__Member__",
				},
			},
		},
		FirehoseArn:    ptr.String("__FirehoseArn__"),
		RoleArn:        ptr.String("__RoleArn__"),
		State:          ptr.String("__State__"),
		CreationDate:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastUpdateDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		OutputFormat:   types.MetricStreamOutputFormat("json"),
		StatisticsConfigurations: []types.MetricStreamStatisticsConfiguration{
			{
				IncludeMetrics: []types.MetricStreamStatisticsMetric{
					{
						Namespace:  ptr.String("__Namespace__"),
						MetricName: ptr.String("__MetricName__"),
					},
					{
						Namespace:  ptr.String("__Namespace__"),
						MetricName: ptr.String("__MetricName__"),
					},
				},
				AdditionalStatistics: []string{
					"__Member__",
					"__Member__",
				},
			},
			{
				IncludeMetrics: []types.MetricStreamStatisticsMetric{
					{
						Namespace:  ptr.String("__Namespace__"),
						MetricName: ptr.String("__MetricName__"),
					},
					{
						Namespace:  ptr.String("__Namespace__"),
						MetricName: ptr.String("__MetricName__"),
					},
				},
				AdditionalStatistics: []string{
					"__Member__",
					"__Member__",
				},
			},
		},
		IncludeLinkedAccountsMetrics: ptr.Bool(true),
	}
	status, header, body, err := serdeRespReadSnapshot("GetMetricStream")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetMetricStream(context.Background(), &GetMetricStreamInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetMetricStream", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetMetricWidgetImage(t *testing.T) {
	want := &GetMetricWidgetImageOutput{
		MetricWidgetImage: []byte("blob"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetMetricWidgetImage")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetMetricWidgetImage(context.Background(), &GetMetricWidgetImageInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetMetricWidgetImage", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetOTelEnrichment(t *testing.T) {
	want := &GetOTelEnrichmentOutput{
		Status: types.OTelEnrichmentStatus("Running"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetOTelEnrichment")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetOTelEnrichment(context.Background(), &GetOTelEnrichmentInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetOTelEnrichment", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListAlarmMuteRules(t *testing.T) {
	want := &ListAlarmMuteRulesOutput{
		AlarmMuteRuleSummaries: []types.AlarmMuteRuleSummary{
			{
				AlarmMuteRuleArn:     ptr.String("__AlarmMuteRuleArn__"),
				ExpireDate:           ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Status:               types.AlarmMuteRuleStatus("SCHEDULED"),
				MuteType:             ptr.String("__MuteType__"),
				LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				AlarmMuteRuleArn:     ptr.String("__AlarmMuteRuleArn__"),
				ExpireDate:           ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Status:               types.AlarmMuteRuleStatus("SCHEDULED"),
				MuteType:             ptr.String("__MuteType__"),
				LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListAlarmMuteRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListAlarmMuteRules(context.Background(), &ListAlarmMuteRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListAlarmMuteRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListDashboards(t *testing.T) {
	want := &ListDashboardsOutput{
		DashboardEntries: []types.DashboardEntry{
			{
				DashboardName: ptr.String("__DashboardName__"),
				DashboardArn:  ptr.String("__DashboardArn__"),
				LastModified:  ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Size:          ptr.Int64(1),
			},
			{
				DashboardName: ptr.String("__DashboardName__"),
				DashboardArn:  ptr.String("__DashboardArn__"),
				LastModified:  ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Size:          ptr.Int64(1),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListDashboards")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListDashboards(context.Background(), &ListDashboardsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListDashboards", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListManagedInsightRules(t *testing.T) {
	want := &ListManagedInsightRulesOutput{
		ManagedRules: []types.ManagedRuleDescription{
			{
				TemplateName: ptr.String("__TemplateName__"),
				ResourceARN:  ptr.String("__ResourceARN__"),
				RuleState: &types.ManagedRuleState{
					RuleName: ptr.String("__RuleName__"),
					State:    ptr.String("__State__"),
				},
			},
			{
				TemplateName: ptr.String("__TemplateName__"),
				ResourceARN:  ptr.String("__ResourceARN__"),
				RuleState: &types.ManagedRuleState{
					RuleName: ptr.String("__RuleName__"),
					State:    ptr.String("__State__"),
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListManagedInsightRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListManagedInsightRules(context.Background(), &ListManagedInsightRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListManagedInsightRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListMetrics(t *testing.T) {
	want := &ListMetricsOutput{
		Metrics: []types.Metric{
			{
				Namespace:  ptr.String("__Namespace__"),
				MetricName: ptr.String("__MetricName__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
			},
			{
				Namespace:  ptr.String("__Namespace__"),
				MetricName: ptr.String("__MetricName__"),
				Dimensions: []types.Dimension{
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
					{
						Name:  ptr.String("__Name__"),
						Value: ptr.String("__Value__"),
					},
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
		OwningAccounts: []string{
			"__Member__",
			"__Member__",
		},
	}
	status, header, body, err := serdeRespReadSnapshot("ListMetrics")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListMetrics(context.Background(), &ListMetricsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListMetrics", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListMetricStreams(t *testing.T) {
	want := &ListMetricStreamsOutput{
		NextToken: ptr.String("__NextToken__"),
		Entries: []types.MetricStreamEntry{
			{
				Arn:            ptr.String("__Arn__"),
				CreationDate:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LastUpdateDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Name:           ptr.String("__Name__"),
				FirehoseArn:    ptr.String("__FirehoseArn__"),
				State:          ptr.String("__State__"),
				OutputFormat:   types.MetricStreamOutputFormat("json"),
			},
			{
				Arn:            ptr.String("__Arn__"),
				CreationDate:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LastUpdateDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Name:           ptr.String("__Name__"),
				FirehoseArn:    ptr.String("__FirehoseArn__"),
				State:          ptr.String("__State__"),
				OutputFormat:   types.MetricStreamOutputFormat("json"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("ListMetricStreams")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListMetricStreams(context.Background(), &ListMetricStreamsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListMetricStreams", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListTagsForResource(t *testing.T) {
	want := &ListTagsForResourceOutput{
		Tags: []types.Tag{
			{
				Key:   ptr.String("__Key__"),
				Value: ptr.String("__Value__"),
			},
			{
				Key:   ptr.String("__Key__"),
				Value: ptr.String("__Value__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("ListTagsForResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListTagsForResource(context.Background(), &ListTagsForResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListTagsForResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutAlarmMuteRule(t *testing.T) {
	want := &PutAlarmMuteRuleOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutAlarmMuteRule")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutAlarmMuteRule(context.Background(), &PutAlarmMuteRuleInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutAlarmMuteRule", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutAnomalyDetector(t *testing.T) {
	want := &PutAnomalyDetectorOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutAnomalyDetector")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutAnomalyDetector(context.Background(), &PutAnomalyDetectorInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutAnomalyDetector", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutCompositeAlarm(t *testing.T) {
	want := &PutCompositeAlarmOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutCompositeAlarm")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutCompositeAlarm(context.Background(), &PutCompositeAlarmInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutCompositeAlarm", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutDashboard(t *testing.T) {
	want := &PutDashboardOutput{
		DashboardValidationMessages: []types.DashboardValidationMessage{
			{
				DataPath: ptr.String("__DataPath__"),
				Message:  ptr.String("__Message__"),
			},
			{
				DataPath: ptr.String("__DataPath__"),
				Message:  ptr.String("__Message__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("PutDashboard")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutDashboard(context.Background(), &PutDashboardInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutDashboard", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutInsightRule(t *testing.T) {
	want := &PutInsightRuleOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutInsightRule")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutInsightRule(context.Background(), &PutInsightRuleInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutInsightRule", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutLogAlarm(t *testing.T) {
	want := &PutLogAlarmOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutLogAlarm")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutLogAlarm(context.Background(), &PutLogAlarmInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutLogAlarm", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutManagedInsightRules(t *testing.T) {
	want := &PutManagedInsightRulesOutput{
		Failures: []types.PartialFailure{
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
			{
				FailureResource:    ptr.String("__FailureResource__"),
				ExceptionType:      ptr.String("__ExceptionType__"),
				FailureCode:        ptr.String("__FailureCode__"),
				FailureDescription: ptr.String("__FailureDescription__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("PutManagedInsightRules")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutManagedInsightRules(context.Background(), &PutManagedInsightRulesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutManagedInsightRules", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutMetricAlarm(t *testing.T) {
	want := &PutMetricAlarmOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutMetricAlarm")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutMetricAlarm(context.Background(), &PutMetricAlarmInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutMetricAlarm", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutMetricData(t *testing.T) {
	want := &PutMetricDataOutput{}
	status, header, body, err := serdeRespReadSnapshot("PutMetricData")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutMetricData(context.Background(), &PutMetricDataInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutMetricData", err)
	}
}

func TestSerdeCheckResponseSnapshot_PutMetricStream(t *testing.T) {
	want := &PutMetricStreamOutput{
		Arn: ptr.String("__Arn__"),
	}
	status, header, body, err := serdeRespReadSnapshot("PutMetricStream")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.PutMetricStream(context.Background(), &PutMetricStreamInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "PutMetricStream", err)
	}
}

func TestSerdeCheckResponseSnapshot_SetAlarmState(t *testing.T) {
	want := &SetAlarmStateOutput{}
	status, header, body, err := serdeRespReadSnapshot("SetAlarmState")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.SetAlarmState(context.Background(), &SetAlarmStateInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "SetAlarmState", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartMetricStreams(t *testing.T) {
	want := &StartMetricStreamsOutput{}
	status, header, body, err := serdeRespReadSnapshot("StartMetricStreams")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartMetricStreams(context.Background(), &StartMetricStreamsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartMetricStreams", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartOTelEnrichment(t *testing.T) {
	want := &StartOTelEnrichmentOutput{}
	status, header, body, err := serdeRespReadSnapshot("StartOTelEnrichment")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartOTelEnrichment(context.Background(), &StartOTelEnrichmentInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartOTelEnrichment", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopMetricStreams(t *testing.T) {
	want := &StopMetricStreamsOutput{}
	status, header, body, err := serdeRespReadSnapshot("StopMetricStreams")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopMetricStreams(context.Background(), &StopMetricStreamsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopMetricStreams", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopOTelEnrichment(t *testing.T) {
	want := &StopOTelEnrichmentOutput{}
	status, header, body, err := serdeRespReadSnapshot("StopOTelEnrichment")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopOTelEnrichment(context.Background(), &StopOTelEnrichmentInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopOTelEnrichment", err)
	}
}

func TestSerdeCheckResponseSnapshot_TagResource(t *testing.T) {
	want := &TagResourceOutput{}
	status, header, body, err := serdeRespReadSnapshot("TagResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.TagResource(context.Background(), &TagResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "TagResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_UntagResource(t *testing.T) {
	want := &UntagResourceOutput{}
	status, header, body, err := serdeRespReadSnapshot("UntagResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UntagResource(context.Background(), &UntagResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UntagResource", err)
	}
}
