// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package snowball

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/snowball/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithytesting "github.com/aws/smithy-go/testing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

const serdeRespSSPrefix = "serde_response_snapshot"

func serdeRespSSPath(op string) string {
	return fmt.Sprintf("%s/%s.response.snap", serdeRespSSPrefix, op)
}

// serdeRespReadSnapshot parses a frozen wire response fixture: a status-code
// line, HTTP headers, a blank line, then the raw body.
func serdeRespReadSnapshot(op string) (int, http.Header, []byte, error) {
	raw, err := os.ReadFile(serdeRespSSPath(op))
	if err != nil {
		return 0, nil, nil, err
	}

	r := bufio.NewReader(bytes.NewReader(raw))
	statusLine, err := r.ReadString('\n')
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read status line: %w", err)
	}
	status, err := strconv.Atoi(strings.TrimSpace(statusLine))
	if err != nil {
		return 0, nil, nil, fmt.Errorf("parse status: %w", err)
	}

	header := http.Header{}
	for {
		line, err := r.ReadString('\n')
		if err != nil && err != io.EOF {
			return 0, nil, nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		k, v, ok := strings.Cut(trimmed, ": ")
		if !ok {
			return 0, nil, nil, fmt.Errorf("malformed header %q", trimmed)
		}
		header.Add(k, v)
		if err == io.EOF {
			break
		}
	}

	body, err := io.ReadAll(r)
	if err != nil {
		return 0, nil, nil, err
	}
	return status, header, body, nil
}

type serdeRespEndpointResolver struct{}

func (*serdeRespEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeRespClient(status int, header http.Header, body []byte) *Client {
	return New(Options{
		Region: "us-east-1",
		HTTPClient: smithyhttp.ClientDoFunc(func(req *http.Request) (*http.Response, error) {
			resp := &http.Response{StatusCode: status, Header: header, Request: req}
			if len(body) > 0 {
				resp.ContentLength = int64(len(body))
				resp.Body = io.NopCloser(bytes.NewReader(body))
			} else {
				resp.Body = http.NoBody
			}
			return resp, nil
		}),
		EndpointResolverV2: &serdeRespEndpointResolver{},
		APIOptions: []func(*middleware.Stack) error{
			func(s *middleware.Stack) error {
				s.Finalize.Clear()
				s.Initialize.Remove("OperationInputValidation")
				return nil
			},
		},
	})
}
func TestSerdeCheckResponseSnapshot_CancelCluster(t *testing.T) {
	want := &CancelClusterOutput{}
	status, header, body, err := serdeRespReadSnapshot("CancelCluster")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CancelCluster(context.Background(), &CancelClusterInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CancelCluster", err)
	}
}

func TestSerdeCheckResponseSnapshot_CancelJob(t *testing.T) {
	want := &CancelJobOutput{}
	status, header, body, err := serdeRespReadSnapshot("CancelJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CancelJob(context.Background(), &CancelJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CancelJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateAddress(t *testing.T) {
	want := &CreateAddressOutput{
		AddressId: ptr.String("__AddressId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateAddress")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateAddress(context.Background(), &CreateAddressInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateAddress", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateCluster(t *testing.T) {
	want := &CreateClusterOutput{
		ClusterId: ptr.String("__ClusterId__"),
		JobListEntries: []types.JobListEntry{
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				IsMaster:     true,
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				IsMaster:     true,
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("CreateCluster")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateCluster(context.Background(), &CreateClusterInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateCluster", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateJob(t *testing.T) {
	want := &CreateJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateJob(context.Background(), &CreateJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateLongTermPricing(t *testing.T) {
	want := &CreateLongTermPricingOutput{
		LongTermPricingId: ptr.String("__LongTermPricingId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateLongTermPricing")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateLongTermPricing(context.Background(), &CreateLongTermPricingInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateLongTermPricing", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateReturnShippingLabel(t *testing.T) {
	want := &CreateReturnShippingLabelOutput{
		Status: types.ShippingLabelStatus("InProgress"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateReturnShippingLabel")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateReturnShippingLabel(context.Background(), &CreateReturnShippingLabelInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateReturnShippingLabel", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAddress(t *testing.T) {
	want := &DescribeAddressOutput{
		Address: &types.Address{
			AddressId:            ptr.String("__AddressId__"),
			Name:                 ptr.String("__Name__"),
			Company:              ptr.String("__Company__"),
			Street1:              ptr.String("__Street1__"),
			Street2:              ptr.String("__Street2__"),
			Street3:              ptr.String("__Street3__"),
			City:                 ptr.String("__City__"),
			StateOrProvince:      ptr.String("__StateOrProvince__"),
			PrefectureOrDistrict: ptr.String("__PrefectureOrDistrict__"),
			Landmark:             ptr.String("__Landmark__"),
			Country:              ptr.String("__Country__"),
			PostalCode:           ptr.String("__PostalCode__"),
			PhoneNumber:          ptr.String("__PhoneNumber__"),
			IsRestricted:         true,
			Type:                 types.AddressType("CUST_PICKUP"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAddress")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAddress(context.Background(), &DescribeAddressInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAddress", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeAddresses(t *testing.T) {
	want := &DescribeAddressesOutput{
		Addresses: []types.Address{
			{
				AddressId:            ptr.String("__AddressId__"),
				Name:                 ptr.String("__Name__"),
				Company:              ptr.String("__Company__"),
				Street1:              ptr.String("__Street1__"),
				Street2:              ptr.String("__Street2__"),
				Street3:              ptr.String("__Street3__"),
				City:                 ptr.String("__City__"),
				StateOrProvince:      ptr.String("__StateOrProvince__"),
				PrefectureOrDistrict: ptr.String("__PrefectureOrDistrict__"),
				Landmark:             ptr.String("__Landmark__"),
				Country:              ptr.String("__Country__"),
				PostalCode:           ptr.String("__PostalCode__"),
				PhoneNumber:          ptr.String("__PhoneNumber__"),
				IsRestricted:         true,
				Type:                 types.AddressType("CUST_PICKUP"),
			},
			{
				AddressId:            ptr.String("__AddressId__"),
				Name:                 ptr.String("__Name__"),
				Company:              ptr.String("__Company__"),
				Street1:              ptr.String("__Street1__"),
				Street2:              ptr.String("__Street2__"),
				Street3:              ptr.String("__Street3__"),
				City:                 ptr.String("__City__"),
				StateOrProvince:      ptr.String("__StateOrProvince__"),
				PrefectureOrDistrict: ptr.String("__PrefectureOrDistrict__"),
				Landmark:             ptr.String("__Landmark__"),
				Country:              ptr.String("__Country__"),
				PostalCode:           ptr.String("__PostalCode__"),
				PhoneNumber:          ptr.String("__PhoneNumber__"),
				IsRestricted:         true,
				Type:                 types.AddressType("CUST_PICKUP"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeAddresses")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeAddresses(context.Background(), &DescribeAddressesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeAddresses", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeCluster(t *testing.T) {
	want := &DescribeClusterOutput{
		ClusterMetadata: &types.ClusterMetadata{
			ClusterId:    ptr.String("__ClusterId__"),
			Description:  ptr.String("__Description__"),
			KmsKeyARN:    ptr.String("__KmsKeyARN__"),
			RoleARN:      ptr.String("__RoleARN__"),
			ClusterState: types.ClusterState("AwaitingQuorum"),
			JobType:      types.JobType("IMPORT"),
			SnowballType: types.SnowballType("STANDARD"),
			CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			Resources: &types.JobResource{
				S3Resources: []types.S3Resource{
					{
						BucketArn: ptr.String("__BucketArn__"),
						KeyRange: &types.KeyRange{
							BeginMarker: ptr.String("__BeginMarker__"),
							EndMarker:   ptr.String("__EndMarker__"),
						},
						TargetOnDeviceServices: []types.TargetOnDeviceService{
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
						},
					},
					{
						BucketArn: ptr.String("__BucketArn__"),
						KeyRange: &types.KeyRange{
							BeginMarker: ptr.String("__BeginMarker__"),
							EndMarker:   ptr.String("__EndMarker__"),
						},
						TargetOnDeviceServices: []types.TargetOnDeviceService{
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
						},
					},
				},
				LambdaResources: []types.LambdaResource{
					{
						LambdaArn: ptr.String("__LambdaArn__"),
						EventTriggers: []types.EventTriggerDefinition{
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
						},
					},
					{
						LambdaArn: ptr.String("__LambdaArn__"),
						EventTriggers: []types.EventTriggerDefinition{
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
						},
					},
				},
				Ec2AmiResources: []types.Ec2AmiResource{
					{
						AmiId:         ptr.String("__AmiId__"),
						SnowballAmiId: ptr.String("__SnowballAmiId__"),
					},
					{
						AmiId:         ptr.String("__AmiId__"),
						SnowballAmiId: ptr.String("__SnowballAmiId__"),
					},
				},
			},
			AddressId:      ptr.String("__AddressId__"),
			ShippingOption: types.ShippingOption("SECOND_DAY"),
			Notification: &types.Notification{
				SnsTopicARN: ptr.String("__SnsTopicARN__"),
				JobStatesToNotify: []types.JobState{
					types.JobState("New"),
					types.JobState("New"),
				},
				NotifyAll:               true,
				DevicePickupSnsTopicARN: ptr.String("__DevicePickupSnsTopicARN__"),
			},
			ForwardingAddressId: ptr.String("__ForwardingAddressId__"),
			TaxDocuments: &types.TaxDocuments{
				IND: &types.INDTaxDocuments{
					GSTIN: ptr.String("__GSTIN__"),
				},
			},
			OnDeviceServiceConfiguration: &types.OnDeviceServiceConfiguration{
				NFSOnDeviceService: &types.NFSOnDeviceServiceConfiguration{
					StorageLimit: 1,
					StorageUnit:  types.StorageUnit("TB"),
				},
				TGWOnDeviceService: &types.TGWOnDeviceServiceConfiguration{
					StorageLimit: 1,
					StorageUnit:  types.StorageUnit("TB"),
				},
				EKSOnDeviceService: &types.EKSOnDeviceServiceConfiguration{
					KubernetesVersion:  ptr.String("__KubernetesVersion__"),
					EKSAnywhereVersion: ptr.String("__EKSAnywhereVersion__"),
				},
				S3OnDeviceService: &types.S3OnDeviceServiceConfiguration{
					StorageLimit:   ptr.Float64(1.0),
					StorageUnit:    types.StorageUnit("TB"),
					ServiceSize:    ptr.Int32(1),
					FaultTolerance: ptr.Int32(1),
				},
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeCluster")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeCluster(context.Background(), &DescribeClusterInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeCluster", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeJob(t *testing.T) {
	want := &DescribeJobOutput{
		JobMetadata: &types.JobMetadata{
			JobId:        ptr.String("__JobId__"),
			JobState:     types.JobState("New"),
			JobType:      types.JobType("IMPORT"),
			SnowballType: types.SnowballType("STANDARD"),
			CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			Resources: &types.JobResource{
				S3Resources: []types.S3Resource{
					{
						BucketArn: ptr.String("__BucketArn__"),
						KeyRange: &types.KeyRange{
							BeginMarker: ptr.String("__BeginMarker__"),
							EndMarker:   ptr.String("__EndMarker__"),
						},
						TargetOnDeviceServices: []types.TargetOnDeviceService{
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
						},
					},
					{
						BucketArn: ptr.String("__BucketArn__"),
						KeyRange: &types.KeyRange{
							BeginMarker: ptr.String("__BeginMarker__"),
							EndMarker:   ptr.String("__EndMarker__"),
						},
						TargetOnDeviceServices: []types.TargetOnDeviceService{
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
							{
								ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
								TransferOption: types.TransferOption("IMPORT"),
							},
						},
					},
				},
				LambdaResources: []types.LambdaResource{
					{
						LambdaArn: ptr.String("__LambdaArn__"),
						EventTriggers: []types.EventTriggerDefinition{
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
						},
					},
					{
						LambdaArn: ptr.String("__LambdaArn__"),
						EventTriggers: []types.EventTriggerDefinition{
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
							{
								EventResourceARN: ptr.String("__EventResourceARN__"),
							},
						},
					},
				},
				Ec2AmiResources: []types.Ec2AmiResource{
					{
						AmiId:         ptr.String("__AmiId__"),
						SnowballAmiId: ptr.String("__SnowballAmiId__"),
					},
					{
						AmiId:         ptr.String("__AmiId__"),
						SnowballAmiId: ptr.String("__SnowballAmiId__"),
					},
				},
			},
			Description: ptr.String("__Description__"),
			KmsKeyARN:   ptr.String("__KmsKeyARN__"),
			RoleARN:     ptr.String("__RoleARN__"),
			AddressId:   ptr.String("__AddressId__"),
			ShippingDetails: &types.ShippingDetails{
				ShippingOption: types.ShippingOption("SECOND_DAY"),
				InboundShipment: &types.Shipment{
					Status:         ptr.String("__Status__"),
					TrackingNumber: ptr.String("__TrackingNumber__"),
				},
				OutboundShipment: &types.Shipment{
					Status:         ptr.String("__Status__"),
					TrackingNumber: ptr.String("__TrackingNumber__"),
				},
			},
			SnowballCapacityPreference: types.SnowballCapacity("T50"),
			Notification: &types.Notification{
				SnsTopicARN: ptr.String("__SnsTopicARN__"),
				JobStatesToNotify: []types.JobState{
					types.JobState("New"),
					types.JobState("New"),
				},
				NotifyAll:               true,
				DevicePickupSnsTopicARN: ptr.String("__DevicePickupSnsTopicARN__"),
			},
			DataTransferProgress: &types.DataTransfer{
				BytesTransferred:   1,
				ObjectsTransferred: 1,
				TotalBytes:         1,
				TotalObjects:       1,
			},
			JobLogInfo: &types.JobLogs{
				JobCompletionReportURI: ptr.String("__JobCompletionReportURI__"),
				JobSuccessLogURI:       ptr.String("__JobSuccessLogURI__"),
				JobFailureLogURI:       ptr.String("__JobFailureLogURI__"),
			},
			ClusterId:           ptr.String("__ClusterId__"),
			ForwardingAddressId: ptr.String("__ForwardingAddressId__"),
			TaxDocuments: &types.TaxDocuments{
				IND: &types.INDTaxDocuments{
					GSTIN: ptr.String("__GSTIN__"),
				},
			},
			DeviceConfiguration: &types.DeviceConfiguration{
				SnowconeDeviceConfiguration: &types.SnowconeDeviceConfiguration{
					WirelessConnection: &types.WirelessConnection{
						IsWifiEnabled: true,
					},
				},
			},
			RemoteManagement:  types.RemoteManagement("INSTALLED_ONLY"),
			LongTermPricingId: ptr.String("__LongTermPricingId__"),
			OnDeviceServiceConfiguration: &types.OnDeviceServiceConfiguration{
				NFSOnDeviceService: &types.NFSOnDeviceServiceConfiguration{
					StorageLimit: 1,
					StorageUnit:  types.StorageUnit("TB"),
				},
				TGWOnDeviceService: &types.TGWOnDeviceServiceConfiguration{
					StorageLimit: 1,
					StorageUnit:  types.StorageUnit("TB"),
				},
				EKSOnDeviceService: &types.EKSOnDeviceServiceConfiguration{
					KubernetesVersion:  ptr.String("__KubernetesVersion__"),
					EKSAnywhereVersion: ptr.String("__EKSAnywhereVersion__"),
				},
				S3OnDeviceService: &types.S3OnDeviceServiceConfiguration{
					StorageLimit:   ptr.Float64(1.0),
					StorageUnit:    types.StorageUnit("TB"),
					ServiceSize:    ptr.Int32(1),
					FaultTolerance: ptr.Int32(1),
				},
			},
			ImpactLevel: types.ImpactLevel("IL2"),
			PickupDetails: &types.PickupDetails{
				Name:                         ptr.String("__Name__"),
				PhoneNumber:                  ptr.String("__PhoneNumber__"),
				Email:                        ptr.String("__Email__"),
				IdentificationNumber:         ptr.String("__IdentificationNumber__"),
				IdentificationExpirationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				IdentificationIssuingOrg:     ptr.String("__IdentificationIssuingOrg__"),
				DevicePickupId:               ptr.String("__DevicePickupId__"),
			},
			SnowballId: ptr.String("__SnowballId__"),
		},
		SubJobMetadata: []types.JobMetadata{
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Resources: &types.JobResource{
					S3Resources: []types.S3Resource{
						{
							BucketArn: ptr.String("__BucketArn__"),
							KeyRange: &types.KeyRange{
								BeginMarker: ptr.String("__BeginMarker__"),
								EndMarker:   ptr.String("__EndMarker__"),
							},
							TargetOnDeviceServices: []types.TargetOnDeviceService{
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
							},
						},
						{
							BucketArn: ptr.String("__BucketArn__"),
							KeyRange: &types.KeyRange{
								BeginMarker: ptr.String("__BeginMarker__"),
								EndMarker:   ptr.String("__EndMarker__"),
							},
							TargetOnDeviceServices: []types.TargetOnDeviceService{
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
							},
						},
					},
					LambdaResources: []types.LambdaResource{
						{
							LambdaArn: ptr.String("__LambdaArn__"),
							EventTriggers: []types.EventTriggerDefinition{
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
							},
						},
						{
							LambdaArn: ptr.String("__LambdaArn__"),
							EventTriggers: []types.EventTriggerDefinition{
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
							},
						},
					},
					Ec2AmiResources: []types.Ec2AmiResource{
						{
							AmiId:         ptr.String("__AmiId__"),
							SnowballAmiId: ptr.String("__SnowballAmiId__"),
						},
						{
							AmiId:         ptr.String("__AmiId__"),
							SnowballAmiId: ptr.String("__SnowballAmiId__"),
						},
					},
				},
				Description: ptr.String("__Description__"),
				KmsKeyARN:   ptr.String("__KmsKeyARN__"),
				RoleARN:     ptr.String("__RoleARN__"),
				AddressId:   ptr.String("__AddressId__"),
				ShippingDetails: &types.ShippingDetails{
					ShippingOption: types.ShippingOption("SECOND_DAY"),
					InboundShipment: &types.Shipment{
						Status:         ptr.String("__Status__"),
						TrackingNumber: ptr.String("__TrackingNumber__"),
					},
					OutboundShipment: &types.Shipment{
						Status:         ptr.String("__Status__"),
						TrackingNumber: ptr.String("__TrackingNumber__"),
					},
				},
				SnowballCapacityPreference: types.SnowballCapacity("T50"),
				Notification: &types.Notification{
					SnsTopicARN: ptr.String("__SnsTopicARN__"),
					JobStatesToNotify: []types.JobState{
						types.JobState("New"),
						types.JobState("New"),
					},
					NotifyAll:               true,
					DevicePickupSnsTopicARN: ptr.String("__DevicePickupSnsTopicARN__"),
				},
				DataTransferProgress: &types.DataTransfer{
					BytesTransferred:   1,
					ObjectsTransferred: 1,
					TotalBytes:         1,
					TotalObjects:       1,
				},
				JobLogInfo: &types.JobLogs{
					JobCompletionReportURI: ptr.String("__JobCompletionReportURI__"),
					JobSuccessLogURI:       ptr.String("__JobSuccessLogURI__"),
					JobFailureLogURI:       ptr.String("__JobFailureLogURI__"),
				},
				ClusterId:           ptr.String("__ClusterId__"),
				ForwardingAddressId: ptr.String("__ForwardingAddressId__"),
				TaxDocuments: &types.TaxDocuments{
					IND: &types.INDTaxDocuments{
						GSTIN: ptr.String("__GSTIN__"),
					},
				},
				DeviceConfiguration: &types.DeviceConfiguration{
					SnowconeDeviceConfiguration: &types.SnowconeDeviceConfiguration{
						WirelessConnection: &types.WirelessConnection{
							IsWifiEnabled: true,
						},
					},
				},
				RemoteManagement:  types.RemoteManagement("INSTALLED_ONLY"),
				LongTermPricingId: ptr.String("__LongTermPricingId__"),
				OnDeviceServiceConfiguration: &types.OnDeviceServiceConfiguration{
					NFSOnDeviceService: &types.NFSOnDeviceServiceConfiguration{
						StorageLimit: 1,
						StorageUnit:  types.StorageUnit("TB"),
					},
					TGWOnDeviceService: &types.TGWOnDeviceServiceConfiguration{
						StorageLimit: 1,
						StorageUnit:  types.StorageUnit("TB"),
					},
					EKSOnDeviceService: &types.EKSOnDeviceServiceConfiguration{
						KubernetesVersion:  ptr.String("__KubernetesVersion__"),
						EKSAnywhereVersion: ptr.String("__EKSAnywhereVersion__"),
					},
					S3OnDeviceService: &types.S3OnDeviceServiceConfiguration{
						StorageLimit:   ptr.Float64(1.0),
						StorageUnit:    types.StorageUnit("TB"),
						ServiceSize:    ptr.Int32(1),
						FaultTolerance: ptr.Int32(1),
					},
				},
				ImpactLevel: types.ImpactLevel("IL2"),
				PickupDetails: &types.PickupDetails{
					Name:                         ptr.String("__Name__"),
					PhoneNumber:                  ptr.String("__PhoneNumber__"),
					Email:                        ptr.String("__Email__"),
					IdentificationNumber:         ptr.String("__IdentificationNumber__"),
					IdentificationExpirationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					IdentificationIssuingOrg:     ptr.String("__IdentificationIssuingOrg__"),
					DevicePickupId:               ptr.String("__DevicePickupId__"),
				},
				SnowballId: ptr.String("__SnowballId__"),
			},
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Resources: &types.JobResource{
					S3Resources: []types.S3Resource{
						{
							BucketArn: ptr.String("__BucketArn__"),
							KeyRange: &types.KeyRange{
								BeginMarker: ptr.String("__BeginMarker__"),
								EndMarker:   ptr.String("__EndMarker__"),
							},
							TargetOnDeviceServices: []types.TargetOnDeviceService{
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
							},
						},
						{
							BucketArn: ptr.String("__BucketArn__"),
							KeyRange: &types.KeyRange{
								BeginMarker: ptr.String("__BeginMarker__"),
								EndMarker:   ptr.String("__EndMarker__"),
							},
							TargetOnDeviceServices: []types.TargetOnDeviceService{
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
								{
									ServiceName:    types.DeviceServiceName("NFS_ON_DEVICE_SERVICE"),
									TransferOption: types.TransferOption("IMPORT"),
								},
							},
						},
					},
					LambdaResources: []types.LambdaResource{
						{
							LambdaArn: ptr.String("__LambdaArn__"),
							EventTriggers: []types.EventTriggerDefinition{
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
							},
						},
						{
							LambdaArn: ptr.String("__LambdaArn__"),
							EventTriggers: []types.EventTriggerDefinition{
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
								{
									EventResourceARN: ptr.String("__EventResourceARN__"),
								},
							},
						},
					},
					Ec2AmiResources: []types.Ec2AmiResource{
						{
							AmiId:         ptr.String("__AmiId__"),
							SnowballAmiId: ptr.String("__SnowballAmiId__"),
						},
						{
							AmiId:         ptr.String("__AmiId__"),
							SnowballAmiId: ptr.String("__SnowballAmiId__"),
						},
					},
				},
				Description: ptr.String("__Description__"),
				KmsKeyARN:   ptr.String("__KmsKeyARN__"),
				RoleARN:     ptr.String("__RoleARN__"),
				AddressId:   ptr.String("__AddressId__"),
				ShippingDetails: &types.ShippingDetails{
					ShippingOption: types.ShippingOption("SECOND_DAY"),
					InboundShipment: &types.Shipment{
						Status:         ptr.String("__Status__"),
						TrackingNumber: ptr.String("__TrackingNumber__"),
					},
					OutboundShipment: &types.Shipment{
						Status:         ptr.String("__Status__"),
						TrackingNumber: ptr.String("__TrackingNumber__"),
					},
				},
				SnowballCapacityPreference: types.SnowballCapacity("T50"),
				Notification: &types.Notification{
					SnsTopicARN: ptr.String("__SnsTopicARN__"),
					JobStatesToNotify: []types.JobState{
						types.JobState("New"),
						types.JobState("New"),
					},
					NotifyAll:               true,
					DevicePickupSnsTopicARN: ptr.String("__DevicePickupSnsTopicARN__"),
				},
				DataTransferProgress: &types.DataTransfer{
					BytesTransferred:   1,
					ObjectsTransferred: 1,
					TotalBytes:         1,
					TotalObjects:       1,
				},
				JobLogInfo: &types.JobLogs{
					JobCompletionReportURI: ptr.String("__JobCompletionReportURI__"),
					JobSuccessLogURI:       ptr.String("__JobSuccessLogURI__"),
					JobFailureLogURI:       ptr.String("__JobFailureLogURI__"),
				},
				ClusterId:           ptr.String("__ClusterId__"),
				ForwardingAddressId: ptr.String("__ForwardingAddressId__"),
				TaxDocuments: &types.TaxDocuments{
					IND: &types.INDTaxDocuments{
						GSTIN: ptr.String("__GSTIN__"),
					},
				},
				DeviceConfiguration: &types.DeviceConfiguration{
					SnowconeDeviceConfiguration: &types.SnowconeDeviceConfiguration{
						WirelessConnection: &types.WirelessConnection{
							IsWifiEnabled: true,
						},
					},
				},
				RemoteManagement:  types.RemoteManagement("INSTALLED_ONLY"),
				LongTermPricingId: ptr.String("__LongTermPricingId__"),
				OnDeviceServiceConfiguration: &types.OnDeviceServiceConfiguration{
					NFSOnDeviceService: &types.NFSOnDeviceServiceConfiguration{
						StorageLimit: 1,
						StorageUnit:  types.StorageUnit("TB"),
					},
					TGWOnDeviceService: &types.TGWOnDeviceServiceConfiguration{
						StorageLimit: 1,
						StorageUnit:  types.StorageUnit("TB"),
					},
					EKSOnDeviceService: &types.EKSOnDeviceServiceConfiguration{
						KubernetesVersion:  ptr.String("__KubernetesVersion__"),
						EKSAnywhereVersion: ptr.String("__EKSAnywhereVersion__"),
					},
					S3OnDeviceService: &types.S3OnDeviceServiceConfiguration{
						StorageLimit:   ptr.Float64(1.0),
						StorageUnit:    types.StorageUnit("TB"),
						ServiceSize:    ptr.Int32(1),
						FaultTolerance: ptr.Int32(1),
					},
				},
				ImpactLevel: types.ImpactLevel("IL2"),
				PickupDetails: &types.PickupDetails{
					Name:                         ptr.String("__Name__"),
					PhoneNumber:                  ptr.String("__PhoneNumber__"),
					Email:                        ptr.String("__Email__"),
					IdentificationNumber:         ptr.String("__IdentificationNumber__"),
					IdentificationExpirationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					IdentificationIssuingOrg:     ptr.String("__IdentificationIssuingOrg__"),
					DevicePickupId:               ptr.String("__DevicePickupId__"),
				},
				SnowballId: ptr.String("__SnowballId__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeJob(context.Background(), &DescribeJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeReturnShippingLabel(t *testing.T) {
	want := &DescribeReturnShippingLabelOutput{
		Status:                 types.ShippingLabelStatus("InProgress"),
		ExpirationDate:         ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		ReturnShippingLabelURI: ptr.String("__ReturnShippingLabelURI__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeReturnShippingLabel")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeReturnShippingLabel(context.Background(), &DescribeReturnShippingLabelInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeReturnShippingLabel", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetJobManifest(t *testing.T) {
	want := &GetJobManifestOutput{
		ManifestURI: ptr.String("__ManifestURI__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetJobManifest")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetJobManifest(context.Background(), &GetJobManifestInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetJobManifest", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetJobUnlockCode(t *testing.T) {
	want := &GetJobUnlockCodeOutput{
		UnlockCode: ptr.String("__UnlockCode__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetJobUnlockCode")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetJobUnlockCode(context.Background(), &GetJobUnlockCodeInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetJobUnlockCode", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetSnowballUsage(t *testing.T) {
	want := &GetSnowballUsageOutput{
		SnowballLimit:  ptr.Int32(1),
		SnowballsInUse: ptr.Int32(1),
	}
	status, header, body, err := serdeRespReadSnapshot("GetSnowballUsage")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetSnowballUsage(context.Background(), &GetSnowballUsageInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetSnowballUsage", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetSoftwareUpdates(t *testing.T) {
	want := &GetSoftwareUpdatesOutput{
		UpdatesURI: ptr.String("__UpdatesURI__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetSoftwareUpdates")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetSoftwareUpdates(context.Background(), &GetSoftwareUpdatesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetSoftwareUpdates", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListClusterJobs(t *testing.T) {
	want := &ListClusterJobsOutput{
		JobListEntries: []types.JobListEntry{
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				IsMaster:     true,
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				IsMaster:     true,
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListClusterJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListClusterJobs(context.Background(), &ListClusterJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListClusterJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListClusters(t *testing.T) {
	want := &ListClustersOutput{
		ClusterListEntries: []types.ClusterListEntry{
			{
				ClusterId:    ptr.String("__ClusterId__"),
				ClusterState: types.ClusterState("AwaitingQuorum"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
			{
				ClusterId:    ptr.String("__ClusterId__"),
				ClusterState: types.ClusterState("AwaitingQuorum"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListClusters")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListClusters(context.Background(), &ListClustersInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListClusters", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListCompatibleImages(t *testing.T) {
	want := &ListCompatibleImagesOutput{
		CompatibleImages: []types.CompatibleImage{
			{
				AmiId: ptr.String("__AmiId__"),
				Name:  ptr.String("__Name__"),
			},
			{
				AmiId: ptr.String("__AmiId__"),
				Name:  ptr.String("__Name__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListCompatibleImages")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListCompatibleImages(context.Background(), &ListCompatibleImagesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListCompatibleImages", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListJobs(t *testing.T) {
	want := &ListJobsOutput{
		JobListEntries: []types.JobListEntry{
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				IsMaster:     true,
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
			{
				JobId:        ptr.String("__JobId__"),
				JobState:     types.JobState("New"),
				IsMaster:     true,
				JobType:      types.JobType("IMPORT"),
				SnowballType: types.SnowballType("STANDARD"),
				CreationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Description:  ptr.String("__Description__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListJobs(context.Background(), &ListJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListLongTermPricing(t *testing.T) {
	want := &ListLongTermPricingOutput{
		LongTermPricingEntries: []types.LongTermPricingListEntry{
			{
				LongTermPricingId:          ptr.String("__LongTermPricingId__"),
				LongTermPricingEndDate:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LongTermPricingStartDate:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LongTermPricingType:        types.LongTermPricingType("OneYear"),
				CurrentActiveJob:           ptr.String("__CurrentActiveJob__"),
				ReplacementJob:             ptr.String("__ReplacementJob__"),
				IsLongTermPricingAutoRenew: ptr.Bool(true),
				LongTermPricingStatus:      ptr.String("__LongTermPricingStatus__"),
				SnowballType:               types.SnowballType("STANDARD"),
				JobIds: []string{
					"__Member__",
					"__Member__",
				},
			},
			{
				LongTermPricingId:          ptr.String("__LongTermPricingId__"),
				LongTermPricingEndDate:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LongTermPricingStartDate:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LongTermPricingType:        types.LongTermPricingType("OneYear"),
				CurrentActiveJob:           ptr.String("__CurrentActiveJob__"),
				ReplacementJob:             ptr.String("__ReplacementJob__"),
				IsLongTermPricingAutoRenew: ptr.Bool(true),
				LongTermPricingStatus:      ptr.String("__LongTermPricingStatus__"),
				SnowballType:               types.SnowballType("STANDARD"),
				JobIds: []string{
					"__Member__",
					"__Member__",
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListLongTermPricing")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListLongTermPricing(context.Background(), &ListLongTermPricingInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListLongTermPricing", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListPickupLocations(t *testing.T) {
	want := &ListPickupLocationsOutput{
		Addresses: []types.Address{
			{
				AddressId:            ptr.String("__AddressId__"),
				Name:                 ptr.String("__Name__"),
				Company:              ptr.String("__Company__"),
				Street1:              ptr.String("__Street1__"),
				Street2:              ptr.String("__Street2__"),
				Street3:              ptr.String("__Street3__"),
				City:                 ptr.String("__City__"),
				StateOrProvince:      ptr.String("__StateOrProvince__"),
				PrefectureOrDistrict: ptr.String("__PrefectureOrDistrict__"),
				Landmark:             ptr.String("__Landmark__"),
				Country:              ptr.String("__Country__"),
				PostalCode:           ptr.String("__PostalCode__"),
				PhoneNumber:          ptr.String("__PhoneNumber__"),
				IsRestricted:         true,
				Type:                 types.AddressType("CUST_PICKUP"),
			},
			{
				AddressId:            ptr.String("__AddressId__"),
				Name:                 ptr.String("__Name__"),
				Company:              ptr.String("__Company__"),
				Street1:              ptr.String("__Street1__"),
				Street2:              ptr.String("__Street2__"),
				Street3:              ptr.String("__Street3__"),
				City:                 ptr.String("__City__"),
				StateOrProvince:      ptr.String("__StateOrProvince__"),
				PrefectureOrDistrict: ptr.String("__PrefectureOrDistrict__"),
				Landmark:             ptr.String("__Landmark__"),
				Country:              ptr.String("__Country__"),
				PostalCode:           ptr.String("__PostalCode__"),
				PhoneNumber:          ptr.String("__PhoneNumber__"),
				IsRestricted:         true,
				Type:                 types.AddressType("CUST_PICKUP"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListPickupLocations")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListPickupLocations(context.Background(), &ListPickupLocationsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListPickupLocations", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListServiceVersions(t *testing.T) {
	want := &ListServiceVersionsOutput{
		ServiceVersions: []types.ServiceVersion{
			{
				Version: ptr.String("__Version__"),
			},
			{
				Version: ptr.String("__Version__"),
			},
		},
		ServiceName: types.ServiceName("KUBERNETES"),
		DependentServices: []types.DependentService{
			{
				ServiceName: types.ServiceName("KUBERNETES"),
				ServiceVersion: &types.ServiceVersion{
					Version: ptr.String("__Version__"),
				},
			},
			{
				ServiceName: types.ServiceName("KUBERNETES"),
				ServiceVersion: &types.ServiceVersion{
					Version: ptr.String("__Version__"),
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListServiceVersions")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListServiceVersions(context.Background(), &ListServiceVersionsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListServiceVersions", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateCluster(t *testing.T) {
	want := &UpdateClusterOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateCluster")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateCluster(context.Background(), &UpdateClusterInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateCluster", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateJob(t *testing.T) {
	want := &UpdateJobOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateJob(context.Background(), &UpdateJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateJobShipmentState(t *testing.T) {
	want := &UpdateJobShipmentStateOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateJobShipmentState")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateJobShipmentState(context.Background(), &UpdateJobShipmentStateInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateJobShipmentState", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateLongTermPricing(t *testing.T) {
	want := &UpdateLongTermPricingOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateLongTermPricing")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateLongTermPricing(context.Background(), &UpdateLongTermPricingInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateLongTermPricing", err)
	}
}
