// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package smithyrpcv2cbor

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithytesting "github.com/aws/smithy-go/testing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

const serdeRespSSPrefix = "serde_response_snapshot"

func serdeRespSSPath(op string) string {
	return fmt.Sprintf("%s/%s.response.snap", serdeRespSSPrefix, op)
}

// serdeRespReadSnapshot parses a frozen wire response fixture: a status-code
// line, HTTP headers, a blank line, then the raw body.
func serdeRespReadSnapshot(op string) (int, http.Header, []byte, error) {
	raw, err := os.ReadFile(serdeRespSSPath(op))
	if err != nil {
		return 0, nil, nil, err
	}

	r := bufio.NewReader(bytes.NewReader(raw))
	statusLine, err := r.ReadString('\n')
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read status line: %w", err)
	}
	status, err := strconv.Atoi(strings.TrimSpace(statusLine))
	if err != nil {
		return 0, nil, nil, fmt.Errorf("parse status: %w", err)
	}

	header := http.Header{}
	for {
		line, err := r.ReadString('\n')
		if err != nil && err != io.EOF {
			return 0, nil, nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		k, v, ok := strings.Cut(trimmed, ": ")
		if !ok {
			return 0, nil, nil, fmt.Errorf("malformed header %q", trimmed)
		}
		header.Add(k, v)
		if err == io.EOF {
			break
		}
	}

	body, err := io.ReadAll(r)
	if err != nil {
		return 0, nil, nil, err
	}
	return status, header, body, nil
}

type serdeRespEndpointResolver struct{}

func (*serdeRespEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeRespClient(status int, header http.Header, body []byte) *Client {
	return New(Options{
		Region: "us-east-1",
		HTTPClient: smithyhttp.ClientDoFunc(func(req *http.Request) (*http.Response, error) {
			resp := &http.Response{StatusCode: status, Header: header, Request: req}
			if len(body) > 0 {
				resp.ContentLength = int64(len(body))
				resp.Body = io.NopCloser(bytes.NewReader(body))
			} else {
				resp.Body = http.NoBody
			}
			return resp, nil
		}),
		EndpointResolverV2: &serdeRespEndpointResolver{},
		APIOptions: []func(*middleware.Stack) error{
			func(s *middleware.Stack) error {
				s.Finalize.Clear()
				s.Initialize.Remove("OperationInputValidation")
				return nil
			},
		},
	})
}
func TestSerdeCheckResponseSnapshot_EmptyInputOutput(t *testing.T) {
	want := &EmptyInputOutputOutput{}
	status, header, body, err := serdeRespReadSnapshot("EmptyInputOutput")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.EmptyInputOutput(context.Background(), &EmptyInputOutputInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "EmptyInputOutput", err)
	}
}

func TestSerdeCheckResponseSnapshot_Float16(t *testing.T) {
	want := &Float16Output{
		Value: ptr.Float64(1.0),
	}
	status, header, body, err := serdeRespReadSnapshot("Float16")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.Float16(context.Background(), &Float16Input{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "Float16", err)
	}
}

func TestSerdeCheckResponseSnapshot_FractionalSeconds(t *testing.T) {
	want := &FractionalSecondsOutput{
		Datetime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("FractionalSeconds")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.FractionalSeconds(context.Background(), &FractionalSecondsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "FractionalSeconds", err)
	}
}

func TestSerdeCheckResponseSnapshot_GreetingWithErrors(t *testing.T) {
	want := &GreetingWithErrorsOutput{
		Greeting: ptr.String("__Greeting__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GreetingWithErrors")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GreetingWithErrors(context.Background(), &GreetingWithErrorsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GreetingWithErrors", err)
	}
}

func TestSerdeCheckResponseSnapshot_NoInputOutput(t *testing.T) {
	want := &NoInputOutputOutput{}
	status, header, body, err := serdeRespReadSnapshot("NoInputOutput")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.NoInputOutput(context.Background(), &NoInputOutputInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "NoInputOutput", err)
	}
}

func TestSerdeCheckResponseSnapshot_OperationWithDefaults(t *testing.T) {
	want := &OperationWithDefaultsOutput{
		DefaultString:  ptr.String("__DefaultString__"),
		DefaultBoolean: ptr.Bool(true),
		DefaultList: []string{
			"__Member__",
			"__Member__",
		},
		DefaultTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		DefaultBlob:      []byte("blob"),
		DefaultByte:      ptr.Int8(1),
		DefaultShort:     ptr.Int16(1),
		DefaultInteger:   ptr.Int32(1),
		DefaultLong:      ptr.Int64(1),
		DefaultFloat:     ptr.Float32(1.0),
		DefaultDouble:    ptr.Float64(1.0),
		DefaultMap: map[string]string{
			"key0": "__Value__",
		},
		DefaultEnum:    types.TestEnum("FOO"),
		DefaultIntEnum: types.TestIntEnum(1),
		EmptyString:    ptr.String("__EmptyString__"),
		FalseBoolean:   true,
		EmptyBlob:      []byte("blob"),
		ZeroByte:       1,
		ZeroShort:      1,
		ZeroInteger:    1,
		ZeroLong:       1,
		ZeroFloat:      1.0,
		ZeroDouble:     1.0,
	}
	status, header, body, err := serdeRespReadSnapshot("OperationWithDefaults")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.OperationWithDefaults(context.Background(), &OperationWithDefaultsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "OperationWithDefaults", err)
	}
}

func TestSerdeCheckResponseSnapshot_OptionalInputOutput(t *testing.T) {
	want := &OptionalInputOutputOutput{
		Value: ptr.String("__Value__"),
	}
	status, header, body, err := serdeRespReadSnapshot("OptionalInputOutput")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.OptionalInputOutput(context.Background(), &OptionalInputOutputInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "OptionalInputOutput", err)
	}
}

func TestSerdeCheckResponseSnapshot_RecursiveShapes(t *testing.T) {
	want := &RecursiveShapesOutput{
		Nested: &types.RecursiveShapesInputOutputNested1{
			Foo: ptr.String("__Foo__"),
			Nested: &types.RecursiveShapesInputOutputNested2{
				Bar:             ptr.String("__Bar__"),
				RecursiveMember: nil,
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("RecursiveShapes")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.RecursiveShapes(context.Background(), &RecursiveShapesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "RecursiveShapes", err)
	}
}

func TestSerdeCheckResponseSnapshot_RpcV2CborDenseMaps(t *testing.T) {
	want := &RpcV2CborDenseMapsOutput{
		DenseStructMap: map[string]types.GreetingStruct{
			"key0": {
				Hi: ptr.String("__Hi__"),
			},
		},
		DenseNumberMap: map[string]int32{
			"key0": 1,
		},
		DenseBooleanMap: map[string]bool{
			"key0": true,
		},
		DenseStringMap: map[string]string{
			"key0": "__Value__",
		},
		DenseSetMap: map[string][]string{
			"key0": {
				"__Member__",
				"__Member__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("RpcV2CborDenseMaps")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.RpcV2CborDenseMaps(context.Background(), &RpcV2CborDenseMapsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "RpcV2CborDenseMaps", err)
	}
}

func TestSerdeCheckResponseSnapshot_RpcV2CborLists(t *testing.T) {
	want := &RpcV2CborListsOutput{
		StringList: []string{
			"__Member__",
			"__Member__",
		},
		StringSet: []string{
			"__Member__",
			"__Member__",
		},
		IntegerList: []int32{
			1,
			1,
		},
		BooleanList: []bool{
			true,
			true,
		},
		TimestampList: []time.Time{
			time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
			time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC),
		},
		EnumList: []types.FooEnum{
			types.FooEnum("Foo"),
			types.FooEnum("Foo"),
		},
		IntEnumList: []types.IntegerEnum{
			types.IntegerEnum(1),
			types.IntegerEnum(1),
		},
		NestedStringList: [][]string{
			{
				"__Member__",
				"__Member__",
			},
			{
				"__Member__",
				"__Member__",
			},
		},
		StructureList: []types.StructureListMember{
			{
				A: ptr.String("__A__"),
				B: ptr.String("__B__"),
			},
			{
				A: ptr.String("__A__"),
				B: ptr.String("__B__"),
			},
		},
		BlobList: [][]byte{
			[]byte("blob"),
			[]byte("blob"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("RpcV2CborLists")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.RpcV2CborLists(context.Background(), &RpcV2CborListsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "RpcV2CborLists", err)
	}
}

func TestSerdeCheckResponseSnapshot_RpcV2CborSparseMaps(t *testing.T) {
	want := &RpcV2CborSparseMapsOutput{
		SparseStructMap: map[string]*types.GreetingStruct{
			"key0": {
				Hi: ptr.String("__Hi__"),
			},
		},
		SparseNumberMap: map[string]*int32{
			"key0": ptr.Int32(1),
		},
		SparseBooleanMap: map[string]*bool{
			"key0": ptr.Bool(true),
		},
		SparseStringMap: map[string]*string{
			"key0": ptr.String("__Value__"),
		},
		SparseSetMap: map[string][]string{
			"key0": {
				"__Member__",
				"__Member__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("RpcV2CborSparseMaps")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.RpcV2CborSparseMaps(context.Background(), &RpcV2CborSparseMapsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "RpcV2CborSparseMaps", err)
	}
}

func TestSerdeCheckResponseSnapshot_SimpleScalarProperties(t *testing.T) {
	want := &SimpleScalarPropertiesOutput{
		TrueBooleanValue:  ptr.Bool(true),
		FalseBooleanValue: ptr.Bool(true),
		ByteValue:         ptr.Int8(1),
		DoubleValue:       ptr.Float64(1.0),
		FloatValue:        ptr.Float32(1.0),
		IntegerValue:      ptr.Int32(1),
		LongValue:         ptr.Int64(1),
		ShortValue:        ptr.Int16(1),
		StringValue:       ptr.String("__StringValue__"),
		BlobValue:         []byte("blob"),
	}
	status, header, body, err := serdeRespReadSnapshot("SimpleScalarProperties")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.SimpleScalarProperties(context.Background(), &SimpleScalarPropertiesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "SimpleScalarProperties", err)
	}
}

func TestSerdeCheckResponseSnapshot_SparseNullsOperation(t *testing.T) {
	want := &SparseNullsOperationOutput{
		SparseStringList: []*string{
			ptr.String("__Member__"),
			ptr.String("__Member__"),
		},
		SparseStringMap: map[string]*string{
			"key0": ptr.String("__Value__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("SparseNullsOperation")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.SparseNullsOperation(context.Background(), &SparseNullsOperationInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "SparseNullsOperation", err)
	}
}
