// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package smithyrpcv2cborquerycompatible

import (
	"context"
	"errors"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cborquerycompatible/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/smithy-go/transport/http/protocol/rpcv2"
	"io"
	"io/fs"
	"net/http"
	"os"
	"slices"
	"strconv"
	"strings"
	"testing"
)

func serdeRespCreatePath(path string) (*os.File, error) {
	if err := os.MkdirAll(serdeRespSSPrefix, 0700); err != nil && !errors.Is(err, fs.ErrExist) {
		return nil, err
	}
	return os.Create(path)
}

func serdeRespWriteSnapshot(op string, status int, header http.Header, body []byte) error {
	f, err := serdeRespCreatePath(serdeRespSSPath(op))
	if err != nil {
		return err
	}
	defer f.Close()

	var sb strings.Builder
	sb.WriteString(strconv.Itoa(status))
	sb.WriteString("\n")
	keys := make([]string, 0, len(header))
	for k := range header {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	for _, k := range keys {
		for _, v := range header[k] {
			sb.WriteString(k)
			sb.WriteString(": ")
			sb.WriteString(v)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\n")
	sb.Write(body)
	_, err = f.WriteString(sb.String())
	return err
}
func TestSerdeUpdateResponseSnapshot_GetItem(t *testing.T) {
	want := &GetItemOutput{}
	proto := rpcv2.NewCBOR(schemas.RpcV2CborQueryCompatible)
	opSchema := smithy.NewOperationSchema(schemas.GetItem, schemas.GetItemOutput, schemas.GetItemOutput)
	req := smithyhttp.NewStackRequest().(*smithyhttp.Request)
	if err := proto.SerializeRequest(context.Background(), opSchema, want, req); err != nil {
		t.Fatal(err)
	}
	built := req.Build(context.Background())
	var body []byte
	if built.Body != nil {
		b, err := io.ReadAll(built.Body)
		if err != nil {
			t.Fatal(err)
		}
		body = b
	}
	if err := serdeRespWriteSnapshot("GetItem", 200, built.Header, body); err != nil {
		t.Fatal(err)
	}
}
