// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package comprehendmedical

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/comprehendmedical/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithytesting "github.com/aws/smithy-go/testing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

const serdeRespSSPrefix = "serde_response_snapshot"

func serdeRespSSPath(op string) string {
	return fmt.Sprintf("%s/%s.response.snap", serdeRespSSPrefix, op)
}

// serdeRespReadSnapshot parses a frozen wire response fixture: a status-code
// line, HTTP headers, a blank line, then the raw body.
func serdeRespReadSnapshot(op string) (int, http.Header, []byte, error) {
	raw, err := os.ReadFile(serdeRespSSPath(op))
	if err != nil {
		return 0, nil, nil, err
	}

	r := bufio.NewReader(bytes.NewReader(raw))
	statusLine, err := r.ReadString('\n')
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read status line: %w", err)
	}
	status, err := strconv.Atoi(strings.TrimSpace(statusLine))
	if err != nil {
		return 0, nil, nil, fmt.Errorf("parse status: %w", err)
	}

	header := http.Header{}
	for {
		line, err := r.ReadString('\n')
		if err != nil && err != io.EOF {
			return 0, nil, nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		k, v, ok := strings.Cut(trimmed, ": ")
		if !ok {
			return 0, nil, nil, fmt.Errorf("malformed header %q", trimmed)
		}
		header.Add(k, v)
		if err == io.EOF {
			break
		}
	}

	body, err := io.ReadAll(r)
	if err != nil {
		return 0, nil, nil, err
	}
	return status, header, body, nil
}

type serdeRespEndpointResolver struct{}

func (*serdeRespEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeRespClient(status int, header http.Header, body []byte) *Client {
	return New(Options{
		Region: "us-east-1",
		HTTPClient: smithyhttp.ClientDoFunc(func(req *http.Request) (*http.Response, error) {
			resp := &http.Response{StatusCode: status, Header: header, Request: req}
			if len(body) > 0 {
				resp.ContentLength = int64(len(body))
				resp.Body = io.NopCloser(bytes.NewReader(body))
			} else {
				resp.Body = http.NoBody
			}
			return resp, nil
		}),
		EndpointResolverV2: &serdeRespEndpointResolver{},
		APIOptions: []func(*middleware.Stack) error{
			func(s *middleware.Stack) error {
				s.Finalize.Clear()
				s.Initialize.Remove("OperationInputValidation")
				return nil
			},
		},
	})
}
func TestSerdeCheckResponseSnapshot_DescribeEntitiesDetectionV2Job(t *testing.T) {
	want := &DescribeEntitiesDetectionV2JobOutput{
		ComprehendMedicalAsyncJobProperties: &types.ComprehendMedicalAsyncJobProperties{
			JobId:          ptr.String("__JobId__"),
			JobName:        ptr.String("__JobName__"),
			JobStatus:      types.JobStatus("SUBMITTED"),
			Message:        ptr.String("__Message__"),
			SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			InputDataConfig: &types.InputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			OutputDataConfig: &types.OutputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			LanguageCode:      types.LanguageCode("en"),
			DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
			ManifestFilePath:  ptr.String("__ManifestFilePath__"),
			KMSKey:            ptr.String("__KMSKey__"),
			ModelVersion:      ptr.String("__ModelVersion__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeEntitiesDetectionV2Job")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeEntitiesDetectionV2Job(context.Background(), &DescribeEntitiesDetectionV2JobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeEntitiesDetectionV2Job", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeICD10CMInferenceJob(t *testing.T) {
	want := &DescribeICD10CMInferenceJobOutput{
		ComprehendMedicalAsyncJobProperties: &types.ComprehendMedicalAsyncJobProperties{
			JobId:          ptr.String("__JobId__"),
			JobName:        ptr.String("__JobName__"),
			JobStatus:      types.JobStatus("SUBMITTED"),
			Message:        ptr.String("__Message__"),
			SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			InputDataConfig: &types.InputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			OutputDataConfig: &types.OutputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			LanguageCode:      types.LanguageCode("en"),
			DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
			ManifestFilePath:  ptr.String("__ManifestFilePath__"),
			KMSKey:            ptr.String("__KMSKey__"),
			ModelVersion:      ptr.String("__ModelVersion__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeICD10CMInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeICD10CMInferenceJob(context.Background(), &DescribeICD10CMInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeICD10CMInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribePHIDetectionJob(t *testing.T) {
	want := &DescribePHIDetectionJobOutput{
		ComprehendMedicalAsyncJobProperties: &types.ComprehendMedicalAsyncJobProperties{
			JobId:          ptr.String("__JobId__"),
			JobName:        ptr.String("__JobName__"),
			JobStatus:      types.JobStatus("SUBMITTED"),
			Message:        ptr.String("__Message__"),
			SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			InputDataConfig: &types.InputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			OutputDataConfig: &types.OutputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			LanguageCode:      types.LanguageCode("en"),
			DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
			ManifestFilePath:  ptr.String("__ManifestFilePath__"),
			KMSKey:            ptr.String("__KMSKey__"),
			ModelVersion:      ptr.String("__ModelVersion__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribePHIDetectionJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribePHIDetectionJob(context.Background(), &DescribePHIDetectionJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribePHIDetectionJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeRxNormInferenceJob(t *testing.T) {
	want := &DescribeRxNormInferenceJobOutput{
		ComprehendMedicalAsyncJobProperties: &types.ComprehendMedicalAsyncJobProperties{
			JobId:          ptr.String("__JobId__"),
			JobName:        ptr.String("__JobName__"),
			JobStatus:      types.JobStatus("SUBMITTED"),
			Message:        ptr.String("__Message__"),
			SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			InputDataConfig: &types.InputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			OutputDataConfig: &types.OutputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			LanguageCode:      types.LanguageCode("en"),
			DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
			ManifestFilePath:  ptr.String("__ManifestFilePath__"),
			KMSKey:            ptr.String("__KMSKey__"),
			ModelVersion:      ptr.String("__ModelVersion__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeRxNormInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeRxNormInferenceJob(context.Background(), &DescribeRxNormInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeRxNormInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_DescribeSNOMEDCTInferenceJob(t *testing.T) {
	want := &DescribeSNOMEDCTInferenceJobOutput{
		ComprehendMedicalAsyncJobProperties: &types.ComprehendMedicalAsyncJobProperties{
			JobId:          ptr.String("__JobId__"),
			JobName:        ptr.String("__JobName__"),
			JobStatus:      types.JobStatus("SUBMITTED"),
			Message:        ptr.String("__Message__"),
			SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			InputDataConfig: &types.InputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			OutputDataConfig: &types.OutputDataConfig{
				S3Bucket: ptr.String("__S3Bucket__"),
				S3Key:    ptr.String("__S3Key__"),
			},
			LanguageCode:      types.LanguageCode("en"),
			DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
			ManifestFilePath:  ptr.String("__ManifestFilePath__"),
			KMSKey:            ptr.String("__KMSKey__"),
			ModelVersion:      ptr.String("__ModelVersion__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("DescribeSNOMEDCTInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DescribeSNOMEDCTInferenceJob(context.Background(), &DescribeSNOMEDCTInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DescribeSNOMEDCTInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_DetectEntities(t *testing.T) {
	want := &DetectEntitiesOutput{
		Entities: []types.Entity{
			{
				Id:          ptr.Int32(1),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Score:       ptr.Float32(1.0),
				Text:        ptr.String("__Text__"),
				Category:    types.EntityType("MEDICATION"),
				Type:        types.EntitySubType("NAME"),
				Traits: []types.Trait{
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
				},
				Attributes: []types.Attribute{
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
			},
			{
				Id:          ptr.Int32(1),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Score:       ptr.Float32(1.0),
				Text:        ptr.String("__Text__"),
				Category:    types.EntityType("MEDICATION"),
				Type:        types.EntitySubType("NAME"),
				Traits: []types.Trait{
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
				},
				Attributes: []types.Attribute{
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
			},
		},
		UnmappedAttributes: []types.UnmappedAttribute{
			{
				Type: types.EntityType("MEDICATION"),
				Attribute: &types.Attribute{
					Type:              types.EntitySubType("NAME"),
					Score:             ptr.Float32(1.0),
					RelationshipScore: ptr.Float32(1.0),
					RelationshipType:  types.RelationshipType("EVERY"),
					Id:                ptr.Int32(1),
					BeginOffset:       ptr.Int32(1),
					EndOffset:         ptr.Int32(1),
					Text:              ptr.String("__Text__"),
					Category:          types.EntityType("MEDICATION"),
					Traits: []types.Trait{
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
					},
				},
			},
			{
				Type: types.EntityType("MEDICATION"),
				Attribute: &types.Attribute{
					Type:              types.EntitySubType("NAME"),
					Score:             ptr.Float32(1.0),
					RelationshipScore: ptr.Float32(1.0),
					RelationshipType:  types.RelationshipType("EVERY"),
					Id:                ptr.Int32(1),
					BeginOffset:       ptr.Int32(1),
					EndOffset:         ptr.Int32(1),
					Text:              ptr.String("__Text__"),
					Category:          types.EntityType("MEDICATION"),
					Traits: []types.Trait{
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
					},
				},
			},
		},
		PaginationToken: ptr.String("__PaginationToken__"),
		ModelVersion:    ptr.String("__ModelVersion__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DetectEntities")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DetectEntities(context.Background(), &DetectEntitiesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DetectEntities", err)
	}
}

func TestSerdeCheckResponseSnapshot_DetectEntitiesV2(t *testing.T) {
	want := &DetectEntitiesV2Output{
		Entities: []types.Entity{
			{
				Id:          ptr.Int32(1),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Score:       ptr.Float32(1.0),
				Text:        ptr.String("__Text__"),
				Category:    types.EntityType("MEDICATION"),
				Type:        types.EntitySubType("NAME"),
				Traits: []types.Trait{
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
				},
				Attributes: []types.Attribute{
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
			},
			{
				Id:          ptr.Int32(1),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Score:       ptr.Float32(1.0),
				Text:        ptr.String("__Text__"),
				Category:    types.EntityType("MEDICATION"),
				Type:        types.EntitySubType("NAME"),
				Traits: []types.Trait{
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
				},
				Attributes: []types.Attribute{
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
			},
		},
		UnmappedAttributes: []types.UnmappedAttribute{
			{
				Type: types.EntityType("MEDICATION"),
				Attribute: &types.Attribute{
					Type:              types.EntitySubType("NAME"),
					Score:             ptr.Float32(1.0),
					RelationshipScore: ptr.Float32(1.0),
					RelationshipType:  types.RelationshipType("EVERY"),
					Id:                ptr.Int32(1),
					BeginOffset:       ptr.Int32(1),
					EndOffset:         ptr.Int32(1),
					Text:              ptr.String("__Text__"),
					Category:          types.EntityType("MEDICATION"),
					Traits: []types.Trait{
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
					},
				},
			},
			{
				Type: types.EntityType("MEDICATION"),
				Attribute: &types.Attribute{
					Type:              types.EntitySubType("NAME"),
					Score:             ptr.Float32(1.0),
					RelationshipScore: ptr.Float32(1.0),
					RelationshipType:  types.RelationshipType("EVERY"),
					Id:                ptr.Int32(1),
					BeginOffset:       ptr.Int32(1),
					EndOffset:         ptr.Int32(1),
					Text:              ptr.String("__Text__"),
					Category:          types.EntityType("MEDICATION"),
					Traits: []types.Trait{
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
						{
							Name:  types.AttributeName("SIGN"),
							Score: ptr.Float32(1.0),
						},
					},
				},
			},
		},
		PaginationToken: ptr.String("__PaginationToken__"),
		ModelVersion:    ptr.String("__ModelVersion__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DetectEntitiesV2")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DetectEntitiesV2(context.Background(), &DetectEntitiesV2Input{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DetectEntitiesV2", err)
	}
}

func TestSerdeCheckResponseSnapshot_DetectPHI(t *testing.T) {
	want := &DetectPHIOutput{
		Entities: []types.Entity{
			{
				Id:          ptr.Int32(1),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Score:       ptr.Float32(1.0),
				Text:        ptr.String("__Text__"),
				Category:    types.EntityType("MEDICATION"),
				Type:        types.EntitySubType("NAME"),
				Traits: []types.Trait{
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
				},
				Attributes: []types.Attribute{
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
			},
			{
				Id:          ptr.Int32(1),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Score:       ptr.Float32(1.0),
				Text:        ptr.String("__Text__"),
				Category:    types.EntityType("MEDICATION"),
				Type:        types.EntitySubType("NAME"),
				Traits: []types.Trait{
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.AttributeName("SIGN"),
						Score: ptr.Float32(1.0),
					},
				},
				Attributes: []types.Attribute{
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.EntitySubType("NAME"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.RelationshipType("EVERY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Category:          types.EntityType("MEDICATION"),
						Traits: []types.Trait{
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.AttributeName("SIGN"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
			},
		},
		PaginationToken: ptr.String("__PaginationToken__"),
		ModelVersion:    ptr.String("__ModelVersion__"),
	}
	status, header, body, err := serdeRespReadSnapshot("DetectPHI")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DetectPHI(context.Background(), &DetectPHIInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DetectPHI", err)
	}
}

func TestSerdeCheckResponseSnapshot_InferICD10CM(t *testing.T) {
	want := &InferICD10CMOutput{
		Entities: []types.ICD10CMEntity{
			{
				Id:          ptr.Int32(1),
				Text:        ptr.String("__Text__"),
				Category:    types.ICD10CMEntityCategory("MEDICAL_CONDITION"),
				Type:        types.ICD10CMEntityType("DX_NAME"),
				Score:       ptr.Float32(1.0),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Attributes: []types.ICD10CMAttribute{
					{
						Type:              types.ICD10CMAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.ICD10CMTrait{
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						Category:         types.ICD10CMEntityType("DX_NAME"),
						RelationshipType: types.ICD10CMRelationshipType("OVERLAP"),
					},
					{
						Type:              types.ICD10CMAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.ICD10CMTrait{
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						Category:         types.ICD10CMEntityType("DX_NAME"),
						RelationshipType: types.ICD10CMRelationshipType("OVERLAP"),
					},
				},
				Traits: []types.ICD10CMTrait{
					{
						Name:  types.ICD10CMTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.ICD10CMTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
				},
				ICD10CMConcepts: []types.ICD10CMConcept{
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
				},
			},
			{
				Id:          ptr.Int32(1),
				Text:        ptr.String("__Text__"),
				Category:    types.ICD10CMEntityCategory("MEDICAL_CONDITION"),
				Type:        types.ICD10CMEntityType("DX_NAME"),
				Score:       ptr.Float32(1.0),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Attributes: []types.ICD10CMAttribute{
					{
						Type:              types.ICD10CMAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.ICD10CMTrait{
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						Category:         types.ICD10CMEntityType("DX_NAME"),
						RelationshipType: types.ICD10CMRelationshipType("OVERLAP"),
					},
					{
						Type:              types.ICD10CMAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.ICD10CMTrait{
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.ICD10CMTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						Category:         types.ICD10CMEntityType("DX_NAME"),
						RelationshipType: types.ICD10CMRelationshipType("OVERLAP"),
					},
				},
				Traits: []types.ICD10CMTrait{
					{
						Name:  types.ICD10CMTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.ICD10CMTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
				},
				ICD10CMConcepts: []types.ICD10CMConcept{
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
				},
			},
		},
		PaginationToken: ptr.String("__PaginationToken__"),
		ModelVersion:    ptr.String("__ModelVersion__"),
	}
	status, header, body, err := serdeRespReadSnapshot("InferICD10CM")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.InferICD10CM(context.Background(), &InferICD10CMInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "InferICD10CM", err)
	}
}

func TestSerdeCheckResponseSnapshot_InferRxNorm(t *testing.T) {
	want := &InferRxNormOutput{
		Entities: []types.RxNormEntity{
			{
				Id:          ptr.Int32(1),
				Text:        ptr.String("__Text__"),
				Category:    types.RxNormEntityCategory("MEDICATION"),
				Type:        types.RxNormEntityType("BRAND_NAME"),
				Score:       ptr.Float32(1.0),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Attributes: []types.RxNormAttribute{
					{
						Type:              types.RxNormAttributeType("DOSAGE"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.RxNormTrait{
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.RxNormAttributeType("DOSAGE"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.RxNormTrait{
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
				Traits: []types.RxNormTrait{
					{
						Name:  types.RxNormTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.RxNormTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
				},
				RxNormConcepts: []types.RxNormConcept{
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
				},
			},
			{
				Id:          ptr.Int32(1),
				Text:        ptr.String("__Text__"),
				Category:    types.RxNormEntityCategory("MEDICATION"),
				Type:        types.RxNormEntityType("BRAND_NAME"),
				Score:       ptr.Float32(1.0),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Attributes: []types.RxNormAttribute{
					{
						Type:              types.RxNormAttributeType("DOSAGE"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.RxNormTrait{
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
					},
					{
						Type:              types.RxNormAttributeType("DOSAGE"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.RxNormTrait{
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.RxNormTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
					},
				},
				Traits: []types.RxNormTrait{
					{
						Name:  types.RxNormTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.RxNormTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
				},
				RxNormConcepts: []types.RxNormConcept{
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
				},
			},
		},
		PaginationToken: ptr.String("__PaginationToken__"),
		ModelVersion:    ptr.String("__ModelVersion__"),
	}
	status, header, body, err := serdeRespReadSnapshot("InferRxNorm")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.InferRxNorm(context.Background(), &InferRxNormInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "InferRxNorm", err)
	}
}

func TestSerdeCheckResponseSnapshot_InferSNOMEDCT(t *testing.T) {
	want := &InferSNOMEDCTOutput{
		Entities: []types.SNOMEDCTEntity{
			{
				Id:          ptr.Int32(1),
				Text:        ptr.String("__Text__"),
				Category:    types.SNOMEDCTEntityCategory("MEDICAL_CONDITION"),
				Type:        types.SNOMEDCTEntityType("DX_NAME"),
				Score:       ptr.Float32(1.0),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Attributes: []types.SNOMEDCTAttribute{
					{
						Category:          types.SNOMEDCTEntityCategory("MEDICAL_CONDITION"),
						Type:              types.SNOMEDCTAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.SNOMEDCTRelationshipType("ACUITY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.SNOMEDCTTrait{
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						SNOMEDCTConcepts: []types.SNOMEDCTConcept{
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
						},
					},
					{
						Category:          types.SNOMEDCTEntityCategory("MEDICAL_CONDITION"),
						Type:              types.SNOMEDCTAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.SNOMEDCTRelationshipType("ACUITY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.SNOMEDCTTrait{
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						SNOMEDCTConcepts: []types.SNOMEDCTConcept{
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
						},
					},
				},
				Traits: []types.SNOMEDCTTrait{
					{
						Name:  types.SNOMEDCTTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.SNOMEDCTTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
				},
				SNOMEDCTConcepts: []types.SNOMEDCTConcept{
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
				},
			},
			{
				Id:          ptr.Int32(1),
				Text:        ptr.String("__Text__"),
				Category:    types.SNOMEDCTEntityCategory("MEDICAL_CONDITION"),
				Type:        types.SNOMEDCTEntityType("DX_NAME"),
				Score:       ptr.Float32(1.0),
				BeginOffset: ptr.Int32(1),
				EndOffset:   ptr.Int32(1),
				Attributes: []types.SNOMEDCTAttribute{
					{
						Category:          types.SNOMEDCTEntityCategory("MEDICAL_CONDITION"),
						Type:              types.SNOMEDCTAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.SNOMEDCTRelationshipType("ACUITY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.SNOMEDCTTrait{
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						SNOMEDCTConcepts: []types.SNOMEDCTConcept{
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
						},
					},
					{
						Category:          types.SNOMEDCTEntityCategory("MEDICAL_CONDITION"),
						Type:              types.SNOMEDCTAttributeType("ACUITY"),
						Score:             ptr.Float32(1.0),
						RelationshipScore: ptr.Float32(1.0),
						RelationshipType:  types.SNOMEDCTRelationshipType("ACUITY"),
						Id:                ptr.Int32(1),
						BeginOffset:       ptr.Int32(1),
						EndOffset:         ptr.Int32(1),
						Text:              ptr.String("__Text__"),
						Traits: []types.SNOMEDCTTrait{
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
							{
								Name:  types.SNOMEDCTTraitName("NEGATION"),
								Score: ptr.Float32(1.0),
							},
						},
						SNOMEDCTConcepts: []types.SNOMEDCTConcept{
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
							{
								Description: ptr.String("__Description__"),
								Code:        ptr.String("__Code__"),
								Score:       ptr.Float32(1.0),
							},
						},
					},
				},
				Traits: []types.SNOMEDCTTrait{
					{
						Name:  types.SNOMEDCTTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
					{
						Name:  types.SNOMEDCTTraitName("NEGATION"),
						Score: ptr.Float32(1.0),
					},
				},
				SNOMEDCTConcepts: []types.SNOMEDCTConcept{
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
					{
						Description: ptr.String("__Description__"),
						Code:        ptr.String("__Code__"),
						Score:       ptr.Float32(1.0),
					},
				},
			},
		},
		PaginationToken: ptr.String("__PaginationToken__"),
		ModelVersion:    ptr.String("__ModelVersion__"),
		SNOMEDCTDetails: &types.SNOMEDCTDetails{
			Edition:     ptr.String("__Edition__"),
			Language:    ptr.String("__Language__"),
			VersionDate: ptr.String("__VersionDate__"),
		},
		Characters: &types.Characters{
			OriginalTextCharacters: ptr.Int32(1),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("InferSNOMEDCT")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.InferSNOMEDCT(context.Background(), &InferSNOMEDCTInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "InferSNOMEDCT", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListEntitiesDetectionV2Jobs(t *testing.T) {
	want := &ListEntitiesDetectionV2JobsOutput{
		ComprehendMedicalAsyncJobPropertiesList: []types.ComprehendMedicalAsyncJobProperties{
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListEntitiesDetectionV2Jobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListEntitiesDetectionV2Jobs(context.Background(), &ListEntitiesDetectionV2JobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListEntitiesDetectionV2Jobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListICD10CMInferenceJobs(t *testing.T) {
	want := &ListICD10CMInferenceJobsOutput{
		ComprehendMedicalAsyncJobPropertiesList: []types.ComprehendMedicalAsyncJobProperties{
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListICD10CMInferenceJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListICD10CMInferenceJobs(context.Background(), &ListICD10CMInferenceJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListICD10CMInferenceJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListPHIDetectionJobs(t *testing.T) {
	want := &ListPHIDetectionJobsOutput{
		ComprehendMedicalAsyncJobPropertiesList: []types.ComprehendMedicalAsyncJobProperties{
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListPHIDetectionJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListPHIDetectionJobs(context.Background(), &ListPHIDetectionJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListPHIDetectionJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListRxNormInferenceJobs(t *testing.T) {
	want := &ListRxNormInferenceJobsOutput{
		ComprehendMedicalAsyncJobPropertiesList: []types.ComprehendMedicalAsyncJobProperties{
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListRxNormInferenceJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListRxNormInferenceJobs(context.Background(), &ListRxNormInferenceJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListRxNormInferenceJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListSNOMEDCTInferenceJobs(t *testing.T) {
	want := &ListSNOMEDCTInferenceJobsOutput{
		ComprehendMedicalAsyncJobPropertiesList: []types.ComprehendMedicalAsyncJobProperties{
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
			{
				JobId:          ptr.String("__JobId__"),
				JobName:        ptr.String("__JobName__"),
				JobStatus:      types.JobStatus("SUBMITTED"),
				Message:        ptr.String("__Message__"),
				SubmitTime:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				EndTime:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				ExpirationTime: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				InputDataConfig: &types.InputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				OutputDataConfig: &types.OutputDataConfig{
					S3Bucket: ptr.String("__S3Bucket__"),
					S3Key:    ptr.String("__S3Key__"),
				},
				LanguageCode:      types.LanguageCode("en"),
				DataAccessRoleArn: ptr.String("__DataAccessRoleArn__"),
				ManifestFilePath:  ptr.String("__ManifestFilePath__"),
				KMSKey:            ptr.String("__KMSKey__"),
				ModelVersion:      ptr.String("__ModelVersion__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListSNOMEDCTInferenceJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListSNOMEDCTInferenceJobs(context.Background(), &ListSNOMEDCTInferenceJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListSNOMEDCTInferenceJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartEntitiesDetectionV2Job(t *testing.T) {
	want := &StartEntitiesDetectionV2JobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartEntitiesDetectionV2Job")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartEntitiesDetectionV2Job(context.Background(), &StartEntitiesDetectionV2JobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartEntitiesDetectionV2Job", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartICD10CMInferenceJob(t *testing.T) {
	want := &StartICD10CMInferenceJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartICD10CMInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartICD10CMInferenceJob(context.Background(), &StartICD10CMInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartICD10CMInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartPHIDetectionJob(t *testing.T) {
	want := &StartPHIDetectionJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartPHIDetectionJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartPHIDetectionJob(context.Background(), &StartPHIDetectionJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartPHIDetectionJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartRxNormInferenceJob(t *testing.T) {
	want := &StartRxNormInferenceJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartRxNormInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartRxNormInferenceJob(context.Background(), &StartRxNormInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartRxNormInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartSNOMEDCTInferenceJob(t *testing.T) {
	want := &StartSNOMEDCTInferenceJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartSNOMEDCTInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartSNOMEDCTInferenceJob(context.Background(), &StartSNOMEDCTInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartSNOMEDCTInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopEntitiesDetectionV2Job(t *testing.T) {
	want := &StopEntitiesDetectionV2JobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StopEntitiesDetectionV2Job")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopEntitiesDetectionV2Job(context.Background(), &StopEntitiesDetectionV2JobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopEntitiesDetectionV2Job", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopICD10CMInferenceJob(t *testing.T) {
	want := &StopICD10CMInferenceJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StopICD10CMInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopICD10CMInferenceJob(context.Background(), &StopICD10CMInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopICD10CMInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopPHIDetectionJob(t *testing.T) {
	want := &StopPHIDetectionJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StopPHIDetectionJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopPHIDetectionJob(context.Background(), &StopPHIDetectionJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopPHIDetectionJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopRxNormInferenceJob(t *testing.T) {
	want := &StopRxNormInferenceJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StopRxNormInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopRxNormInferenceJob(context.Background(), &StopRxNormInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopRxNormInferenceJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopSNOMEDCTInferenceJob(t *testing.T) {
	want := &StopSNOMEDCTInferenceJobOutput{
		JobId: ptr.String("__JobId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StopSNOMEDCTInferenceJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopSNOMEDCTInferenceJob(context.Background(), &StopSNOMEDCTInferenceJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopSNOMEDCTInferenceJob", err)
	}
}
