// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_response_snapshot

package mailmanager

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/mailmanager/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithytesting "github.com/aws/smithy-go/testing"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"
)

const serdeRespSSPrefix = "serde_response_snapshot"

func serdeRespSSPath(op string) string {
	return fmt.Sprintf("%s/%s.response.snap", serdeRespSSPrefix, op)
}

// serdeRespReadSnapshot parses a frozen wire response fixture: a status-code
// line, HTTP headers, a blank line, then the raw body.
func serdeRespReadSnapshot(op string) (int, http.Header, []byte, error) {
	raw, err := os.ReadFile(serdeRespSSPath(op))
	if err != nil {
		return 0, nil, nil, err
	}

	r := bufio.NewReader(bytes.NewReader(raw))
	statusLine, err := r.ReadString('\n')
	if err != nil {
		return 0, nil, nil, fmt.Errorf("read status line: %w", err)
	}
	status, err := strconv.Atoi(strings.TrimSpace(statusLine))
	if err != nil {
		return 0, nil, nil, fmt.Errorf("parse status: %w", err)
	}

	header := http.Header{}
	for {
		line, err := r.ReadString('\n')
		if err != nil && err != io.EOF {
			return 0, nil, nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		k, v, ok := strings.Cut(trimmed, ": ")
		if !ok {
			return 0, nil, nil, fmt.Errorf("malformed header %q", trimmed)
		}
		header.Add(k, v)
		if err == io.EOF {
			break
		}
	}

	body, err := io.ReadAll(r)
	if err != nil {
		return 0, nil, nil, err
	}
	return status, header, body, nil
}

type serdeRespEndpointResolver struct{}

func (*serdeRespEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeRespClient(status int, header http.Header, body []byte) *Client {
	return New(Options{
		Region: "us-east-1",
		HTTPClient: smithyhttp.ClientDoFunc(func(req *http.Request) (*http.Response, error) {
			resp := &http.Response{StatusCode: status, Header: header, Request: req}
			if len(body) > 0 {
				resp.ContentLength = int64(len(body))
				resp.Body = io.NopCloser(bytes.NewReader(body))
			} else {
				resp.Body = http.NoBody
			}
			return resp, nil
		}),
		EndpointResolverV2: &serdeRespEndpointResolver{},
		APIOptions: []func(*middleware.Stack) error{
			func(s *middleware.Stack) error {
				s.Finalize.Clear()
				s.Initialize.Remove("OperationInputValidation")
				return nil
			},
		},
	})
}
func TestSerdeCheckResponseSnapshot_CreateAddonInstance(t *testing.T) {
	want := &CreateAddonInstanceOutput{
		AddonInstanceId: ptr.String("__AddonInstanceId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateAddonInstance")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateAddonInstance(context.Background(), &CreateAddonInstanceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateAddonInstance", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateAddonSubscription(t *testing.T) {
	want := &CreateAddonSubscriptionOutput{
		AddonSubscriptionId: ptr.String("__AddonSubscriptionId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateAddonSubscription")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateAddonSubscription(context.Background(), &CreateAddonSubscriptionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateAddonSubscription", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateAddressList(t *testing.T) {
	want := &CreateAddressListOutput{
		AddressListId: ptr.String("__AddressListId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateAddressList(context.Background(), &CreateAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateAddressListImportJob(t *testing.T) {
	want := &CreateAddressListImportJobOutput{
		JobId:        ptr.String("__JobId__"),
		PreSignedUrl: ptr.String("__PreSignedUrl__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateAddressListImportJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateAddressListImportJob(context.Background(), &CreateAddressListImportJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateAddressListImportJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateArchive(t *testing.T) {
	want := &CreateArchiveOutput{
		ArchiveId: ptr.String("__ArchiveId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateArchive")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateArchive(context.Background(), &CreateArchiveInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateArchive", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateIngressPoint(t *testing.T) {
	want := &CreateIngressPointOutput{
		IngressPointId: ptr.String("__IngressPointId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateIngressPoint")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateIngressPoint(context.Background(), &CreateIngressPointInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateIngressPoint", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateRelay(t *testing.T) {
	want := &CreateRelayOutput{
		RelayId: ptr.String("__RelayId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateRelay")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateRelay(context.Background(), &CreateRelayInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateRelay", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateRuleSet(t *testing.T) {
	want := &CreateRuleSetOutput{
		RuleSetId: ptr.String("__RuleSetId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateRuleSet")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateRuleSet(context.Background(), &CreateRuleSetInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateRuleSet", err)
	}
}

func TestSerdeCheckResponseSnapshot_CreateTrafficPolicy(t *testing.T) {
	want := &CreateTrafficPolicyOutput{
		TrafficPolicyId: ptr.String("__TrafficPolicyId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("CreateTrafficPolicy")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.CreateTrafficPolicy(context.Background(), &CreateTrafficPolicyInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "CreateTrafficPolicy", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteAddonInstance(t *testing.T) {
	want := &DeleteAddonInstanceOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteAddonInstance")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteAddonInstance(context.Background(), &DeleteAddonInstanceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteAddonInstance", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteAddonSubscription(t *testing.T) {
	want := &DeleteAddonSubscriptionOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteAddonSubscription")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteAddonSubscription(context.Background(), &DeleteAddonSubscriptionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteAddonSubscription", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteAddressList(t *testing.T) {
	want := &DeleteAddressListOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteAddressList(context.Background(), &DeleteAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteArchive(t *testing.T) {
	want := &DeleteArchiveOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteArchive")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteArchive(context.Background(), &DeleteArchiveInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteArchive", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteIngressPoint(t *testing.T) {
	want := &DeleteIngressPointOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteIngressPoint")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteIngressPoint(context.Background(), &DeleteIngressPointInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteIngressPoint", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteRelay(t *testing.T) {
	want := &DeleteRelayOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteRelay")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteRelay(context.Background(), &DeleteRelayInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteRelay", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteRuleSet(t *testing.T) {
	want := &DeleteRuleSetOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteRuleSet")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteRuleSet(context.Background(), &DeleteRuleSetInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteRuleSet", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeleteTrafficPolicy(t *testing.T) {
	want := &DeleteTrafficPolicyOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeleteTrafficPolicy")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeleteTrafficPolicy(context.Background(), &DeleteTrafficPolicyInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeleteTrafficPolicy", err)
	}
}

func TestSerdeCheckResponseSnapshot_DeregisterMemberFromAddressList(t *testing.T) {
	want := &DeregisterMemberFromAddressListOutput{}
	status, header, body, err := serdeRespReadSnapshot("DeregisterMemberFromAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.DeregisterMemberFromAddressList(context.Background(), &DeregisterMemberFromAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "DeregisterMemberFromAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetAddonInstance(t *testing.T) {
	want := &GetAddonInstanceOutput{
		AddonSubscriptionId: ptr.String("__AddonSubscriptionId__"),
		AddonName:           ptr.String("__AddonName__"),
		AddonInstanceArn:    ptr.String("__AddonInstanceArn__"),
		CreatedTimestamp:    ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetAddonInstance")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetAddonInstance(context.Background(), &GetAddonInstanceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetAddonInstance", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetAddonSubscription(t *testing.T) {
	want := &GetAddonSubscriptionOutput{
		AddonName:            ptr.String("__AddonName__"),
		AddonSubscriptionArn: ptr.String("__AddonSubscriptionArn__"),
		CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetAddonSubscription")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetAddonSubscription(context.Background(), &GetAddonSubscriptionInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetAddonSubscription", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetAddressList(t *testing.T) {
	want := &GetAddressListOutput{
		AddressListId:        ptr.String("__AddressListId__"),
		AddressListArn:       ptr.String("__AddressListArn__"),
		AddressListName:      ptr.String("__AddressListName__"),
		CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetAddressList(context.Background(), &GetAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetAddressListImportJob(t *testing.T) {
	want := &GetAddressListImportJobOutput{
		JobId:              ptr.String("__JobId__"),
		Name:               ptr.String("__Name__"),
		Status:             types.ImportJobStatus("CREATED"),
		PreSignedUrl:       ptr.String("__PreSignedUrl__"),
		ImportedItemsCount: ptr.Int32(1),
		FailedItemsCount:   ptr.Int32(1),
		ImportDataFormat: &types.ImportDataFormat{
			ImportDataType: types.ImportDataType("CSV"),
		},
		AddressListId:      ptr.String("__AddressListId__"),
		CreatedTimestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		StartTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		CompletedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		Error:              ptr.String("__Error__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetAddressListImportJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetAddressListImportJob(context.Background(), &GetAddressListImportJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetAddressListImportJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetArchive(t *testing.T) {
	want := &GetArchiveOutput{
		ArchiveId:    ptr.String("__ArchiveId__"),
		ArchiveName:  ptr.String("__ArchiveName__"),
		ArchiveArn:   ptr.String("__ArchiveArn__"),
		ArchiveState: types.ArchiveState("ACTIVE"),
		Retention: &types.ArchiveRetentionMemberRetentionPeriod{
			Value: types.RetentionPeriod("THREE_MONTHS"),
		},
		CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		KmsKeyArn:            ptr.String("__KmsKeyArn__"),
	}
	status, header, body, err := serdeRespReadSnapshot("GetArchive")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetArchive(context.Background(), &GetArchiveInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetArchive", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetArchiveExport(t *testing.T) {
	want := &GetArchiveExportOutput{
		ArchiveId: ptr.String("__ArchiveId__"),
		Filters: &types.ArchiveFilters{
			Include: []types.ArchiveFilterCondition{
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
			},
			Unless: []types.ArchiveFilterCondition{
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
			},
		},
		FromTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		ToTimestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		MaxResults:    ptr.Int32(1),
		ExportDestinationConfiguration: &types.ExportDestinationConfigurationMemberS3{
			Value: types.S3ExportDestinationConfiguration{
				S3Location: ptr.String("__S3Location__"),
			},
		},
		Status: &types.ExportStatus{
			SubmissionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			CompletionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			State:               types.ExportState("QUEUED"),
			ErrorMessage:        ptr.String("__ErrorMessage__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetArchiveExport")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetArchiveExport(context.Background(), &GetArchiveExportInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetArchiveExport", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetArchiveMessage(t *testing.T) {
	want := &GetArchiveMessageOutput{
		MessageDownloadLink: ptr.String("__MessageDownloadLink__"),
		Metadata: &types.Metadata{
			Timestamp:        ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			IngressPointId:   ptr.String("__IngressPointId__"),
			TrafficPolicyId:  ptr.String("__TrafficPolicyId__"),
			RuleSetId:        ptr.String("__RuleSetId__"),
			SenderHostname:   ptr.String("__SenderHostname__"),
			SenderIpAddress:  ptr.String("__SenderIpAddress__"),
			TlsCipherSuite:   ptr.String("__TlsCipherSuite__"),
			TlsProtocol:      ptr.String("__TlsProtocol__"),
			SendingMethod:    ptr.String("__SendingMethod__"),
			SourceIdentity:   ptr.String("__SourceIdentity__"),
			SendingPool:      ptr.String("__SendingPool__"),
			ConfigurationSet: ptr.String("__ConfigurationSet__"),
			SourceArn:        ptr.String("__SourceArn__"),
		},
		Envelope: &types.Envelope{
			Helo: ptr.String("__Helo__"),
			From: ptr.String("__From__"),
			To: []string{
				"__Member__",
				"__Member__",
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetArchiveMessage")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetArchiveMessage(context.Background(), &GetArchiveMessageInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetArchiveMessage", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetArchiveMessageContent(t *testing.T) {
	want := &GetArchiveMessageContentOutput{
		Body: &types.MessageBody{
			Text:             ptr.String("__Text__"),
			Html:             ptr.String("__Html__"),
			MessageMalformed: ptr.Bool(true),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetArchiveMessageContent")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetArchiveMessageContent(context.Background(), &GetArchiveMessageContentInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetArchiveMessageContent", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetArchiveSearch(t *testing.T) {
	want := &GetArchiveSearchOutput{
		ArchiveId: ptr.String("__ArchiveId__"),
		Filters: &types.ArchiveFilters{
			Include: []types.ArchiveFilterCondition{
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
			},
			Unless: []types.ArchiveFilterCondition{
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
				&types.ArchiveFilterConditionMemberStringExpression{
					Value: types.ArchiveStringExpression{
						Evaluate: &types.ArchiveStringToEvaluateMemberAttribute{
							Value: types.ArchiveStringEmailAttribute("TO"),
						},
						Operator: types.ArchiveStringOperator("CONTAINS"),
						Values: []string{
							"__Member__",
							"__Member__",
						},
					},
				},
			},
		},
		FromTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		ToTimestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		MaxResults:    ptr.Int32(1),
		Status: &types.SearchStatus{
			SubmissionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			CompletionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			State:               types.SearchState("QUEUED"),
			ErrorMessage:        ptr.String("__ErrorMessage__"),
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetArchiveSearch")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetArchiveSearch(context.Background(), &GetArchiveSearchInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetArchiveSearch", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetArchiveSearchResults(t *testing.T) {
	want := &GetArchiveSearchResultsOutput{
		Rows: []types.Row{
			{
				ArchivedMessageId: ptr.String("__ArchivedMessageId__"),
				ReceivedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Date:              ptr.String("__Date__"),
				To:                ptr.String("__To__"),
				From:              ptr.String("__From__"),
				Cc:                ptr.String("__Cc__"),
				Subject:           ptr.String("__Subject__"),
				MessageId:         ptr.String("__MessageId__"),
				HasAttachments:    ptr.Bool(true),
				ReceivedHeaders: []string{
					"__Member__",
					"__Member__",
				},
				InReplyTo:       ptr.String("__InReplyTo__"),
				XMailer:         ptr.String("__XMailer__"),
				XOriginalMailer: ptr.String("__XOriginalMailer__"),
				XPriority:       ptr.String("__XPriority__"),
				IngressPointId:  ptr.String("__IngressPointId__"),
				SenderHostname:  ptr.String("__SenderHostname__"),
				SenderIpAddress: ptr.String("__SenderIpAddress__"),
				Envelope: &types.Envelope{
					Helo: ptr.String("__Helo__"),
					From: ptr.String("__From__"),
					To: []string{
						"__Member__",
						"__Member__",
					},
				},
				SourceArn: ptr.String("__SourceArn__"),
			},
			{
				ArchivedMessageId: ptr.String("__ArchivedMessageId__"),
				ReceivedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Date:              ptr.String("__Date__"),
				To:                ptr.String("__To__"),
				From:              ptr.String("__From__"),
				Cc:                ptr.String("__Cc__"),
				Subject:           ptr.String("__Subject__"),
				MessageId:         ptr.String("__MessageId__"),
				HasAttachments:    ptr.Bool(true),
				ReceivedHeaders: []string{
					"__Member__",
					"__Member__",
				},
				InReplyTo:       ptr.String("__InReplyTo__"),
				XMailer:         ptr.String("__XMailer__"),
				XOriginalMailer: ptr.String("__XOriginalMailer__"),
				XPriority:       ptr.String("__XPriority__"),
				IngressPointId:  ptr.String("__IngressPointId__"),
				SenderHostname:  ptr.String("__SenderHostname__"),
				SenderIpAddress: ptr.String("__SenderIpAddress__"),
				Envelope: &types.Envelope{
					Helo: ptr.String("__Helo__"),
					From: ptr.String("__From__"),
					To: []string{
						"__Member__",
						"__Member__",
					},
				},
				SourceArn: ptr.String("__SourceArn__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetArchiveSearchResults")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetArchiveSearchResults(context.Background(), &GetArchiveSearchResultsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetArchiveSearchResults", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetIngressPoint(t *testing.T) {
	want := &GetIngressPointOutput{
		IngressPointId:   ptr.String("__IngressPointId__"),
		IngressPointName: ptr.String("__IngressPointName__"),
		IngressPointArn:  ptr.String("__IngressPointArn__"),
		Status:           types.IngressPointStatus("PROVISIONING"),
		Type:             types.IngressPointType("OPEN"),
		ARecord:          ptr.String("__ARecord__"),
		RuleSetId:        ptr.String("__RuleSetId__"),
		TrafficPolicyId:  ptr.String("__TrafficPolicyId__"),
		IngressPointAuthConfiguration: &types.IngressPointAuthConfiguration{
			IngressPointPasswordConfiguration: &types.IngressPointPasswordConfiguration{
				SmtpPasswordVersion:                 ptr.String("__SmtpPasswordVersion__"),
				PreviousSmtpPasswordVersion:         ptr.String("__PreviousSmtpPasswordVersion__"),
				PreviousSmtpPasswordExpiryTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			SecretArn: ptr.String("__SecretArn__"),
			TlsAuthConfiguration: &types.TlsAuthConfiguration{
				TrustStore: &types.TrustStore{
					CAContent:  ptr.String("__CAContent__"),
					CrlContent: ptr.String("__CrlContent__"),
					KmsKeyArn:  ptr.String("__KmsKeyArn__"),
				},
			},
		},
		NetworkConfiguration: &types.NetworkConfigurationMemberPublicNetworkConfiguration{
			Value: types.PublicNetworkConfiguration{
				IpType: types.IpType("IPV4"),
			},
		},
		TlsPolicy:            types.TlsPolicy("REQUIRED"),
		CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetIngressPoint")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetIngressPoint(context.Background(), &GetIngressPointInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetIngressPoint", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetMemberOfAddressList(t *testing.T) {
	want := &GetMemberOfAddressListOutput{
		Address:          ptr.String("__Address__"),
		CreatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetMemberOfAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetMemberOfAddressList(context.Background(), &GetMemberOfAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetMemberOfAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetRelay(t *testing.T) {
	want := &GetRelayOutput{
		RelayId:    ptr.String("__RelayId__"),
		RelayArn:   ptr.String("__RelayArn__"),
		RelayName:  ptr.String("__RelayName__"),
		ServerName: ptr.String("__ServerName__"),
		ServerPort: ptr.Int32(1),
		Authentication: &types.RelayAuthenticationMemberSecretArn{
			Value: "__RelayAuthenticationMemberSecretArn__",
		},
		CreatedTimestamp:      ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastModifiedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetRelay")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetRelay(context.Background(), &GetRelayInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetRelay", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetRuleSet(t *testing.T) {
	want := &GetRuleSetOutput{
		RuleSetId:            ptr.String("__RuleSetId__"),
		RuleSetArn:           ptr.String("__RuleSetArn__"),
		RuleSetName:          ptr.String("__RuleSetName__"),
		CreatedDate:          ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastModificationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		Rules: []types.Rule{
			{
				Name: ptr.String("__Name__"),
				Conditions: []types.RuleCondition{
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
				},
				Unless: []types.RuleCondition{
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
				},
				Actions: []types.RuleAction{
					&types.RuleActionMemberDrop{
						Value: types.DropAction{},
					},
					&types.RuleActionMemberDrop{
						Value: types.DropAction{},
					},
				},
			},
			{
				Name: ptr.String("__Name__"),
				Conditions: []types.RuleCondition{
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
				},
				Unless: []types.RuleCondition{
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
					&types.RuleConditionMemberBooleanExpression{
						Value: types.RuleBooleanExpression{
							Evaluate: &types.RuleBooleanToEvaluateMemberAttribute{
								Value: types.RuleBooleanEmailAttribute("READ_RECEIPT_REQUESTED"),
							},
							Operator: types.RuleBooleanOperator("IS_TRUE"),
						},
					},
				},
				Actions: []types.RuleAction{
					&types.RuleActionMemberDrop{
						Value: types.DropAction{},
					},
					&types.RuleActionMemberDrop{
						Value: types.DropAction{},
					},
				},
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("GetRuleSet")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetRuleSet(context.Background(), &GetRuleSetInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetRuleSet", err)
	}
}

func TestSerdeCheckResponseSnapshot_GetTrafficPolicy(t *testing.T) {
	want := &GetTrafficPolicyOutput{
		TrafficPolicyName: ptr.String("__TrafficPolicyName__"),
		TrafficPolicyId:   ptr.String("__TrafficPolicyId__"),
		TrafficPolicyArn:  ptr.String("__TrafficPolicyArn__"),
		PolicyStatements: []types.PolicyStatement{
			{
				Conditions: []types.PolicyCondition{
					&types.PolicyConditionMemberStringExpression{
						Value: types.IngressStringExpression{
							Evaluate: &types.IngressStringToEvaluateMemberAttribute{
								Value: types.IngressStringEmailAttribute("RECIPIENT"),
							},
							Operator: types.IngressStringOperator("EQUALS"),
							Values: []string{
								"__Member__",
								"__Member__",
							},
						},
					},
					&types.PolicyConditionMemberStringExpression{
						Value: types.IngressStringExpression{
							Evaluate: &types.IngressStringToEvaluateMemberAttribute{
								Value: types.IngressStringEmailAttribute("RECIPIENT"),
							},
							Operator: types.IngressStringOperator("EQUALS"),
							Values: []string{
								"__Member__",
								"__Member__",
							},
						},
					},
				},
				Action: types.AcceptAction("ALLOW"),
			},
			{
				Conditions: []types.PolicyCondition{
					&types.PolicyConditionMemberStringExpression{
						Value: types.IngressStringExpression{
							Evaluate: &types.IngressStringToEvaluateMemberAttribute{
								Value: types.IngressStringEmailAttribute("RECIPIENT"),
							},
							Operator: types.IngressStringOperator("EQUALS"),
							Values: []string{
								"__Member__",
								"__Member__",
							},
						},
					},
					&types.PolicyConditionMemberStringExpression{
						Value: types.IngressStringExpression{
							Evaluate: &types.IngressStringToEvaluateMemberAttribute{
								Value: types.IngressStringEmailAttribute("RECIPIENT"),
							},
							Operator: types.IngressStringOperator("EQUALS"),
							Values: []string{
								"__Member__",
								"__Member__",
							},
						},
					},
				},
				Action: types.AcceptAction("ALLOW"),
			},
		},
		MaxMessageSizeBytes:  ptr.Int32(1),
		DefaultAction:        types.AcceptAction("ALLOW"),
		CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
		LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
	}
	status, header, body, err := serdeRespReadSnapshot("GetTrafficPolicy")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.GetTrafficPolicy(context.Background(), &GetTrafficPolicyInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "GetTrafficPolicy", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListAddonInstances(t *testing.T) {
	want := &ListAddonInstancesOutput{
		AddonInstances: []types.AddonInstance{
			{
				AddonInstanceId:     ptr.String("__AddonInstanceId__"),
				AddonSubscriptionId: ptr.String("__AddonSubscriptionId__"),
				AddonName:           ptr.String("__AddonName__"),
				AddonInstanceArn:    ptr.String("__AddonInstanceArn__"),
				CreatedTimestamp:    ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				AddonInstanceId:     ptr.String("__AddonInstanceId__"),
				AddonSubscriptionId: ptr.String("__AddonSubscriptionId__"),
				AddonName:           ptr.String("__AddonName__"),
				AddonInstanceArn:    ptr.String("__AddonInstanceArn__"),
				CreatedTimestamp:    ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListAddonInstances")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListAddonInstances(context.Background(), &ListAddonInstancesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListAddonInstances", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListAddonSubscriptions(t *testing.T) {
	want := &ListAddonSubscriptionsOutput{
		AddonSubscriptions: []types.AddonSubscription{
			{
				AddonSubscriptionId:  ptr.String("__AddonSubscriptionId__"),
				AddonName:            ptr.String("__AddonName__"),
				AddonSubscriptionArn: ptr.String("__AddonSubscriptionArn__"),
				CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				AddonSubscriptionId:  ptr.String("__AddonSubscriptionId__"),
				AddonName:            ptr.String("__AddonName__"),
				AddonSubscriptionArn: ptr.String("__AddonSubscriptionArn__"),
				CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListAddonSubscriptions")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListAddonSubscriptions(context.Background(), &ListAddonSubscriptionsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListAddonSubscriptions", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListAddressListImportJobs(t *testing.T) {
	want := &ListAddressListImportJobsOutput{
		ImportJobs: []types.ImportJob{
			{
				JobId:              ptr.String("__JobId__"),
				Name:               ptr.String("__Name__"),
				Status:             types.ImportJobStatus("CREATED"),
				PreSignedUrl:       ptr.String("__PreSignedUrl__"),
				ImportedItemsCount: ptr.Int32(1),
				FailedItemsCount:   ptr.Int32(1),
				ImportDataFormat: &types.ImportDataFormat{
					ImportDataType: types.ImportDataType("CSV"),
				},
				AddressListId:      ptr.String("__AddressListId__"),
				CreatedTimestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				StartTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				CompletedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Error:              ptr.String("__Error__"),
			},
			{
				JobId:              ptr.String("__JobId__"),
				Name:               ptr.String("__Name__"),
				Status:             types.ImportJobStatus("CREATED"),
				PreSignedUrl:       ptr.String("__PreSignedUrl__"),
				ImportedItemsCount: ptr.Int32(1),
				FailedItemsCount:   ptr.Int32(1),
				ImportDataFormat: &types.ImportDataFormat{
					ImportDataType: types.ImportDataType("CSV"),
				},
				AddressListId:      ptr.String("__AddressListId__"),
				CreatedTimestamp:   ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				StartTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				CompletedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				Error:              ptr.String("__Error__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListAddressListImportJobs")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListAddressListImportJobs(context.Background(), &ListAddressListImportJobsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListAddressListImportJobs", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListAddressLists(t *testing.T) {
	want := &ListAddressListsOutput{
		AddressLists: []types.AddressList{
			{
				AddressListId:        ptr.String("__AddressListId__"),
				AddressListArn:       ptr.String("__AddressListArn__"),
				AddressListName:      ptr.String("__AddressListName__"),
				CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				AddressListId:        ptr.String("__AddressListId__"),
				AddressListArn:       ptr.String("__AddressListArn__"),
				AddressListName:      ptr.String("__AddressListName__"),
				CreatedTimestamp:     ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
				LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListAddressLists")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListAddressLists(context.Background(), &ListAddressListsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListAddressLists", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListArchiveExports(t *testing.T) {
	want := &ListArchiveExportsOutput{
		Exports: []types.ExportSummary{
			{
				ExportId: ptr.String("__ExportId__"),
				Status: &types.ExportStatus{
					SubmissionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					CompletionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					State:               types.ExportState("QUEUED"),
					ErrorMessage:        ptr.String("__ErrorMessage__"),
				},
			},
			{
				ExportId: ptr.String("__ExportId__"),
				Status: &types.ExportStatus{
					SubmissionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					CompletionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					State:               types.ExportState("QUEUED"),
					ErrorMessage:        ptr.String("__ErrorMessage__"),
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListArchiveExports")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListArchiveExports(context.Background(), &ListArchiveExportsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListArchiveExports", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListArchives(t *testing.T) {
	want := &ListArchivesOutput{
		Archives: []types.Archive{
			{
				ArchiveId:            ptr.String("__ArchiveId__"),
				ArchiveName:          ptr.String("__ArchiveName__"),
				ArchiveState:         types.ArchiveState("ACTIVE"),
				LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				ArchiveId:            ptr.String("__ArchiveId__"),
				ArchiveName:          ptr.String("__ArchiveName__"),
				ArchiveState:         types.ArchiveState("ACTIVE"),
				LastUpdatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListArchives")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListArchives(context.Background(), &ListArchivesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListArchives", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListArchiveSearches(t *testing.T) {
	want := &ListArchiveSearchesOutput{
		Searches: []types.SearchSummary{
			{
				SearchId: ptr.String("__SearchId__"),
				Status: &types.SearchStatus{
					SubmissionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					CompletionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					State:               types.SearchState("QUEUED"),
					ErrorMessage:        ptr.String("__ErrorMessage__"),
				},
			},
			{
				SearchId: ptr.String("__SearchId__"),
				Status: &types.SearchStatus{
					SubmissionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					CompletionTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
					State:               types.SearchState("QUEUED"),
					ErrorMessage:        ptr.String("__ErrorMessage__"),
				},
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListArchiveSearches")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListArchiveSearches(context.Background(), &ListArchiveSearchesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListArchiveSearches", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListIngressPoints(t *testing.T) {
	want := &ListIngressPointsOutput{
		IngressPoints: []types.IngressPoint{
			{
				IngressPointName: ptr.String("__IngressPointName__"),
				IngressPointId:   ptr.String("__IngressPointId__"),
				Status:           types.IngressPointStatus("PROVISIONING"),
				Type:             types.IngressPointType("OPEN"),
				ARecord:          ptr.String("__ARecord__"),
			},
			{
				IngressPointName: ptr.String("__IngressPointName__"),
				IngressPointId:   ptr.String("__IngressPointId__"),
				Status:           types.IngressPointStatus("PROVISIONING"),
				Type:             types.IngressPointType("OPEN"),
				ARecord:          ptr.String("__ARecord__"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListIngressPoints")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListIngressPoints(context.Background(), &ListIngressPointsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListIngressPoints", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListMembersOfAddressList(t *testing.T) {
	want := &ListMembersOfAddressListOutput{
		Addresses: []types.SavedAddress{
			{
				Address:          ptr.String("__Address__"),
				CreatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				Address:          ptr.String("__Address__"),
				CreatedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListMembersOfAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListMembersOfAddressList(context.Background(), &ListMembersOfAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListMembersOfAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListRelays(t *testing.T) {
	want := &ListRelaysOutput{
		Relays: []types.Relay{
			{
				RelayId:               ptr.String("__RelayId__"),
				RelayName:             ptr.String("__RelayName__"),
				LastModifiedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				RelayId:               ptr.String("__RelayId__"),
				RelayName:             ptr.String("__RelayName__"),
				LastModifiedTimestamp: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListRelays")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListRelays(context.Background(), &ListRelaysInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListRelays", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListRuleSets(t *testing.T) {
	want := &ListRuleSetsOutput{
		RuleSets: []types.RuleSet{
			{
				RuleSetId:            ptr.String("__RuleSetId__"),
				RuleSetName:          ptr.String("__RuleSetName__"),
				LastModificationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
			{
				RuleSetId:            ptr.String("__RuleSetId__"),
				RuleSetName:          ptr.String("__RuleSetName__"),
				LastModificationDate: ptr.Time(time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListRuleSets")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListRuleSets(context.Background(), &ListRuleSetsInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListRuleSets", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListTagsForResource(t *testing.T) {
	want := &ListTagsForResourceOutput{
		Tags: []types.Tag{
			{
				Key:   ptr.String("__Key__"),
				Value: ptr.String("__Value__"),
			},
			{
				Key:   ptr.String("__Key__"),
				Value: ptr.String("__Value__"),
			},
		},
	}
	status, header, body, err := serdeRespReadSnapshot("ListTagsForResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListTagsForResource(context.Background(), &ListTagsForResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListTagsForResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_ListTrafficPolicies(t *testing.T) {
	want := &ListTrafficPoliciesOutput{
		TrafficPolicies: []types.TrafficPolicy{
			{
				TrafficPolicyName: ptr.String("__TrafficPolicyName__"),
				TrafficPolicyId:   ptr.String("__TrafficPolicyId__"),
				DefaultAction:     types.AcceptAction("ALLOW"),
			},
			{
				TrafficPolicyName: ptr.String("__TrafficPolicyName__"),
				TrafficPolicyId:   ptr.String("__TrafficPolicyId__"),
				DefaultAction:     types.AcceptAction("ALLOW"),
			},
		},
		NextToken: ptr.String("__NextToken__"),
	}
	status, header, body, err := serdeRespReadSnapshot("ListTrafficPolicies")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.ListTrafficPolicies(context.Background(), &ListTrafficPoliciesInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "ListTrafficPolicies", err)
	}
}

func TestSerdeCheckResponseSnapshot_RegisterMemberToAddressList(t *testing.T) {
	want := &RegisterMemberToAddressListOutput{}
	status, header, body, err := serdeRespReadSnapshot("RegisterMemberToAddressList")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.RegisterMemberToAddressList(context.Background(), &RegisterMemberToAddressListInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "RegisterMemberToAddressList", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartAddressListImportJob(t *testing.T) {
	want := &StartAddressListImportJobOutput{}
	status, header, body, err := serdeRespReadSnapshot("StartAddressListImportJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartAddressListImportJob(context.Background(), &StartAddressListImportJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartAddressListImportJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartArchiveExport(t *testing.T) {
	want := &StartArchiveExportOutput{
		ExportId: ptr.String("__ExportId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartArchiveExport")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartArchiveExport(context.Background(), &StartArchiveExportInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartArchiveExport", err)
	}
}

func TestSerdeCheckResponseSnapshot_StartArchiveSearch(t *testing.T) {
	want := &StartArchiveSearchOutput{
		SearchId: ptr.String("__SearchId__"),
	}
	status, header, body, err := serdeRespReadSnapshot("StartArchiveSearch")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StartArchiveSearch(context.Background(), &StartArchiveSearchInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StartArchiveSearch", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopAddressListImportJob(t *testing.T) {
	want := &StopAddressListImportJobOutput{}
	status, header, body, err := serdeRespReadSnapshot("StopAddressListImportJob")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopAddressListImportJob(context.Background(), &StopAddressListImportJobInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopAddressListImportJob", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopArchiveExport(t *testing.T) {
	want := &StopArchiveExportOutput{}
	status, header, body, err := serdeRespReadSnapshot("StopArchiveExport")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopArchiveExport(context.Background(), &StopArchiveExportInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopArchiveExport", err)
	}
}

func TestSerdeCheckResponseSnapshot_StopArchiveSearch(t *testing.T) {
	want := &StopArchiveSearchOutput{}
	status, header, body, err := serdeRespReadSnapshot("StopArchiveSearch")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.StopArchiveSearch(context.Background(), &StopArchiveSearchInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "StopArchiveSearch", err)
	}
}

func TestSerdeCheckResponseSnapshot_TagResource(t *testing.T) {
	want := &TagResourceOutput{}
	status, header, body, err := serdeRespReadSnapshot("TagResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.TagResource(context.Background(), &TagResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "TagResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_UntagResource(t *testing.T) {
	want := &UntagResourceOutput{}
	status, header, body, err := serdeRespReadSnapshot("UntagResource")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UntagResource(context.Background(), &UntagResourceInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UntagResource", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateArchive(t *testing.T) {
	want := &UpdateArchiveOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateArchive")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateArchive(context.Background(), &UpdateArchiveInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateArchive", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateIngressPoint(t *testing.T) {
	want := &UpdateIngressPointOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateIngressPoint")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateIngressPoint(context.Background(), &UpdateIngressPointInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateIngressPoint", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateRelay(t *testing.T) {
	want := &UpdateRelayOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateRelay")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateRelay(context.Background(), &UpdateRelayInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateRelay", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateRuleSet(t *testing.T) {
	want := &UpdateRuleSetOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateRuleSet")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateRuleSet(context.Background(), &UpdateRuleSetInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateRuleSet", err)
	}
}

func TestSerdeCheckResponseSnapshot_UpdateTrafficPolicy(t *testing.T) {
	want := &UpdateTrafficPolicyOutput{}
	status, header, body, err := serdeRespReadSnapshot("UpdateTrafficPolicy")
	if errors.Is(err, fs.ErrNotExist) {
		t.Skip("no response snapshot fixture")
	}
	if err != nil {
		t.Fatal(err)
	}
	svc := serdeRespClient(status, header, body)
	got, err := svc.UpdateTrafficPolicy(context.Background(), &UpdateTrafficPolicyInput{})
	if err != nil {
		t.Fatal(err)
	}
	if err := smithytesting.CompareValues(want, got); err != nil {
		t.Errorf("response snapshot mismatch for %s: %v", "UpdateTrafficPolicy", err)
	}
}
