// Code generated by smithy-go-codegen DO NOT EDIT.

//go:build serde_snapshot

package panorama

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/aws/aws-sdk-go-v2/service/panorama/types"
	smithyendpoints "github.com/aws/smithy-go/endpoints"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/smithy-go/ptr"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"io"
	"io/fs"
	"net/url"
	"os"
	"slices"
	"strings"
	"testing"
)

const serdeSSPrefix = "serde_snapshot"

type serdeSnapshotOK struct{}

func (serdeSnapshotOK) Error() string { return "error: success" }

func serdeCreatePath(path string) (*os.File, error) {
	if err := os.MkdirAll(serdeSSPrefix, 0700); err != nil && !errors.Is(err, fs.ErrExist) {
		return nil, err
	}
	return os.Create(path)
}

func serdeSSPath(op string) string {
	return fmt.Sprintf("%s/%s.request.snap", serdeSSPrefix, op)
}

type captureSerdeRequestMiddleware struct {
	body     *bytes.Buffer
	method   *string
	rawPath  *string
	rawQuery *string
	header   *map[string][]string
}

func (*captureSerdeRequestMiddleware) ID() string { return "captureSerdeRequest" }

func (m *captureSerdeRequestMiddleware) HandleFinalize(
	ctx context.Context, input middleware.FinalizeInput, next middleware.FinalizeHandler,
) (
	middleware.FinalizeOutput, middleware.Metadata, error,
) {
	req, ok := input.Request.(*smithyhttp.Request)
	if !ok {
		return middleware.FinalizeOutput{}, middleware.Metadata{}, fmt.Errorf("unexpected transport type %T", input.Request)
	}

	built := req.Build(ctx)
	*m.method = built.Method
	*m.rawPath = built.URL.RawPath
	if *m.rawPath == "" {
		*m.rawPath = built.URL.Path
	}
	*m.rawQuery = built.URL.RawQuery
	*m.header = built.Header

	if built.Body != nil {
		if _, err := io.Copy(m.body, built.Body); err != nil {
			return middleware.FinalizeOutput{}, middleware.Metadata{}, err
		}
	}

	return middleware.FinalizeOutput{}, middleware.Metadata{}, serdeSnapshotOK{}
}

func serdeFormatRequest(method, rawPath, rawQuery string, header map[string][]string, body []byte) string {
	skipHeaders := map[string]bool{
		"Authorization":         true,
		"User-Agent":            true,
		"X-Amz-Date":            true,
		"X-Amz-Security-Token":  true,
		"Amz-Sdk-Invocation-Id": true,
		"Amz-Sdk-Request":       true,
	}

	var sb strings.Builder
	sb.WriteString(method)
	sb.WriteString(" ")
	sb.WriteString(rawPath)
	if rawQuery != "" {
		sb.WriteString("?")
		sb.WriteString(rawQuery)
	}
	sb.WriteString("\n\n")

	keys := make([]string, 0, len(header))
	for k := range header {
		if skipHeaders[k] {
			continue
		}
		keys = append(keys, k)
	}
	slices.Sort(keys)
	for _, k := range keys {
		for _, v := range header[k] {
			sb.WriteString(k)
			sb.WriteString(": ")
			sb.WriteString(v)
			sb.WriteString("\n")
		}
	}
	sb.WriteString("\n")
	if len(body) > 0 {
		var v interface{}
		if err := json.Unmarshal(body, &v); err == nil {
			if sorted, err := json.Marshal(v); err == nil {
				sb.Write(sorted)
			}
		}
	}
	return sb.String()
}

func serdeUpdateSnapshot(method, rawPath, rawQuery string, header map[string][]string, body []byte, operation string) error {
	content := serdeFormatRequest(method, rawPath, rawQuery, header, body)
	f, err := serdeCreatePath(serdeSSPath(operation))
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := f.Write([]byte(content)); err != nil {
		return err
	}
	return serdeSnapshotOK{}
}

func serdeTestSnapshot(method, rawPath, rawQuery string, header map[string][]string, body []byte, operation string) error {
	content := serdeFormatRequest(method, rawPath, rawQuery, header, body)
	f, err := os.Open(serdeSSPath(operation))
	if errors.Is(err, fs.ErrNotExist) {
		return serdeSnapshotOK{}
	}
	if err != nil {
		return err
	}
	defer f.Close()
	expected, err := io.ReadAll(f)
	if err != nil {
		return err
	}
	if content != string(expected) {
		return fmt.Errorf("serde snapshot mismatch for %s:\nGOT:\n%s:\nEXPECTED:\n%s", operation, content, string(expected))
	}
	return serdeSnapshotOK{}
}

type serdeEndpointResolver struct{}

func (*serdeEndpointResolver) ResolveEndpoint(ctx context.Context, params EndpointParameters) (smithyendpoints.Endpoint, error) {
	return smithyendpoints.Endpoint{URI: url.URL{Scheme: "https", Host: "test.example.com"}}, nil
}

func serdeNewClient() *Client {
	return New(Options{
		Region:             "us-east-1",
		EndpointResolverV2: &serdeEndpointResolver{},
	})
}
func TestSerdeCheckSnapshot_CreateApplicationInstance(t *testing.T) {
	input := &CreateApplicationInstanceInput{
		Name:        ptr.String("__Name__"),
		Description: ptr.String("__Description__"),
		ManifestPayload: &types.ManifestPayloadMemberPayloadData{
			Value: "__ManifestPayloadMemberPayloadData__",
		},
		ManifestOverridesPayload: &types.ManifestOverridesPayloadMemberPayloadData{
			Value: "__ManifestOverridesPayloadMemberPayloadData__",
		},
		ApplicationInstanceIdToReplace: ptr.String("__ApplicationInstanceIdToReplace__"),
		RuntimeRoleArn:                 ptr.String("__RuntimeRoleArn__"),
		DefaultRuntimeContextDevice:    ptr.String("__DefaultRuntimeContextDevice__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreateApplicationInstance(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreateApplicationInstance"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_CreateJobForDevices(t *testing.T) {
	input := &CreateJobForDevicesInput{
		DeviceIds: []string{
			"__Member__",
			"__Member__",
		},
		DeviceJobConfig: &types.DeviceJobConfig{
			OTAJobConfig: &types.OTAJobConfig{
				ImageVersion:            ptr.String("__ImageVersion__"),
				AllowMajorVersionUpdate: true,
			},
		},
		JobType: types.JobType("OTA"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreateJobForDevices(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreateJobForDevices"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_CreateNodeFromTemplateJob(t *testing.T) {
	input := &CreateNodeFromTemplateJobInput{
		TemplateType:         types.TemplateType("RTSP_CAMERA_STREAM"),
		OutputPackageName:    ptr.String("__OutputPackageName__"),
		OutputPackageVersion: ptr.String("__OutputPackageVersion__"),
		NodeName:             ptr.String("__NodeName__"),
		NodeDescription:      ptr.String("__NodeDescription__"),
		TemplateParameters: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
		JobTags: []types.JobResourceTags{
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreateNodeFromTemplateJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreateNodeFromTemplateJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_CreatePackage(t *testing.T) {
	input := &CreatePackageInput{
		PackageName: ptr.String("__PackageName__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreatePackage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreatePackage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_CreatePackageImportJob(t *testing.T) {
	input := &CreatePackageImportJobInput{
		JobType: types.PackageImportJobType("NODE_PACKAGE_VERSION"),
		InputConfig: &types.PackageImportJobInputConfig{
			PackageVersionInputConfig: &types.PackageVersionInputConfig{
				S3Location: &types.S3Location{
					Region:     ptr.String("__Region__"),
					BucketName: ptr.String("__BucketName__"),
					ObjectKey:  ptr.String("__ObjectKey__"),
				},
			},
		},
		OutputConfig: &types.PackageImportJobOutputConfig{
			PackageVersionOutputConfig: &types.PackageVersionOutputConfig{
				PackageName:    ptr.String("__PackageName__"),
				PackageVersion: ptr.String("__PackageVersion__"),
				MarkLatest:     true,
			},
		},
		ClientToken: ptr.String("__ClientToken__"),
		JobTags: []types.JobResourceTags{
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreatePackageImportJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreatePackageImportJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DeleteDevice(t *testing.T) {
	input := &DeleteDeviceInput{
		DeviceId: ptr.String("__DeviceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DeleteDevice(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DeleteDevice"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DeletePackage(t *testing.T) {
	input := &DeletePackageInput{
		PackageId:   ptr.String("__PackageId__"),
		ForceDelete: true,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DeletePackage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DeletePackage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DeregisterPackageVersion(t *testing.T) {
	input := &DeregisterPackageVersionInput{
		OwnerAccount:              ptr.String("__OwnerAccount__"),
		PackageId:                 ptr.String("__PackageId__"),
		PackageVersion:            ptr.String("__PackageVersion__"),
		PatchVersion:              ptr.String("__PatchVersion__"),
		UpdatedLatestPatchVersion: ptr.String("__UpdatedLatestPatchVersion__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DeregisterPackageVersion(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DeregisterPackageVersion"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeApplicationInstance(t *testing.T) {
	input := &DescribeApplicationInstanceInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeApplicationInstance(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeApplicationInstance"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeApplicationInstanceDetails(t *testing.T) {
	input := &DescribeApplicationInstanceDetailsInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeApplicationInstanceDetails(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeApplicationInstanceDetails"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeDevice(t *testing.T) {
	input := &DescribeDeviceInput{
		DeviceId: ptr.String("__DeviceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeDevice(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeDevice"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeDeviceJob(t *testing.T) {
	input := &DescribeDeviceJobInput{
		JobId: ptr.String("__JobId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeDeviceJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeDeviceJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeNode(t *testing.T) {
	input := &DescribeNodeInput{
		NodeId:       ptr.String("__NodeId__"),
		OwnerAccount: ptr.String("__OwnerAccount__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeNode(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeNode"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribeNodeFromTemplateJob(t *testing.T) {
	input := &DescribeNodeFromTemplateJobInput{
		JobId: ptr.String("__JobId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeNodeFromTemplateJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeNodeFromTemplateJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribePackage(t *testing.T) {
	input := &DescribePackageInput{
		PackageId: ptr.String("__PackageId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribePackage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribePackage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribePackageImportJob(t *testing.T) {
	input := &DescribePackageImportJobInput{
		JobId: ptr.String("__JobId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribePackageImportJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribePackageImportJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_DescribePackageVersion(t *testing.T) {
	input := &DescribePackageVersionInput{
		OwnerAccount:   ptr.String("__OwnerAccount__"),
		PackageId:      ptr.String("__PackageId__"),
		PackageVersion: ptr.String("__PackageVersion__"),
		PatchVersion:   ptr.String("__PatchVersion__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribePackageVersion(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribePackageVersion"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListApplicationInstanceDependencies(t *testing.T) {
	input := &ListApplicationInstanceDependenciesInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
		MaxResults:            1,
		NextToken:             ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListApplicationInstanceDependencies(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListApplicationInstanceDependencies"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListApplicationInstanceNodeInstances(t *testing.T) {
	input := &ListApplicationInstanceNodeInstancesInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
		MaxResults:            1,
		NextToken:             ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListApplicationInstanceNodeInstances(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListApplicationInstanceNodeInstances"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListApplicationInstances(t *testing.T) {
	input := &ListApplicationInstancesInput{
		DeviceId:     ptr.String("__DeviceId__"),
		StatusFilter: types.StatusFilter("DEPLOYMENT_SUCCEEDED"),
		MaxResults:   1,
		NextToken:    ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListApplicationInstances(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListApplicationInstances"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListDevices(t *testing.T) {
	input := &ListDevicesInput{
		NextToken:                    ptr.String("__NextToken__"),
		MaxResults:                   1,
		SortBy:                       types.ListDevicesSortBy("DEVICE_ID"),
		SortOrder:                    types.SortOrder("ASCENDING"),
		NameFilter:                   ptr.String("__NameFilter__"),
		DeviceAggregatedStatusFilter: types.DeviceAggregatedStatus("ERROR"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListDevices(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListDevices"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListDevicesJobs(t *testing.T) {
	input := &ListDevicesJobsInput{
		DeviceId:   ptr.String("__DeviceId__"),
		NextToken:  ptr.String("__NextToken__"),
		MaxResults: 1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListDevicesJobs(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListDevicesJobs"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListNodeFromTemplateJobs(t *testing.T) {
	input := &ListNodeFromTemplateJobsInput{
		NextToken:  ptr.String("__NextToken__"),
		MaxResults: 1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListNodeFromTemplateJobs(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListNodeFromTemplateJobs"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListNodes(t *testing.T) {
	input := &ListNodesInput{
		Category:       types.NodeCategory("BUSINESS_LOGIC"),
		OwnerAccount:   ptr.String("__OwnerAccount__"),
		PackageName:    ptr.String("__PackageName__"),
		PackageVersion: ptr.String("__PackageVersion__"),
		PatchVersion:   ptr.String("__PatchVersion__"),
		NextToken:      ptr.String("__NextToken__"),
		MaxResults:     1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListNodes(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListNodes"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListPackageImportJobs(t *testing.T) {
	input := &ListPackageImportJobsInput{
		NextToken:  ptr.String("__NextToken__"),
		MaxResults: 1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListPackageImportJobs(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListPackageImportJobs"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListPackages(t *testing.T) {
	input := &ListPackagesInput{
		MaxResults: 1,
		NextToken:  ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListPackages(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListPackages"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ListTagsForResource(t *testing.T) {
	input := &ListTagsForResourceInput{
		ResourceArn: ptr.String("__ResourceArn__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListTagsForResource(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListTagsForResource"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_ProvisionDevice(t *testing.T) {
	input := &ProvisionDeviceInput{
		Name:        ptr.String("__Name__"),
		Description: ptr.String("__Description__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
		NetworkingConfiguration: &types.NetworkPayload{
			Ethernet0: &types.EthernetPayload{
				ConnectionType: types.ConnectionType("STATIC_IP"),
				StaticIpConnectionInfo: &types.StaticIpConnectionInfo{
					IpAddress: ptr.String("__IpAddress__"),
					Mask:      ptr.String("__Mask__"),
					Dns: []string{
						"__Member__",
						"__Member__",
					},
					DefaultGateway: ptr.String("__DefaultGateway__"),
				},
			},
			Ethernet1: &types.EthernetPayload{
				ConnectionType: types.ConnectionType("STATIC_IP"),
				StaticIpConnectionInfo: &types.StaticIpConnectionInfo{
					IpAddress: ptr.String("__IpAddress__"),
					Mask:      ptr.String("__Mask__"),
					Dns: []string{
						"__Member__",
						"__Member__",
					},
					DefaultGateway: ptr.String("__DefaultGateway__"),
				},
			},
			Ntp: &types.NtpPayload{
				NtpServers: []string{
					"__Member__",
					"__Member__",
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ProvisionDevice(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ProvisionDevice"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_RegisterPackageVersion(t *testing.T) {
	input := &RegisterPackageVersionInput{
		OwnerAccount:   ptr.String("__OwnerAccount__"),
		PackageId:      ptr.String("__PackageId__"),
		PackageVersion: ptr.String("__PackageVersion__"),
		PatchVersion:   ptr.String("__PatchVersion__"),
		MarkLatest:     true,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.RegisterPackageVersion(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "RegisterPackageVersion"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_RemoveApplicationInstance(t *testing.T) {
	input := &RemoveApplicationInstanceInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.RemoveApplicationInstance(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "RemoveApplicationInstance"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_SignalApplicationInstanceNodeInstances(t *testing.T) {
	input := &SignalApplicationInstanceNodeInstancesInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
		NodeSignals: []types.NodeSignal{
			{
				NodeInstanceId: ptr.String("__NodeInstanceId__"),
				Signal:         types.NodeSignalValue("PAUSE"),
			},
			{
				NodeInstanceId: ptr.String("__NodeInstanceId__"),
				Signal:         types.NodeSignalValue("PAUSE"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.SignalApplicationInstanceNodeInstances(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "SignalApplicationInstanceNodeInstances"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_TagResource(t *testing.T) {
	input := &TagResourceInput{
		ResourceArn: ptr.String("__ResourceArn__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.TagResource(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "TagResource"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_UntagResource(t *testing.T) {
	input := &UntagResourceInput{
		ResourceArn: ptr.String("__ResourceArn__"),
		TagKeys: []string{
			"__Member__",
			"__Member__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.UntagResource(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "UntagResource"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeCheckSnapshot_UpdateDeviceMetadata(t *testing.T) {
	input := &UpdateDeviceMetadataInput{
		DeviceId:    ptr.String("__DeviceId__"),
		Description: ptr.String("__Description__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.UpdateDeviceMetadata(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeTestSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "UpdateDeviceMetadata"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}
func TestSerdeUpdateSnapshot_CreateApplicationInstance(t *testing.T) {
	input := &CreateApplicationInstanceInput{
		Name:        ptr.String("__Name__"),
		Description: ptr.String("__Description__"),
		ManifestPayload: &types.ManifestPayloadMemberPayloadData{
			Value: "__ManifestPayloadMemberPayloadData__",
		},
		ManifestOverridesPayload: &types.ManifestOverridesPayloadMemberPayloadData{
			Value: "__ManifestOverridesPayloadMemberPayloadData__",
		},
		ApplicationInstanceIdToReplace: ptr.String("__ApplicationInstanceIdToReplace__"),
		RuntimeRoleArn:                 ptr.String("__RuntimeRoleArn__"),
		DefaultRuntimeContextDevice:    ptr.String("__DefaultRuntimeContextDevice__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreateApplicationInstance(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreateApplicationInstance"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_CreateJobForDevices(t *testing.T) {
	input := &CreateJobForDevicesInput{
		DeviceIds: []string{
			"__Member__",
			"__Member__",
		},
		DeviceJobConfig: &types.DeviceJobConfig{
			OTAJobConfig: &types.OTAJobConfig{
				ImageVersion:            ptr.String("__ImageVersion__"),
				AllowMajorVersionUpdate: true,
			},
		},
		JobType: types.JobType("OTA"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreateJobForDevices(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreateJobForDevices"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_CreateNodeFromTemplateJob(t *testing.T) {
	input := &CreateNodeFromTemplateJobInput{
		TemplateType:         types.TemplateType("RTSP_CAMERA_STREAM"),
		OutputPackageName:    ptr.String("__OutputPackageName__"),
		OutputPackageVersion: ptr.String("__OutputPackageVersion__"),
		NodeName:             ptr.String("__NodeName__"),
		NodeDescription:      ptr.String("__NodeDescription__"),
		TemplateParameters: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
		JobTags: []types.JobResourceTags{
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreateNodeFromTemplateJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreateNodeFromTemplateJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_CreatePackage(t *testing.T) {
	input := &CreatePackageInput{
		PackageName: ptr.String("__PackageName__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreatePackage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreatePackage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_CreatePackageImportJob(t *testing.T) {
	input := &CreatePackageImportJobInput{
		JobType: types.PackageImportJobType("NODE_PACKAGE_VERSION"),
		InputConfig: &types.PackageImportJobInputConfig{
			PackageVersionInputConfig: &types.PackageVersionInputConfig{
				S3Location: &types.S3Location{
					Region:     ptr.String("__Region__"),
					BucketName: ptr.String("__BucketName__"),
					ObjectKey:  ptr.String("__ObjectKey__"),
				},
			},
		},
		OutputConfig: &types.PackageImportJobOutputConfig{
			PackageVersionOutputConfig: &types.PackageVersionOutputConfig{
				PackageName:    ptr.String("__PackageName__"),
				PackageVersion: ptr.String("__PackageVersion__"),
				MarkLatest:     true,
			},
		},
		ClientToken: ptr.String("__ClientToken__"),
		JobTags: []types.JobResourceTags{
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
			{
				ResourceType: types.JobResourceType("PACKAGE"),
				Tags: map[string]string{
					"key0": "__Value__",
					"key1": "__Value__",
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.CreatePackageImportJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "CreatePackageImportJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DeleteDevice(t *testing.T) {
	input := &DeleteDeviceInput{
		DeviceId: ptr.String("__DeviceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DeleteDevice(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DeleteDevice"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DeletePackage(t *testing.T) {
	input := &DeletePackageInput{
		PackageId:   ptr.String("__PackageId__"),
		ForceDelete: true,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DeletePackage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DeletePackage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DeregisterPackageVersion(t *testing.T) {
	input := &DeregisterPackageVersionInput{
		OwnerAccount:              ptr.String("__OwnerAccount__"),
		PackageId:                 ptr.String("__PackageId__"),
		PackageVersion:            ptr.String("__PackageVersion__"),
		PatchVersion:              ptr.String("__PatchVersion__"),
		UpdatedLatestPatchVersion: ptr.String("__UpdatedLatestPatchVersion__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DeregisterPackageVersion(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DeregisterPackageVersion"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeApplicationInstance(t *testing.T) {
	input := &DescribeApplicationInstanceInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeApplicationInstance(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeApplicationInstance"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeApplicationInstanceDetails(t *testing.T) {
	input := &DescribeApplicationInstanceDetailsInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeApplicationInstanceDetails(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeApplicationInstanceDetails"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeDevice(t *testing.T) {
	input := &DescribeDeviceInput{
		DeviceId: ptr.String("__DeviceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeDevice(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeDevice"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeDeviceJob(t *testing.T) {
	input := &DescribeDeviceJobInput{
		JobId: ptr.String("__JobId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeDeviceJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeDeviceJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeNode(t *testing.T) {
	input := &DescribeNodeInput{
		NodeId:       ptr.String("__NodeId__"),
		OwnerAccount: ptr.String("__OwnerAccount__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeNode(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeNode"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribeNodeFromTemplateJob(t *testing.T) {
	input := &DescribeNodeFromTemplateJobInput{
		JobId: ptr.String("__JobId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribeNodeFromTemplateJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribeNodeFromTemplateJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribePackage(t *testing.T) {
	input := &DescribePackageInput{
		PackageId: ptr.String("__PackageId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribePackage(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribePackage"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribePackageImportJob(t *testing.T) {
	input := &DescribePackageImportJobInput{
		JobId: ptr.String("__JobId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribePackageImportJob(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribePackageImportJob"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_DescribePackageVersion(t *testing.T) {
	input := &DescribePackageVersionInput{
		OwnerAccount:   ptr.String("__OwnerAccount__"),
		PackageId:      ptr.String("__PackageId__"),
		PackageVersion: ptr.String("__PackageVersion__"),
		PatchVersion:   ptr.String("__PatchVersion__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.DescribePackageVersion(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "DescribePackageVersion"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListApplicationInstanceDependencies(t *testing.T) {
	input := &ListApplicationInstanceDependenciesInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
		MaxResults:            1,
		NextToken:             ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListApplicationInstanceDependencies(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListApplicationInstanceDependencies"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListApplicationInstanceNodeInstances(t *testing.T) {
	input := &ListApplicationInstanceNodeInstancesInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
		MaxResults:            1,
		NextToken:             ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListApplicationInstanceNodeInstances(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListApplicationInstanceNodeInstances"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListApplicationInstances(t *testing.T) {
	input := &ListApplicationInstancesInput{
		DeviceId:     ptr.String("__DeviceId__"),
		StatusFilter: types.StatusFilter("DEPLOYMENT_SUCCEEDED"),
		MaxResults:   1,
		NextToken:    ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListApplicationInstances(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListApplicationInstances"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListDevices(t *testing.T) {
	input := &ListDevicesInput{
		NextToken:                    ptr.String("__NextToken__"),
		MaxResults:                   1,
		SortBy:                       types.ListDevicesSortBy("DEVICE_ID"),
		SortOrder:                    types.SortOrder("ASCENDING"),
		NameFilter:                   ptr.String("__NameFilter__"),
		DeviceAggregatedStatusFilter: types.DeviceAggregatedStatus("ERROR"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListDevices(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListDevices"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListDevicesJobs(t *testing.T) {
	input := &ListDevicesJobsInput{
		DeviceId:   ptr.String("__DeviceId__"),
		NextToken:  ptr.String("__NextToken__"),
		MaxResults: 1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListDevicesJobs(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListDevicesJobs"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListNodeFromTemplateJobs(t *testing.T) {
	input := &ListNodeFromTemplateJobsInput{
		NextToken:  ptr.String("__NextToken__"),
		MaxResults: 1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListNodeFromTemplateJobs(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListNodeFromTemplateJobs"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListNodes(t *testing.T) {
	input := &ListNodesInput{
		Category:       types.NodeCategory("BUSINESS_LOGIC"),
		OwnerAccount:   ptr.String("__OwnerAccount__"),
		PackageName:    ptr.String("__PackageName__"),
		PackageVersion: ptr.String("__PackageVersion__"),
		PatchVersion:   ptr.String("__PatchVersion__"),
		NextToken:      ptr.String("__NextToken__"),
		MaxResults:     1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListNodes(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListNodes"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListPackageImportJobs(t *testing.T) {
	input := &ListPackageImportJobsInput{
		NextToken:  ptr.String("__NextToken__"),
		MaxResults: 1,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListPackageImportJobs(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListPackageImportJobs"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListPackages(t *testing.T) {
	input := &ListPackagesInput{
		MaxResults: 1,
		NextToken:  ptr.String("__NextToken__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListPackages(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListPackages"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ListTagsForResource(t *testing.T) {
	input := &ListTagsForResourceInput{
		ResourceArn: ptr.String("__ResourceArn__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ListTagsForResource(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ListTagsForResource"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_ProvisionDevice(t *testing.T) {
	input := &ProvisionDeviceInput{
		Name:        ptr.String("__Name__"),
		Description: ptr.String("__Description__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
		NetworkingConfiguration: &types.NetworkPayload{
			Ethernet0: &types.EthernetPayload{
				ConnectionType: types.ConnectionType("STATIC_IP"),
				StaticIpConnectionInfo: &types.StaticIpConnectionInfo{
					IpAddress: ptr.String("__IpAddress__"),
					Mask:      ptr.String("__Mask__"),
					Dns: []string{
						"__Member__",
						"__Member__",
					},
					DefaultGateway: ptr.String("__DefaultGateway__"),
				},
			},
			Ethernet1: &types.EthernetPayload{
				ConnectionType: types.ConnectionType("STATIC_IP"),
				StaticIpConnectionInfo: &types.StaticIpConnectionInfo{
					IpAddress: ptr.String("__IpAddress__"),
					Mask:      ptr.String("__Mask__"),
					Dns: []string{
						"__Member__",
						"__Member__",
					},
					DefaultGateway: ptr.String("__DefaultGateway__"),
				},
			},
			Ntp: &types.NtpPayload{
				NtpServers: []string{
					"__Member__",
					"__Member__",
				},
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.ProvisionDevice(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "ProvisionDevice"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_RegisterPackageVersion(t *testing.T) {
	input := &RegisterPackageVersionInput{
		OwnerAccount:   ptr.String("__OwnerAccount__"),
		PackageId:      ptr.String("__PackageId__"),
		PackageVersion: ptr.String("__PackageVersion__"),
		PatchVersion:   ptr.String("__PatchVersion__"),
		MarkLatest:     true,
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.RegisterPackageVersion(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "RegisterPackageVersion"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_RemoveApplicationInstance(t *testing.T) {
	input := &RemoveApplicationInstanceInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.RemoveApplicationInstance(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "RemoveApplicationInstance"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_SignalApplicationInstanceNodeInstances(t *testing.T) {
	input := &SignalApplicationInstanceNodeInstancesInput{
		ApplicationInstanceId: ptr.String("__ApplicationInstanceId__"),
		NodeSignals: []types.NodeSignal{
			{
				NodeInstanceId: ptr.String("__NodeInstanceId__"),
				Signal:         types.NodeSignalValue("PAUSE"),
			},
			{
				NodeInstanceId: ptr.String("__NodeInstanceId__"),
				Signal:         types.NodeSignalValue("PAUSE"),
			},
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.SignalApplicationInstanceNodeInstances(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "SignalApplicationInstanceNodeInstances"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_TagResource(t *testing.T) {
	input := &TagResourceInput{
		ResourceArn: ptr.String("__ResourceArn__"),
		Tags: map[string]string{
			"key0": "__Value__",
			"key1": "__Value__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.TagResource(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "TagResource"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_UntagResource(t *testing.T) {
	input := &UntagResourceInput{
		ResourceArn: ptr.String("__ResourceArn__"),
		TagKeys: []string{
			"__Member__",
			"__Member__",
		},
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.UntagResource(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "UntagResource"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}

func TestSerdeUpdateSnapshot_UpdateDeviceMetadata(t *testing.T) {
	input := &UpdateDeviceMetadataInput{
		DeviceId:    ptr.String("__DeviceId__"),
		Description: ptr.String("__Description__"),
	}
	body := &bytes.Buffer{}
	method := ""
	rawPath := ""
	rawQuery := ""
	header := map[string][]string{}
	svc := serdeNewClient()
	_, err := svc.UpdateDeviceMetadata(context.Background(), input, func(o *Options) {
		o.APIOptions = append(o.APIOptions, func(stack *middleware.Stack) error {
			stack.Initialize.Remove("OperationInputValidation")
			return stack.Finalize.Add(&captureSerdeRequestMiddleware{
				body: body, method: &method, rawPath: &rawPath, rawQuery: &rawQuery, header: &header,
			}, middleware.Before)
		})
	})
	if err != nil && !strings.Contains(err.Error(), "error: success") {
		t.Fatal(err)
	}
	if err := serdeUpdateSnapshot(method, rawPath, rawQuery, header, body.Bytes(), "UpdateDeviceMetadata"); err != nil {
		if err != nil && !strings.Contains(err.Error(), "error: success") {
			t.Fatal(err)
		}
	}
}
